app/charts/area/chart-area.tsx
app/charts/shared/chart-helpers.tsx
app/components/chart-published.tsx

Smallish refactor on the published chart file to prevent code duplication and drift.
Since it can be a bit "invasive" and since I had to had a @ts-ignore, I prefer to keep this commit out of the next release.

Refactor published chart

---

app/configurator/components/chart-options-selector.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

Closes #213.
@herrstucki could you confirm that the German version looks good? @ortnever mentioned that we should verify this + the English version. Thanks!

Update translations for missing data imputation

---

app/homepage/intro.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

fix: Align theme wording between homepage and nav

---

app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

Not really sure why they appeared 🤔
Closes #226.

Remove <<<<< HEAD from some German translations

---

app/components/browsing-autocomplete.tsx
app/homepage/intro.tsx

- feat: Re-introduce the "create viz" CTA for homepage intro
- feat: Remove icons in homepage intro

Homepage tweaks

---

app/configurator/components/select-dataset-step.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

Add datasets title

---

app/docs/cube-update-constraints.mdx
app/pages/docs.tsx

Add documentation on how to safely update a cube so that charts still work.

docs: Add cube update rules

---

app/graphql/resolvers.ts
app/pages/api/graphql.ts
app/rdf/queries.ts

Added DataLoader for dimension values.

Use DataLoader for dimension values

---

app/configurator/components/chart-controls/control-tab.tsx
app/configurator/components/chart-controls/drag-and-drop-tab.tsx

Buttons are not draggable with react-dnd. We have to put `as='div'` onto theme ui Button.

fix: Make column groups draggable on all the column row

---

app/charts/map/chart-map.tsx

feat: Remove map border

---

app/charts/map/map-legend.tsx

fix: Undefined observations in map circle legend

---

app/configurator/components/filters.tsx
yarn.lock

Previously, only the min/max were returned in the values. Now that
values are returned (necessary for date picker), we need to use the
last values and not the 2nd one for the max value.
fix https://github.com/visualize-admin/visualization-tool/issues/316

fix: Ability to use date filter for time dimension in days

---

app/charts/column/chart-column.tsx
app/charts/column/columns-grouped-state.tsx
app/charts/column/columns-grouped.tsx
app/charts/column/columns-simple.tsx
app/charts/column/columns-state.tsx
app/charts/shared/interaction/tooltip-box.tsx
app/charts/shared/interaction/tooltip-content.tsx
app/charts/shared/interaction/tooltip.tsx
app/charts/whiskers.tsx
app/configurator/components/ui-helpers.ts
yarn.lock

Preview here : https://visualize-ad-error-bars-xqzebf.herokuapp.com/en/create/new?from=kbIrSDxJKLqL

Error bars 2

---

app/charts/map/chart-map.tsx
app/charts/map/map.tsx

Fixes #363.
Changes the logic so the booleans are used for map rendering condition.

Use booleans in map rendering condition

---

app/charts/map/get-base-layer-style.ts
app/charts/map/map.tsx
app/package.json
yarn.lock

Map style updates

---

app/charts/map/get-base-layer-style.ts

Changed visibility of text layers, so there are no "alone" points and rectangles without labels.

Hide all elements related to labels, not only text

---

app/components/search-autocomplete.tsx
app/configurator/components/dataset-browse.tsx
app/configurator/components/use-dataset-count.tsx
app/graphql/queries/data-cubes.graphql
app/graphql/query-hooks.ts
app/graphql/resolver-types.ts
app/graphql/resolvers.ts
app/graphql/schema.graphql
app/rdf/query-cube-metadata.ts

fix #391
- fix: Consider include drafts checkbox when computing search counts
- feat: Keep search and includeDrafts when clicking inside nav panel

Fix search and drafts count

---

app/configurator/map/map-chart-options.tsx

Fix: map filter icons

---

app/charts/map/map-tooltip.tsx

Show "-" if no data is attached to a shape in maps

---

app/charts/map/chart-map.tsx
app/charts/map/helpers.ts

Fix geo coords loading error

---

CHANGELOG.md
app/charts/map/map-tooltip.tsx

+ a small refactor for better readability

fix: Map tooltip text color

---

CHANGELOG.md
app/test/__fixtures/api/cubes-list.json
app/utils/search.spec.ts
app/utils/search.ts

- fix: Trim search string and lower case it
- chore: Add test for search various cases

Search small improvements

---

app/components/chart-footnotes.tsx
app/components/data-download.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/package.json
app/pages/api/download.ts
yarn.lock

This PR:
- adds an option to download either visible or full dataset,
- adds an option to download data either in CSV or XLSX.

Add full data download (CSV | XLSX)

---

app/components/chart-footnotes.tsx
app/components/data-download.tsx
app/configurator/components/dataset-preview.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/package.json
app/pages/api/download.ts
app/themes/federal.tsx
yarn.lock

This PR adds new data download UI (popover).

Upgrade data download UI

---

CHANGELOG.md
app/charts/pie/chart-pie.tsx

Change pie legend symbol to square

---

app/graphql/queries/data-cubes.graphql
app/graphql/query-hooks.ts
app/package.json
app/rdf/queries.ts
app/typings/rdf.d.ts
yarn.lock

- feat: Disable distinct when there is no filter to improve performance
- feat: Add way to limit the observations query

Loading observations improvements

---

app/rdf/query-geo-coordinates.ts

This PR fixes SPARQL query for fetching geoCoordinates from unversioned dimensions.

Fix loading of unversioned geo coordinates

---

app/components/form.tsx
app/configurator/components/chart-annotations-selector.tsx
app/configurator/components/dataset-browse.tsx
app/configurator/configurator-state.tsx
app/pages/v/[chartId].tsx
app/themes/federal.tsx

- feat: Remove submit button
- feat: Show navigation items if there are no results

Search tweaks

---

CHANGELOG.md
app/components/footer.tsx
app/configurator/components/dataset-browse.tsx
app/configurator/components/presence.tsx
app/configurator/components/select-dataset-step.tsx
app/test/__fixtures/api/cubes-list.json
app/utils/search.spec.ts

Simple things that I noticed while working on other things.
- feat: Only show top 7 items in nav (design alignment)
- feat: Add footer to search results page
- feat: Add test to search with diacritics

Small improvements

---

app/components/chart-selection-tabs.tsx
app/configurator/components/chart-type-selector.tsx
app/themes/federal.tsx

Closes #515.
Small adjustments to the tabs UI based on conversation in #515.

feat: Tabs UI refinements

---

app/configurator/components/dataset-preview.tsx

feat: Move DataDownload button to the left in dataset preview panel

---

app/pages/v/[chartId].tsx

- fix: On mobile chart published do not overflow
- fix: When downsizing the window, a published chart will resize correctly
- fix: Correctly display chart actions on mobile

Published chart responsiveness

---

app/charts/shared/chart-data-filters.tsx
app/components/chart-preview.tsx
app/components/chart-published.tsx

fix: Show ChartFiltersList when IE DataFilters are empty

---

app/charts/map/map.tsx
app/components/chart-footnotes.tsx
app/components/chart-panel.tsx
app/components/chart-preview.tsx
app/components/chart-published.tsx
app/components/chart-selection-tabs.tsx
app/configurator/components/datatable.tsx
app/configurator/components/stepper.tsx
app/lib/use-resize-observer.ts
app/pages/_charts.tsx
app/themes/federal.tsx

- feat: Tab whole content is clickable: fix https://github.com/visualize-admin/visualization-tool/issues/548
- fix: Better fit for map features (no need for padding), fixes https://github.com/visualize-admin/visualization-tool/issues/550
- fix: Footnotes elements wrap, fixes https://github.com/visualize-admin/visualization-tool/issues/549
- feat: Table has same height as chart, fixes https://github.com/visualize-admin/visualization-tool/issues/549
- fix: Better handling of back button, fixes https://github.com/visualize-admin/visualization-tool/issues/542

UX fixes from user feedback

---

app/components/footer.tsx
app/components/hint.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

- feat: Add footer to search results page
- feat: Add mention of page status in data loading error hint

Status page links

---

app/homepage/examples.tsx

fix: Update homepage chart URLs following data reset on int.lindas.admin.ch

---

app/components/chart-footnotes.tsx
app/graphql/queries/data-cubes.graphql
app/graphql/query-hooks.ts
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

Add a link to the landing page in footnotes.

Add link to landing page in footnotes

---

app/configurator/components/datatable.tsx
app/graphql/queries/data-cubes.graphql
app/graphql/query-hooks.ts
app/graphql/resolver-types.ts
app/graphql/resolvers.ts
app/graphql/schema.graphql
app/graphql/shared-types.ts
app/rdf/parse.ts

- feat: Parse sh:order from dimensions and use it to sort columns of preview table

Order columns for data preview table

---

CHANGELOG.md
app/domain/env.ts
app/graphql/resolvers/rdf.ts

Data Source Selection Improvements

---

app/charts/table/table.tsx
app/configurator/interactive-filters/editor-time-brush.tsx
app/graphql/context.tsx
app/graphql/resolver-types.ts
app/graphql/resolvers.spec.ts
app/graphql/resolvers/index.ts
app/graphql/resolvers/rdf.ts
app/pages/api/graphql.ts
app/rdf/cube-filters.ts
app/rdf/parse.ts
app/rdf/queries.ts
codegen.yml

Splitted commits that were not realted to search from the [search PR](https://github.com/visualize-admin/visualization-tool/pull/611). Will merge as soon as CI is green as the PR was already reviewed.

GraphQL context improvements

---

app/configurator/components/filters.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

Add a button to refresh colors based on what's selected.
To be checked with @AnninaWalker

Refresh colors

---

app/charts/shared/legend-color.tsx
app/components/form.tsx
app/configurator/components/chart-configurator.tsx
app/configurator/components/chart-controls/color-palette.tsx
app/configurator/components/chart-controls/color-ramp.tsx
app/configurator/components/filters.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/themes/federal.tsx
app/utils/interlace.ts

- refactor: Remove unused props
- fix: Correct margin for labels
- fix: Interlace would fail if array length was 0
- refactor: Remove unneeded Box
- refactor: Use Select + MenuItem for color palette selector

Fix color segmentation

---

app/configurator/components/filters.tsx

- fix: UI tweaks for filters options
- fix: Correctly get color mapping from config

Filter fixes

---

app/charts/area/chart-area.tsx
app/charts/bar/chart-bar.tsx
app/charts/column/chart-column.tsx
app/charts/scatterplot/chart-scatterplot.tsx
app/charts/shared/legend-color.tsx
app/configurator/components/chart-controls/color-palette.tsx

- feat: Avoid layout jump due to appearing reset color button
- feat: Design alignment
- feat: Legend items are shaped according to their chart

Legend improvements

---

app/components/debug-search.tsx
app/rdf/query-search.ts

- refactor: Extract makeVisualize filters to make query clearer
- fix: Organization search did not work
- fix: Return cubes without version history
- feat: Add response time to search debug page
Fix https://github.com/visualize-admin/visualization-tool/issues/635

Organization search

---

app/components/data-source-menu.tsx
app/components/header.tsx
app/configurator/components/dataset-browse.tsx
app/configurator/components/use-dataset-count.tsx
app/configurator/configurator-state.tsx
app/lib/use-sync-router-param.ts

To fix some bugs when sharing links to dataset previews, data source is now also stored in URL.

feat: Save DataSource label in the URL

---

app/components/data-source-menu.tsx
app/docs/rdf-to-visualize.mdx
app/pages/_cube-checker.tsx

- fix: Fix docs/ route infinite loop
- fix: Do not save in localStorage nor in URL the dataSource if it's the same as the default one
- feat: Add theme + organisation check to cube checker
- docs: Add link to cube checker inside docs

Cube checker improvements

---

app/configurator/components/chart-controls/control-tab.tsx
app/configurator/components/empty-right-panel.tsx
app/themes/federal.tsx

Font alignments

---

app/pages/__test/[env]/[slug].tsx

I think that at some point tests folder structure changed, there was a need to update it to make tests run again.

fix: Cypress tests

---

app/components/chart-panel.tsx
app/components/chart-selection-tabs.tsx
app/configurator/components/chart-configurator.tsx
app/configurator/components/chart-type-selector.tsx

This PR brings chart selection via tab back.

feat: Reintroduce chart selection popup

---

app/charts/index.ts
app/configurator/components/chart-configurator.tsx
app/configurator/components/chart-type-selector.tsx
app/configurator/config-form.tsx

The selection of default state would only work on the second attempt.
Before I had put the logic at the wrong place in getAdjustedConfig where in fact it needs to be in getInitialConfig to work 
correctly.
I do not know how I missed that 🤷

Map default state

---

app/docs/rdf-to-visualize.mdx

Add how currencies are displayed, using the dimension information, inside
the catalog documentation.﻿

docs: Add how currencies are managed

---

app/components/hint.tsx

Use correct color for loading otherwise it cannot be seen.
Fix https://github.com/visualize-admin/visualization-tool/issues/668

Show search loading indication

---

app/components/chart-published.tsx

Fix https://github.com/visualize-admin/visualization-tool/issues/670﻿

fix: Do not let table spill over footnotes

---

app/charts/map/map.tsx

feat: Disable rotation & tilting of the map on desktop

---

app/package.json
yarn.lock

Through update of cube-hierarchy-query
Fix https://github.com/visualize-admin/visualization-tool/issues/664

fix: No label for root without children

---

app/locales/fr/messages.po
app/locales/it/messages.po

Locale text was incorrect.
Fix https://github.com/visualize-admin/visualization-tool/issues/681

fix: Results number is correct in French and Italian

---

.github/workflows/lint-test.yml
cypress/integration/edition.spec.ts

The edition test is failing on the CI, while it's working locally.

Fix cypress tests

---

app/charts/map/map.tsx

feat: Disable map rotation & tilting

---

app/charts/map/constants.ts
app/charts/map/map-legend.tsx
eslint/visualize-admin/make-styles.js

- fix: Use correct default color
- feat: Add small transition on map legend indicator
- chore: Defensive programming on eslint rule

fix: Use correct default color

---

app/charts/map/map.tsx

feat: Re-introduce water & roads on top of Area Layer

---

app/charts/map/map.tsx

Fix https://github.com/visualize-admin/visualization-tool/issues/724﻿

fix: Show area layer even when base layer is off

---

app/components/chart-footnotes.tsx
app/graphql/queries/data-cubes.graphql
app/graphql/query-hooks.ts
app/graphql/resolver-types.ts
app/graphql/resolvers/index.ts
app/graphql/schema.graphql
app/graphql/shared-types.ts
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/rdf/parse.ts

Chart update in footnotes
Show when the data for the current chart has been updated.
Fix #759

Add latest update date to chart footnotes

---

CHANGELOG.md
app/components/hint.tsx
app/docs/rdf-to-visualize.mdx
app/graphql/resolvers/index.ts

Better error message based on #766.

feat: Better timeFormat missing error

---

app/charts/map/map.tsx
e2e/chart-snapshots.spec.ts
e2e/selectors.ts

test: Waits for tiles to be loaded before screenshotting the map

---

app/configurator/components/filters.tsx
playwright.config.ts

- fix: Show filter drawer on the left

Fix drawer layout

---

app/components/data-download.tsx
app/pages/api/download.ts

feat: Increase data download size limit

---

app/configurator/components/filters.tsx
e2e/color-mapping-maps.spec.ts
e2e/edition.spec.ts
e2e/fixtures/offentliche-ausgaben-chart-config.json
e2e/tooltip.spec.ts

feat: Hierarchies filters drawer UI refinements

---

app/charts/line/lines-state.tsx

Fixes #859.
Broken E2E test will be fixed by #855.

fix: Lines tooltip value colors

---

app/configurator/components/configurator.tsx
app/configurator/components/dataset-browse.tsx
app/configurator/components/use-redirect-to-versioned-cube.spec.tsx
e2e/actions.ts
e2e/unversioned.spec.ts

- feat: Use dataset from URL param

Dataset preview URL

---

app/components/select-tree.tsx

- Add check icon if value is selected
- Anchor select tree popover to the bottom of the anchor
- Fix popover position when select is opened programmatically

feat: Adjustments to select tree

---

app/configurator/components/dataset-browse.tsx
e2e/filters.spec.ts
e2e/high-filter-value-count.spec.ts
e2e/tooltip.spec.ts

- test: Deactivate failing test due to bad data
- test: Increase timeouts
- fix: Nav filters work again

Fix navigation

---

app/configurator/components/chart-options-selector.tsx
app/configurator/table/table-chart-options.tsx

fix: Can show numerical measure in table configurator

---

app/configurator/components/presence.tsx
app/configurator/components/select-dataset-step.tsx
e2e/filters.spec.ts
e2e/interactive-filters.spec.ts

Fix https://github.com/visualize-admin/visualization-tool/issues/897

feat: Diminish banner height

---

app/charts/shared/legend-color-helpers.ts
app/charts/shared/legend-color.spec.ts
app/charts/shared/legend-color.tsx
app/graphql/queries/data-cubes.graphql
app/graphql/query-hooks.ts
app/graphql/resolver-types.ts
app/graphql/schema.graphql
app/rdf/query-hierarchies.ts
e2e/abbreviations.spec.ts

This PR fixes a Color Legend when using abbreviations for hierarchical dimensions.

fix: Abbreviations for color legend for hierarchies

---

app/configurator/components/filters.tsx

fix: Padding of last level hierarchy in filters

---

app/components/metadata-panel.tsx

https://github.com/visualize-admin/visualization-tool/issues/917#issuecomment-1337587807

feat: Metadata panel tweaks

---

app/charts/shared/axis-height-linear.tsx
app/charts/shared/axis-width-linear.tsx
app/components/metadata-panel.tsx
app/configurator/components/chart-configurator.tsx
app/configurator/components/configurator.tsx
app/domain/data.ts
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/rdf/queries.ts
app/rdf/query-dimension-values.ts

Closes #917.
- Design adjustments (font sizes, text underlines, colors, button styling)
- Mix & max values for numerical & standard error dimensions are now always loaded
cc: @AnninaWalker

feat: Metadata panel enhancements continuation

---

app/charts/shared/chart-data-filters.tsx
app/charts/shared/legend-color.tsx
app/configurator/components/chart-configurator.tsx
app/gql-flamegraph/devtool.tsx
app/graphql/queries/data-cubes.graphql
app/graphql/query-hooks.ts
app/rdf/queries.ts
app/rdf/query-literals.ts
e2e/abbreviations.spec.ts

Since abbreviations were not filtered by locale, in cases were abbreviations were localized, we could have multiple different locales competing.
Fix https://github.com/visualize-admin/visualization-tool/issues/991

Abbreviations

---

app/.gitignore
app/domain/env.ts
app/graphql/apollo-sentry-plugin.ts
app/next.config.js
app/package.json
app/pages/_error.js
app/pages/api/graphql.ts
app/sentry.client.config.js
app/sentry.edge.config.js
app/sentry.properties
app/sentry.server.config.js
yarn.lock

With this we will get informed and have basic instrumentation in Sentry- feat: Add sentry next js integration
- feat: Apollo sentry integration
See https://interactive-things.sentry.io/performance/?isDefaultQuery=false&metricSearchSetting=transactionsOnly&project=4504922724040704&query=GQL

feat: Add sentry next js integration

---

app/charts/map/map.tsx
app/charts/map/ref.ts

Fixes #1032.
1. Open `Forest fire danger` dataset.
2. Change chart type to map.
3. Publish a chart.
4. Change a language.
5. Copy and edit the chart.
6. See that both above actions work.

fix: Undefined Map handlers during unmount

---

app/components/hint.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

feat: Update Spinner text

---

.github/workflows/manual-load-test.yml
README.md
k6/graphql/components.js
k6/graphql/observations.js
k6/graphql/utils.js
k6/har/int/edition.js
k6/har/prod/edition.js
k6/har/test/edition.js

test: Add an ability to control server-side GQL cache when doing load tests

---

app/utils/sorting-values.spec.ts
app/utils/sorting-values.ts

fix: Wrong sorting order if identifier is equal to 0

---

CHANGELOG.md
app/browse/datatable.tsx
app/charts/table/table-state.tsx
app/utils/sorting-values.spec.ts
app/utils/sorting-values.ts

fix: Sorting of numerical dimensions

---

CHANGELOG.md
app/charts/area/areas-state.tsx
app/charts/area/rendering-utils.ts
app/charts/chart-config-ui-options.ts
app/charts/column/columns-grouped-state.tsx
app/charts/column/columns-stacked-state.tsx
app/charts/column/columns-state.tsx
app/charts/pie/pie-state.tsx
app/charts/shared/chart-dimensions.tsx
app/charts/shared/chart-helpers.tsx
app/charts/shared/legend-color.tsx
app/charts/shared/stacked-helpers.ts
app/components/chart-footnotes.tsx
app/components/chart-published.tsx
app/components/form.tsx
app/configurator/components/chart-annotator.tsx
app/configurator/components/chart-configurator.tsx
app/configurator/components/chart-controls/control-tab.tsx
app/configurator/components/chart-controls/section.tsx
app/configurator/components/chart-options-selector.tsx
app/configurator/components/field.tsx
app/configurator/components/filters.tsx
app/configurator/configurator-state.tsx
app/configurator/interactive-filters/interactive-filters-configurator.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/themes/federal.tsx

Closes #541.
Closes #1060.
This PR:
- adds icon tooltip with warning message to chart mode section,
- improves visibility of imputation section,
- makes the segment options only appear when a dimension is selected,
- makes the percentage formatting in tooltips consistent across charts (https://github.com/visualize-admin/visualization-tool/issues/1092#issuecomment-1676926586),
- fixes https://github.com/visualize-admin/visualization-tool/issues/1091#issuecomment-1677061226

feat: General improvements

---

app/docs/annotations.docs.tsx
app/docs/chart-config.tsx
app/docs/columns.docs.tsx
app/docs/lines.docs.tsx
app/docs/rdf-to-visualize.mdx
app/docs/scatterplot.docs.tsx

docs: Update docs

---

CHANGELOG.md
app/components/use-redirect-to-versioned-cube.tsx

Fixes #1125.
1. Go to `/browse?dataSource=Prod&type=dataset&iri=https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2Fstapfer-enquete-1799&dataset=https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2Fstapfer-enquete-1799%2F2`.
2. See that the dataset loads.
3. Go to the same link on PROD and see that it does not load.

fix: Need to replace iri if type=dataset

---

CHANGELOG.md
app/charts/map/chart-map.tsx
app/components/hint.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

Closes #1137.
This PR adds an error message when no geometries are available.

feat: Show error when no geometries are available

---

app/charts/chart-config-ui-options.ts
app/components/header.tsx
app/components/layout.tsx
app/static-pages/de/rechtliche-grundlagen.mdx
app/static-pages/en/legal-framework.mdx
app/static-pages/fr/cadre-juridique.mdx
app/static-pages/it/quadro-giuridico.mdx

docs: Update legal framework

---

CHANGELOG.md
app/rdf/queries.ts

chore: Improve langString error message

---

CHANGELOG.md
app/charts/chart-config-ui-options.ts

fix: Initialize color mapping with all values

---

app/docs/testing.mdx

docs: Update testing docs

---

CHANGELOG.md
app/utils/observables.ts

feat: Show latest data when animation is enabled

---

CHANGELOG.md
app/components/select-tree.tsx

fix: Use the same y padding across different filters

---

.github/workflows/docker-build-dev.yml
.github/workflows/docker-build-release.yml

...due to a problem with next-auth library not passing NEXTAUTH_URL in CI.
https://github.com/nextauthjs/next-auth/issues/6479
https://github.com/nextauthjs/next-auth/issues/3286
https://github.com/nextauthjs/next-auth/discussions/7699

build: Disable automatic Docker image build

---

CHANGELOG.md
app/charts/map/map.tsx

style: Outline map shapes of hover

---

app/docs/chart-preview-via-api.mdx

Fixes #1239.
cc @lloydrichards

chore: Fix docs typo

---

app/graphql/hook-utils.spec.ts
app/graphql/hook-utils.ts

fix: Enable merge observations tests

---

CHANGELOG.md
app/components/data-download.tsx

This PR adds explicit UTF-8 encoding to downloaded files.

fix: Add UTF-8 charset hint to data type (data download)

---

app/charts/table/chart-table.tsx

fix: Table filters

---

app/configurator/configurator-state.tsx

This PR fixes data source changes.

fix: Data source changes

---

app/config-types.ts
app/configurator/components/configurator.tsx
app/configurator/components/layout-configurator.tsx

- Remove flag
- Change default dashboard mode

feat: Smaller dashboards improvements

---

app/rdf/query-dimension-values.ts

After a discussion with @Rdataflow, the issue that originally led to the inclusion of other dimension iris in the dimension values query was due to the data issue; it turns out the query doesn't need to be changed (due to performance reasons), but rather the data.
See the original issue in [PR description](https://github.com/visualize-admin/visualization-tool/pull/1360) and [here](https://github.com/visualize-admin/visualization-tool/pull/1360#discussion_r1504098838).

perf: Do not include other dimension iris when fetching dimension values

---

app/browser/filters.tsx
app/browser/select-dataset-step.tsx
app/charts/chart-config-ui-options.ts
app/charts/chart-data-wrapper.tsx
app/charts/shared/interaction/tooltip.tsx
app/components/debug-search.tsx
app/components/metadata-panel.tsx
app/config-types.ts
app/configurator/components/add-dataset-dialog.tsx
app/configurator/components/chart-configurator.tsx
app/configurator/components/chart-controls/control-tab.tsx
app/configurator/components/chart-options-selector.tsx
app/configurator/components/field.tsx
app/configurator/components/ui-helpers.ts
app/configurator/configurator-state.mock.ts
app/configurator/configurator-state.spec.tsx
app/configurator/configurator-state.tsx
app/configurator/interactive-filters/interactive-filters-configurator.tsx
app/graphql/hooks.ts
app/graphql/query-hooks.ts
app/graphql/resolver-types.ts
app/graphql/schema.graphql
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/package.json
app/rdf/cube-filters.ts
app/rdf/query-search.ts
yarn.lock

Improvements on the add dataset functionality.
- refactor: Extract out make search query
- refactor: Use enum for SearchCubeFilterType
- fix: Use correct value for TemporalDimension
- fix: Use correct component iri when tweaking iri to be joinBy
- feat: ControlTabField handle multi components field
- fix: Missing localized string
- wip fix nan
- feat: Show multiple for vertical axis in case of combo chart + show merged temporal dimension according to time unit
- feat: Use chart spec to known where are the iri attributes
- feat: Show correct dimension label in metadata panel

Add dataset improvements in filter and metadata panel

---

CHANGELOG.md
app/graphql/context.tsx
app/graphql/query-hooks.ts
app/graphql/resolver-types.ts
app/graphql/resolvers/index.ts
app/graphql/resolvers/rdf.ts
app/graphql/resolvers/sql.ts
app/graphql/schema.graphql
app/rdf/query-hierarchies.ts

Closes #1405
---
This PR parallelizes loading of dimension values and hierarchies.

perf: Load dimension values and hierarchies in parallel

---

app/components/confirmation-dialog.tsx

fix: Closing confirmation dialog

---

CHANGELOG.md
app/configurator/components/chart-type-selector.tsx

style: UI improvements

---

app/charts/shared/chart-data-filters.tsx
app/components/form.tsx

fix: Smaller issues

---

app/components/tag.tsx
app/configurator/components/add-dataset-dialog.tsx
app/configurator/components/beta-tag.tsx
app/configurator/components/chart-configurator.tsx
app/configurator/components/dataset-control-section.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

- fix: No shadow on tag if not clickable
- fix: Missing translations
- feat: Add beta tag

Beta tag for merging cubes

---

app/components/hint.tsx
app/configurator/components/add-dataset-dialog.tsx
app/configurator/components/beta-tag.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/rdf/query-search.ts
app/utils/clipboard.ts
e2e/filters.spec.ts
e2e/ordinal-measures.spec.ts
e2e/selectors.ts
e2e/tooltip.spec.ts

This adds a dimension selector to the preview when selecting a second 
cube to add, similar to what's done in Notion.

Dimension selector in add dataset search preview

---

app/rdf/queries.ts

see also https://github.com/visualize-admin/visualization-tool/commit/ac4db2ebf39ef57b7afc4cefd0b3f87831f01ee5
WRT https://github.com/zazuko/cube-creator/issues/1243
cc @ptbrowne

drop legacy hasHierarchy

---

app/rdf/query-dimension-values.ts

fix: Missing dimension iri

---

app/rdf/query-dimension-values.ts
e2e/named-nodes.spec.ts

Fixes #1497
Fixes regression from https://github.com/visualize-admin/visualization-tool/commit/908ddd71fa593fbb8dab5ae99936ff6eaf76d3a7 (metadata is only attached to versioned values)

fix: Dimension values unversioning

---

app/homepage/examples.tsx

Fixes #1498
This PR adds automatic cube upgrades to demo charts.

fix: Upgrade demo cubes

---

app/components/info-icon-tooltip.tsx
app/components/metadata-panel.tsx
app/configurator/components/add-dataset-dialog.tsx
app/configurator/components/chart-type-selector.tsx
app/configurator/components/info-icon-tooltip.tsx
app/docs/tooltip.stories.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/themes/federal.tsx
app/utils/use-local-state.ts

Metadata panel
- Show additional information for joined dimensions in metadata panel
- Add info icon tooltip to joined dimensions in metadata panel
Add dataset dialog
- Show caution alert (state saved in local storage)

Joined dimensions improvements

---

app/pages/_preview.tsx
app/pages/preview.tsx

Multiple problems were fixed.
- Needed to wrap the ChartPublished inside a ChartConfiguratorState provider
- Change config that was triggering a Stardog error (:shrug:)
- Migrate config to latest version

Fix preview

---

app/icons/components/IcDuplicate.tsx
app/icons/svg/ic_duplicate.svg

fix: Correct DuplicateIcon sizing

---

app/browser/context.tsx
app/browser/dataset-browse.tsx
app/browser/filters.tsx
app/browser/select-dataset-step.tsx
app/pages/browse/index.tsx

fix: Filtering by termsets

---

app/auth-providers/adfs.ts
app/browser/context.tsx

fix: Keeping search controls state when rendered in a drawer

---

app/components/react-grid.tsx

fix: Assure the layouts adhere to min and max constraints

---

app/browser/select-dataset-step.tsx

fix: Search page title

---

app/configurator/components/badges.tsx
app/configurator/components/chart-configurator.tsx
app/configurator/components/dataset-control-section.tsx

fix: Datasets count

---

app/components/chart-selection-tabs.tsx

Allow not to have a label for the tab.

feat: Allow a tab not to have a label

---

app/login/components/profile-tables.tsx

- **fix: Allow for text overflow ellipsis to work in table**
- **feat: Use dashboard title in profile**
fixes https://github.com/visualize-admin/visualization-tool/issues/1600

Config title in profile

---

app/docs/catalog/chart-preview-via-api.mdx
app/pages/_preview.tsx
app/pages/_preview_post.tsx
app/pages/preview.tsx
app/pages/preview_post.tsx

Closes #1605
This PR makes it possible to set chart's language when using preview via API feature.

feat: Localized charts via API

---

app/locales/de/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/login/components/profile-tables.tsx
app/pages/v/[chartId].tsx

feat: User profile page improvements

---

app/charts/area/areas-state.tsx
app/charts/area/chart-area.tsx
app/charts/column/chart-column.tsx
app/charts/column/columns-grouped-state.tsx
app/charts/column/columns-stacked-state.tsx
app/charts/column/columns-state.tsx
app/charts/combo/chart-combo-line-column.tsx
app/charts/combo/chart-combo-line-dual.tsx
app/charts/combo/chart-combo-line-single.tsx
app/charts/combo/combo-line-column-state.tsx
app/charts/combo/combo-line-dual-state.tsx
app/charts/combo/combo-line-single-state.tsx
app/charts/line/chart-lines.tsx
app/charts/line/lines-state.tsx
app/charts/map/chart-map.tsx
app/charts/pie/chart-pie.tsx
app/charts/pie/pie-state.tsx
app/charts/scatterplot/chart-scatterplot.tsx
app/charts/scatterplot/scatterplot-state.tsx
app/charts/shared/chart-dimensions.tsx
app/charts/shared/containers.tsx
app/components/react-grid.tsx
app/configurator/configurator-state/index.tsx
app/docs/charts.stories.tsx
app/docs/datatable.stories.tsx
app/docs/lines.stories.tsx

Fixes #1665
1. Go to [this link](https://int.visualize.admin.ch/en/v/YzDlIzcQKrT6?dataSource=Int).
2. ❌ See that the chart is really short.
1. Go to [this link](https://visualization-tool-git-fix-container-size-ixt1.vercel.app/en/v/_sef-ZIvhwoc?dataSource=Prod).
2. ✅ See that the chart is displayed as expected.
3. ✅ Compare with the [same chart from Visualize PROD](https://visualize.admin.ch/en/v/IqjL1uuEeQPw?dataSource=Prod).

fix: Container size

---

app/charts/map/map.tsx

Fixes #1663
1. Go to [this link](https://visualization-tool-git-fix-map-center-ixt1.vercel.app/en/v/SMoHiVNj1YNQ?dataSource=Prod).
2. Copy and edit the chart (using a button below the chart).
3. ✅ See that the map is centered on Switzerland.

fix: Initial map state

---

app/charts/shared/containers.tsx
app/components/react-grid.tsx

This PR addresses https://github.com/visualize-admin/visualization-tool/pull/1647#discussion_r1695140287 and improves resizing behavior of e.g. column charts with very long X axis labels.

refactor: Min height in free canvas layout

---

app/charts/combo/axis-height-linear-dual.tsx
app/charts/combo/chart-combo-line-dual.tsx
app/charts/combo/combo-line-container.tsx
app/charts/combo/combo-line-dual-state.tsx
app/charts/map/map-legend.tsx
app/charts/shared/use-chart-theme.ts

Just increased the Tooltip delay by a few seconds, after clicking "Save Draft"

fix: Delayed Tooltip for Save my Draft

---

app/browser/select-dataset-step.tsx
app/components/dashboard-interactive-filters.tsx
app/configurator/components/configurator.tsx
app/configurator/components/layout.tsx
app/configurator/components/preview-breakpoint.tsx

fix: Layout step styling adjustments

---

app/configurator/components/configurator.tsx
app/utils/ui-strings.spec.tsx

style: Make the clicked link blue

---

CHANGELOG.md
app/configurator/components/annotators.tsx

fix: Inconsistent title and description fields behavior

---

app/charts/shared/containers.tsx
app/configurator/components/dataset-control-section.tsx
app/static-pages/de/index.mdx
app/static-pages/en/index.mdx
app/static-pages/fr/index.mdx
app/static-pages/it/index.mdx
app/templates/email/newsletter.ts

**This PR:**
- This PR resolves minor issues and missing things detected by @sosiology and @KerstinFaye during the Internal Review (test) process.
**Fixes**
- Adds Subject and body to Newsletter
- Fixed English New Feature Subject Line "undefined"
- Showing the Accordion open on Datasets
- Overlapping Toggleswitch 
@bprusinowski there where still some minor mistakes that where causing issue's, this PR resolves all Testing Internal feedback from @sosiology

fix: Added Newsletter Body & Subject

---

app/login/components/login-menu.tsx

**This PR:**
- resolves the problem of not being able to close nested popovers within the user profile for share and embed and the Feedback button.
- resolves #1891
1. This feature can only be tested on Prod
2. Login
3. Open the Dropdown See the new `Feedback >` button ✅
4. Click the `Feedback >` button see how there is Report Bug and Request new Feature button ✅
5. Click away, see how it closes ✅
---
CC: @sosiology , @KerstinFaye

fix: Fixed Feedback Closing mechanism

---

app/templates/email/bug-report.ts
app/templates/email/feature-request.ts
app/templates/email/newsletter.ts

This PR: 
- adds a divider line to the new email body sections

fix: Added requested divider-line

---

app/next.config.js

Minor update to `connect-src` policy for connections to https://*.admin.ch

fix: Updated policy

---

app/charts/map/map-state.tsx
app/components/form.tsx
app/config-types.ts
app/configurator/components/chart-controls/color-palette.tsx
app/configurator/components/chart-controls/color-picker.tsx
app/configurator/components/chart-controls/color-ramp.tsx
app/configurator/components/chart-controls/create-color-palette.tsx
app/configurator/components/chart-options-selector.tsx
app/configurator/components/color-picker.tsx
app/configurator/components/configurator.tsx
app/configurator/configurator-state/actions.tsx
app/configurator/configurator-state/reducer.tsx
app/db/palettes.ts
app/docs/controls.stories.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/login/components/color-palettes/color-palette-examples.tsx
app/login/components/color-palettes/color-palette-types.tsx
app/login/components/color-palettes/profile-color-palette-content.tsx
app/login/components/color-palettes/profile-color-palette-form.tsx
app/login/components/profile-content-tabs.tsx
app/login/components/profile-tables.tsx
app/pages/api/user/color-palette.ts
app/palettes.ts
app/prisma/schema.prisma
app/server/user-controller.ts
app/utils/chart-config/api.ts
app/utils/check-contrast.ts

fix: fixed all of bartosz's recommendations

---

app/configurator/components/chart-controls/color-palette.tsx

Complete forgot to change it 🙄 - my bad

fix: fogrot to change let to const

---

CHANGELOG.md
app/configurator/components/chart-controls/drawer-color-palette-content.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/login/components/color-palettes/profile-color-palette-form.tsx

This PR adds dynamic color palettes type description.
1. Go to this link
2. Login 
3. Create a custom color palette
4. Change to all types 
5. See how description changes dynamically ✅
1. Go to this [link](https://test.visualize.admin.ch)
2. Login 
3. Create a custom color palette
4. Change to all types 
5. See how description don't change dynamically ❌
---
---
cc: @KerstinFaye

fix: added dynamic translations for color palette types

---

app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/login/components/color-palettes/profile-color-palette-form.tsx

found the issue about the type translations 😵‍💫
cc: @KerstinFaye

fix: Fixed Color type translations 😅

---

app/browser/dataset-preview.tsx

Added External Link Icon to the ODS button in the iframe

feat: Added LinkExternal Icon

---

CHANGELOG.md
package.json
yarn.lock

Closes #2213
This PR updates Next.js from 14.2.23 to 14.2.26.
---

chore: Update Next.js

---

CHANGELOG.md
app/browse/datatable.tsx
app/browser/dataset-preview.tsx
app/browser/select-dataset-step.tsx
app/components/arrow-menu.tsx
app/components/data-download.tsx
app/components/dataset-metadata.tsx
app/components/header.tsx
app/components/metadata-panel.tsx
app/components/tag.tsx
app/configurator/components/add-dataset-dialog.tsx
app/configurator/components/add-new-dataset-panel.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po
app/login/components/login-menu.tsx
app/themes/components.tsx
e2e/abbreviations.spec.ts
e2e/edition.spec.ts
e2e/ordinal-measures.spec.ts
e2e/sorting.spec.ts
e2e/symbol-layer-colors.spec.ts

This PR continues the CI / CD migration by:
- completing the migration of the dataset preview page,
- fixing button text overflow issues.
---

feat: CI / CD pt. 4

---

app/configurator/components/chart-options-selector.tsx
app/locales/de/messages.po
app/locales/en/messages.po
app/locales/fr/messages.po
app/locales/it/messages.po

Closes #2226
This PR adjusts UI copy and updates translation string id.

feat: Update UI copy

---

app/components/chart-published.tsx
app/components/form.tsx
app/components/markdown.module.css
app/components/markdown.tsx
app/configurator/components/annotation-options.tsx
app/configurator/components/block-options-selector.tsx
app/configurator/interactive-filters/time-slider.tsx

Closes #2264
Closes #2283
Closes #2286
This PR introduces a few styling improvements.
---

feat: Smaller styling improvements

---

.github/workflows/base-checks.yml
.github/workflows/chromatic.yml
.github/workflows/e2e.yml
.github/workflows/preload-varnish-cache.yml
.gitlab-ci.yml
CHANGELOG.md
Dockerfile
app/package.json
app/public/json-schema/chart-config.json
app/public/json-schema/configurator-state.json
docker-compose.mitm.yml
docker-compose.yml
shell.nix
yarn.lock

maintenance: Update Node.js to v22

---

CHANGELOG.md
app/components/chart-shared.spec.tsx
app/components/chart-shared.tsx

Closes #2408
This PR makes sure we do not render more options button when no actions are available.
1. Go to [this link](https://visualization-tool-git-fix-empty-more-options-menu-ixt1.vercel.app/en/preview#version=4.6.0||state=CONFIGURING_CHART||dataSource__SEP__type=sparql||dataSource__SEP__url=https://lindas-cached.cluster.ldbar.ch/query||layout__SEP__type=tab||layout__SEP__meta__SEP__title__SEP__de=||layout__SEP__meta__SEP__title__SEP__en=||layout__SEP__meta__SEP__title__SEP__fr=||layout__SEP__meta__SEP__title__SEP__it=||layout__SEP__meta__SEP__description__SEP__de=||layout__SEP__meta__SEP__description__SEP__en=||layout__SEP__meta__SEP__description__SEP__fr=||layout__SEP__meta__SEP__description__SEP__it=||layout__SEP__meta__SEP__label__SEP__de=||layout__SEP__meta__SEP__label__SEP__en=| …

fix: Do not render ChartMoreButton when no actions are available

---

CHANGELOG.md
app/browse/ui/select-dataset-banner.tsx
app/components/chart-shared.tsx
app/components/dataset-metadata.tsx
app/components/metadata-panel.tsx
app/domain/data.ts
app/rdf/query-cube-metadata.ts

Closes #2458
This PR adds support for multiple cube contact points to Visualize.
1. Go to [this link](https://visualization-tool-git-feat-multiple-contact-points-ixt1.vercel.app/en/browse?dataset=https://communication.ld.admin.ch/ofcom/tv_srg_program_information_structure/1).
2. See that the application doesn't crash and that there are two contact points listed in the left section.
1. Go to [this link](https://visualize.admin.ch/en/browse?dataset=https://communication.ld.admin.ch/ofcom/tv_srg_program_information_structure/1).
2. See that the application crashes.
---

feat: Multiple contact points
