app/next.config.js, app/package.json, package.json, yarn.lock
The application still works, even in Edge 17. This fixes an inexplicable bug where the dev server wouldn't start anymore and be stuck compiling the next.js error page.
=> Disable compilation of node_modules

app/components/chart-options-selector.tsx, app/components/charts-generic/areas/areas-state.tsx, app/components/charts-generic/columns/columns-stacked-state.tsx, app/components/field.tsx, app/domain/config-form.tsx, app/domain/configurator-state.tsx
- Remove sorting options for non-nominal dimensions. Temporal and Ordinal dimensions already have a defined order
- Order stacks visually from top to bottom when stack order is ascending
=> Sorting improvements

app/components/charts-generic/areas/areas-state.tsx, app/components/charts-generic/axis/axis-height-linear.tsx, app/components/charts-generic/axis/axis-width-linear.tsx, app/components/charts-generic/axis/axis-width-time.tsx, app/components/charts-generic/columns/columns-grouped-state.tsx, app/components/charts-generic/columns/columns-stacked-state.tsx, app/components/charts-generic/columns/columns-state.tsx, app/components/charts-generic/lines/hover-line-values.tsx, app/components/charts-generic/lines/lines-state.tsx, app/components/charts-generic/pie/pie-state.tsx, app/components/charts-generic/scatterplot/scatterplot-state.tsx, app/components/dataset-metadata.tsx, app/components/datatable.tsx, app/domain/helpers.tsx, app/locales/locales.ts
Replaces all uses of date/number formatting functions with localized ones. I created React hooks for both because the locale can then easily be read from context.
NB:
- Numbers are currently all formatted with the de-CH locale.
- Currencies are not handled since there's no formal definition of how they would be expressed in the Data Cube
- Date/time formatting is approximated to the shortest useful form using a multi-scale time format as described in [d3-time-format](https://github.com/d3/d3-time-format/blob/master/README.md), but since we lack working real-world datasets with anything other than day and year interval, it's not very thoroughly tested.
- Date/time is formatted differently on time axes (where they are abbreviated) and everywhere else. This is probably not bullet-proof in …
=> Localize date and number formatting

app/charts/chart-config-ui-options.ts, app/charts/index.ts, app/components/data-download.tsx, app/configurator/components/chart-controls/color-palette.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx, app/configurator/config-types.ts, app/configurator/configurator-state.tsx
Made the following changes to the TableConfig type:
- Removed `columns` array in favor of re-using `fields` map (keys will be numbers or something similar)
- Added a union type for all possible `columnStyle` variants. Easier to typecheck, because we don't use partials anymore. This means that these options are now nested within `columnStyle`, e.g. `{ ..., columnStyle: { type: "text", textColor: "#333", columnColor: "#fff" } }`
"Fixed" type errors in a few places. Mostly because `segment` is expected to be a color field and table is the only chart type that doesn't use this field. Probably need to improve this later.
=> Fix table chart config types

app/charts/index.ts, app/components/chart-preview.tsx, app/configurator/components/chart-configurator-table.tsx, app/configurator/components/chart-controls/drag-and-drop-tab.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/ui-helpers.tsx, app/configurator/config-form.tsx, app/configurator/config-types.ts, app/configurator/configurator-state.tsx, app/docs/fixtures.ts
- Table fields are now keyed by IRI
- Added `position` and `componentType` to table fields
- Added `getOrderedTableColumns()` helper
_Not yet solved_: when the `isGroup` or `isHidden` field properties are changed, the `position` is not updated. This can lead to some inconsitency in the orderint of the columns in the sidebar but shouldn't affect the table itself too much anymore since fields are now accessed by IRI instead of their array index.
=> Table Config Changes

app/charts/index.ts, app/configurator/components/chart-options-selector.tsx, app/configurator/components/panel-left.tsx, app/configurator/components/ui-helpers.tsx, app/configurator/config-types.ts, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-configurator.tsx, app/configurator/table/table-chart-options.tsx, app/configurator/table/table-config-state.ts, app/docs/fixtures.ts
Fixes not updating `position` when toggling `isGroup` on columns.
Renamed column `position` to `index`.
=> Fix Column Order For Groups

app/rdf/parse.ts, app/rdf/queries.ts
After a visualization is created, it should not be locked to the data cube version current at the time of creation but automatically try to pick and display the latest version of the cube (preferring published over draft cubes).
=> Use latest available cube version automatically

app/components/form.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/field.tsx, app/configurator/components/ui-helpers.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.tsx, app/configurator/constants.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers.ts, app/graphql/schema.graphql, app/graphql/shared-types.ts, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/rdf/parse.ts, app/rdf/queries.ts
Adds support for `cube:KeyDimensions`:
- Only Key Dimensions will be automatically set as filters. This should prevent cases where filters on redundant dimensions result in queries that return no data. NB: this only works if the cube is modeled correctly!
- Optional filter menus (only non-key dimensions can be optional) now include a "No Filter" option to deselect filters
Note that this does not yet address #73 or #79
=> Support for Key Dimensions

app/charts/shared/chart-data-filters.tsx, app/components/chart-filters-list.tsx, app/components/form.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/field.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.tsx, app/configurator/interactive-filters/editor-time-interval-brush.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts
Handle temporal dimensions correctly in data filters. The original problem was that the dimension is only annotated with the date range but not a list of dates. To select a filter on a temporal dimension, we have to interpolate in the right time unit.
This is implemented by showing a dropdown menu for 100 entries and less and an input field when there are more possible values. The input is matched on the ISO8601 format of the dimension's datatype (e.g. "2007" for years, "2007-01-01" for dates etc.).
It's not an optimal solution because users have to know or guess the right date … but it works for now. We will have to design and implement a better solution in the future, ideally one _that only allows to select dates which have observations_.
See #79
=> Date Data Filter

app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx
https://github.com/visualize-admin/visualization-tool/pull/150#issuecomment-956097226
> @ptbrowne Currently, the Cube Creator links to /create/new?cube=<versionHistoryIri> (as described in #87). So the param and the logic don't quite match yet 😅
Instead of using the "dataset" parameter in the URL, use the "cube" to match what the cube creator is using.
=> fix: Use "cube" parameter instead of "dataset" when creating chart from existing dataset

app/charts/area/areas.tsx, app/charts/line/lines.tsx
Closes #171.
This PR makes the line and area charts consider user-selected colors when the selection is one-element long.
@herrstucki I'm not sure why the current behavior wasn't allowing that, as this was explicitly coded in the app – let me know if you think it shouldn't be changed :)
=> Consider user-selected color in line and area charts for one-element selections

app/configurator/config-types.ts
Fixes #168
The parser for single filter now accepts strings and integers since some datasets have integers in their columns.
=> fix: Ability to use integer as filters

app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-grouped.tsx, app/charts/column/columns-simple.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-stacked.tsx, app/charts/column/columns-state.tsx, app/charts/column/rendering-utils.tsx, app/charts/shared/padding.tsx
Closes #166, #190.
This PR:
- fixes cropped Y axis ticks for column charts,
- introduces a "start with 0" constraint for Y axes with negative scales, which fixes bars that were overlapping axis titles,
- fixes min and max Y scale ranges for stacked column charts (previously, it was taking min and max of total, which was a sum of all positive and negative values in a given "column stack" – now it takes max(positive values in a stack) and min(negative values in a stack)),
- extracts a Column function (which was the same in 3 files) to a separate file.
=> Fix Column Chart display bugs

app/homepage/examples.tsx
Closes #82.
Side question: can I be sure that these examples will work when we publish to PROD? These datasets don't appear on that env and I'm not sure if we can fetch them from there.
=> Replace examples on the home page

app/charts/index.ts, app/charts/table/table-state.tsx, app/configurator/components/chart-controls/drag-and-drop-tab.tsx, app/configurator/components/filters.tsx, app/configurator/config-types.ts, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-options.tsx, app/configurator/table/table-config-state.ts, app/docs/fixtures.ts
Closes #188.
This PR:
- keeps the hidden state when using a hidden column as a group (as suggested in the issue raised by @AnninaWalker),
- allows to hide/unhide key dimensions used as group-by columns,
- shows a "Use as group" checkbox for non-key dimensions that are not of a "Measure" type (previously anyway we could use them as grouping variables by drag&drop), but this might be more convenient and consistent with how it's dealt with in case of key dimensions.
@herrstucki previously it was coded to clear the "isHidden" prop, so let me know if you think it should be the way the PR proposes – but it feels more natural to keep the state IMO, as anyway I had to hide a column first and then use it as a group (the other way I see it could be to always clear the "isFiltered" prop when using a …
=> Fix hidden grouped-by columns in the Table chart

.gitlab-ci.yml, Dockerfile, app/.env.development, app/components/DebugPanel.tsx, app/components/footer.tsx, app/db/pg-pool.ts, app/domain/env.ts, app/next.config.js, app/pages/_document.tsx, package.json
Adds the Git hash and repo via `NEXT_PUBLIC_` build-time env vars, so they can be displayed along with the version number.
Fixes #192
Fixes #167
=> Add Git Hash To Version

app/components/footer.tsx, app/domain/env.ts, app/pages/_document.tsx
Follow-up on #194. Rename env variables to make it more clear which are available in the client, server and which are set during build time.
=> Rename env variables for clarity

app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-options.tsx
I have not considered all possible situations in #191 – I assumed that we don't need to differentiate between tables and other charts when dealing with filters, but in fact we do.
This PR fixes an issue currently available on DEV, when using a given dimension as a segment,  which removes currently applied single filter, and this behavior is not desired in this case.
I have also added some comments, to not forget in the future what's going on here (along with another test) 😆
=> Fix non-table filtering issue

app/charts/area/areas-state.tsx, app/charts/area/chart-area.tsx, app/charts/bar/bars-grouped-state.tsx, app/charts/bar/bars-state.tsx, app/charts/chart-config-ui-options.ts, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/index.ts, app/charts/line/lines-state.tsx, app/charts/pie/pie-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/chart-helpers.tsx, app/charts/shared/imputation.spec.tsx, app/charts/shared/imputation.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/data-download.tsx, app/components/hint.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/panel-left.tsx, app/configurator/components/ui-helpers.ts, app/configurator/config-types.ts, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-options.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
This PR is based on the conversation in #148 and it:
- introduces a concept of imputation of missing data (currently only applicable to stacked area charts with different time ranges for individual series),
- allows imputations with zeros or linearly interpolated values (in this case, if a series has a missing value at the beginning or at the end, then it will still be filled using 0),
- adds a proper section (called "Missing values") in the chart configurator (right panel) when using an area chart,
- the above section is disabled when no missing values are detected and is activated otherwise (I found it distracting when the whole section was disappearing and re-appearing but let me know what do you think about this).
Still TODO if you think the approach is ok:
I will also add some …
=> Add missing data imputations for stacked area charts

app/configurator/components/chart-type-selector.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Removes the experimental section from the chart type selector.
The feature itself is still available at /experimental/map
=> Remove experimental map from chart type selector

app/charts/area/areas-state.tsx, app/charts/line/lines-state.tsx, app/charts/shared/chart-helpers.spec.tsx, app/charts/shared/chart-helpers.tsx
The time brush displayed below the charts needs sorted data in order to run correctly – this PR fixes that by sorting the wideData.
Closes #220.
=> Sort the wideData in order to make time brush run correctly

app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
The wording on the dataset page was inconsistent, not self-descriptive enough or just wrong (at least in German).
Changes:
- "back to list" (was "back to results" in some languages?) to "back to datasets" (more descriptive and consistent)
- "create visualization from dataset" to "create visualization" (was inconsistent between languages and wrong in German)
=> Improve translations on dataset selection step

app/configurator/components/dataset-metadata.tsx
Long tags could be cut by line break and this was not pretty.
Now tags in the dataset metadata are shown as a list (line break between each element).
https://visualize-ad-fix-datase-jx9gw1.herokuapp.com/en/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd10_energieforschungsstatistik_ch%2F2%2F?previous=%7B%7D
If the organization name is too long (does not happen right now for any organization), there is an ellipsis, and full title is shown on hover (via HTML title attribute)
=> fix: Tags have max width + ellipsis and are displayed as a list in dataset metadata

app/configurator/components/chart-controls/color-picker.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.tsx
This PR prepares the future work on hierarchical filters. It does not add any new functionality (yay!?).
Since in the future we want to be able to display hierarchical multi checkboxes, and we will possibly separate the color pickers from the data filters, this PR ensures that the UI components can be more freely re-arranged. 
- Checkboxes and color pickers are now separate components
- They know what to dispatch and do not rely on their parents to pass the correct properties
- Since we need to have a shared state (containing what is checked, the selection state and several other values), I used a context to share the information
- I used hooks that contain the budget logic to separate the presentation from the logic. This could be useful in the future when we want to have the color …
=> Hierarchical filters step 1

app/charts/shared/chart-data-filters.tsx, app/configurator/components/field.spec.tsx, app/configurator/components/field.tsx
Closes #209.
This PR allows to have an empty optional time filter (non-key dimension) and forces it to have some value for key dimensions.
=> fix: Allowing for empty key dimension time filter

app/configurator/components/dataset-browse.tsx, app/configurator/components/select-dataset-step.tsx, app/lib/use-nprogress.ts, app/pages/browse/index.tsx
Search, order and includeDrafts are passed from browsing page to dataset result and are passed into the back link : now the user goes back to the exact state she left.
fix #238
=> fix: Can navigate back after data selection and browsing state is kept

app/configurator/components/action-bar.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/components/configurator.tsx, app/configurator/components/layout.tsx, app/configurator/components/select-dataset-step.tsx, app/configurator/components/stepper.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Since the browsing mode is now separated from the chart creation, we chose to remove the step 1 "Selecting dataset" of the creation stepper.
fix #244
=> feat: Remove select dataset step from stepper

app/charts/shared/brush.tsx, app/homepage/examples.tsx
This PR:
- replaces an example of the homepage (which stopped working due to some changes in the cube),
- fixes a bug where a chart time brush wasn't being updated when using an interactive filter.
I kept the current brush's behavior – so when you change an interactive filter option, the new time domain tries to fit into the old domain. It can be easily changed to reset the domain after each change, but I'm not sure which feels more natural.
=> Homepage example change & time brush domain fix

app/configurator/components/configurator.tsx, app/configurator/components/dataset-metadata.tsx, app/configurator/components/select-dataset-step.tsx
- Back to results link is separated from dataset metadata, a bit bigger, and with arrow
- Choose another dataset link is styled properly (primary color with underline on hover)
=> Back link improvements

app/pages/_document.tsx, app/pages/api/client-env.ts
Because the process.env.* variables for some reason are only set in next.js dev mode inside of _document.tsx, the only way to expose them reliably is through an API route.
To ensure it's loaded before other scripts, it's imported as a synchronous script that sets `window.__clientEnv__` in the document `<head>`.
Fixes #254
=> fix: Expose client env via API endpoint

app/rdf/queries.ts, app/rdf/query-dimension-values.ts
Right now the logic brings back the previous functionality – tries to fetch all of the dimension values if no values are present initially. We still need to wait for autocomplete API from Zazuko and I'm not quite sure how this should look like in UI (and the code), so I didn't try to come up with new ideas, it probably would make sense to also consult this with Annina.
Let me know what do you think (and if this should be already merged to main – if not, I can merge this to maps PR to continue working on it if the code looks fine).
=> Try to fetch dimension values when no values are there initially

app/configurator/components/select-dataset-step.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/themes/federal.ts
Adding a descriptive text on the browsing datasets index page.
=> feat: Add browsing description

app/graphql/context.tsx, app/pages/_app.tsx, app/pages/_document.tsx
Basing on information from https://nextjs.org/docs/advanced-features/i18n-routing:
- locale is accessible through document context, there is no need to retrieve it in such complex way,
- lang is automatically appended to HTML, so there is no need to set it explicitly.
The way of setting the locale was **always** returning a default locale (de) initially, probably because Next.js introduced some changes since the project was created and then it was changed through _app.tsx.
Additionally, retrieving the lang property by using querySelector in urql client was resulting in an undefined locale for the initial request, which introduced some bugs in fetching of the shapes, which isn't the case anymore.
=> fix: Geo data loaders locale switching bug

app/configurator/components/dataset-browse.tsx
The score by default was "title", by mistake, which meant the results were
alphabetically ordered instead of being ordered by relevance.﻿
=> fix: Sort by relevance by default

app/charts/chart-config-ui-options.ts, app/charts/index.ts, app/charts/map/chart-map.tsx, app/charts/map/map-state.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/ui-helpers.ts, app/configurator/config-types.ts, app/configurator/map/map-chart-options.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
=> feat: Update map icons

app/charts/chart-config-ui-options.ts, app/configurator/components/chart-options-selector.tsx
We have to add geo dimensions to the encoding specs (that specify constraints
on which type of dimension can be mapped to which encoding) so that we
can map the bathing site dimension (that has been changed recently into
a geocoordinates dimension)﻿to a color.
- fix: Add GeoShape and GeoCoordinates dimensions to the UI encoding spec
=> Fix: ability to encode geo dimensions

app/.env.development, app/charts/area/areas-state.tsx, app/charts/bar/bars-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/shared/legend-color.tsx, app/charts/shared/use-chart-state.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/common-chart.tsx, app/components/form.tsx, app/configurator/components/filters.tsx, app/configurator/config-form.tsx, app/domain/data.ts, app/graphql/resolvers.ts, app/rdf/batch-load.ts, app/rdf/parse.ts, app/rdf/queries.ts, app/rdf/query-labels.ts, app/rdf/query-positions.ts, app/rdf/query-sameas.ts, app/rdf/query-unit-labels.ts, app/utils/dimension-hierarchy.ts, app/utils/sorting-values.ts
A less disruptive approach than #227
=> Include Position for Ordinal Dimensions

app/pages/browse/[type]/[iri].tsx, app/pages/browse/index.tsx, app/rdf/query-cube-metadata.ts
Fixes https://github.com/visualize-admin/visualization-tool/issues/288
When we land on /en/browse/dataset/<unversionedIri>, we fetch the latest published cube to get the latest unversioned iri and redirect server side to /en/browse/dataset/<versionedIri>.
To detect unversionedIri, a heuristic is used, it should end with `/<number>/`.
=> feat: Redirect to latest cube iri when going to on browse/dataset/<unversionedIri>

app/components/hint.tsx, app/configurator/components/dataset-metadata.tsx, app/configurator/components/dataset-preview.tsx, app/configurator/components/select-dataset-step.tsx
- Do not show loader in browsing metadata panel
- Show error message if dataset cannot be loaded
=> Handling of error and loading states

app/pages/browse/[type]/[iri].tsx
Iris for dataset can contain an optional ending slash.
Since the regex would match only URLs with ending slash, we would consider some URLs as unversioned when in fact they are versioned, and then we would try to find the versioned dataset and it would fail. Now we correctly consider http://<iri>/1 as versioned (and also http://<iri>/1/).
fix #313
=> fix: Ending slash is optional for iris (versioned or unversioned)

app/rdf/query-dimension-values.ts
Some datasets have been created with rdf:langString in some columns. This means that strings are tagged with their language. Since we do not keep the language information inside the filter, we have to filter only based on the string representation of the value.
=> fix: Show dimension values even when column datatype is rdf:langString

app/components/chart-preview.tsx, app/configurator/components/dataset-preview.tsx, app/configurator/components/select-dataset-step.tsx, app/locales/en/messages.po, app/pages/_app.tsx
- feat: Add page titles in browsing pages
- feat: Add browsing title in dataset preview page
- feat: Add page title when creating chart
fix #330
Examples
- All datasets - visualize.admin.ch (while browsing all datasets, no search has been entered)
- "penguins" - visualize.admin.ch (while browsing datasets, search has been entered)
- Territory and environment - visualize.admin.ch (user has chosen a specific filter)
- Palmer penguins - visualize.admin.ch (user is previewing a dataset)
- Palmer penguins - visualize.admin.ch (user is creating a chart and has not chosen a title yet)
- My chart about penguins - visualize.admin.ch (user has put a title to its chart)
=> Page titles

app/configurator/components/dataset-browse.tsx, app/configurator/components/select-dataset-step.tsx
When a search has been entered, the nav panel counts will reflect
the numbers of *results* per theme/organization instead of the *overall
count of cubes per theme/organization.
fix https://github.com/visualize-admin/visualization-tool/issues/310
=> feat: Display counts per theme / organisations depending on search

CHANGELOG.md, app/charts/index.ts, app/charts/map/chart-map.tsx, app/charts/map/map-legend.tsx, app/charts/map/map-state.tsx, app/charts/map/map.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/config-types.ts, app/configurator/map/map-chart-options.tsx, app/domain/data.ts, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, yarn.lock
- _Fixes_ discrete color scales with < 3 observations for maps
- Adds new MVTLayer which displays lakes and rivers
- Fixes shape fill color when value === 0
=> fix: Discrete color scales with < 3 values + display lakes and rivers

CHANGELOG.md, app/components/debug-panel.tsx, app/components/form.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-controls/section.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/components/field.tsx, app/configurator/components/select-dataset-step.tsx, app/configurator/components/stepper.tsx, app/configurator/configurator-state.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers.ts, app/graphql/schema.graphql, app/rdf/queries.ts, app/rdf/query-dimension-values.ts
Previously when changing a filter in a cascading facets. we would take the first value of each dimension value that was present and this could lead to dead-end, and was slow since each filter could be changed after the filter just before it has been changed. Now the approach is different: when a filter is changed/moved, we try to find an observation with the filter, and if we do not find an observation, we relax the filters 1 by 1 starting from the bottom until we have an observations. This ensures that data is shown after filter have been loaded, and it also tries to keep as much as possible what the user has chosen (= change the bottomost filters first).
fix #327
fix #328
=> Improve filter value selection

app/charts/column/chart-column.tsx, app/charts/column/columns-simple.tsx, app/charts/column/columns-state.tsx, app/charts/shared/chart-helpers.tsx, app/docs/columns.docs.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers.ts, app/graphql/schema.graphql, app/graphql/shared-types.ts, app/pages/docs.tsx, app/rdf/parse.ts, app/rdf/queries.ts
In this PR, standard errors support is added to visualize.
Other PRs will follow to refine the functionality (tooltip support, activate / deactivate, support in horizontal chart).
Related meta issue : https://github.com/visualize-admin/visualization-tool/issues/353
The dataset where the standard error dimension is available is "LFI Data Cube [Version 1]: Waldfläche / Produktionsregion"
=> Error bars 1

app/charts/shared/use-chart-state.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-options.tsx, app/domain/data.ts, app/lib/has.ts, app/utils/dimension-hierarchy.ts
With the change of loading possible filters, a mistake was made since
the "right" filters (= filters that are on an IRI that is mapped)
should not be considered in the query that tries to find possible values for left filters.
Tested on multiple datasets:
Also, a change was made so that GeoShapesDimension and GeoCoordinatesDimension can be filtered correctly in table view.
fix #355
=> fix: Color segmentation filtering

app/charts/chart-config-ui-options.ts, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-grouped.tsx, app/charts/column/columns-simple.tsx, app/charts/column/columns-state.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/field.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
- feat: Add checkbox to show standard error
- feat: Show checkbox for standard error only if dimension has a related standard error dimension
Preview feature here : https://visualize-ad-standard-e-fffypz.herokuapp.com/en/create/new?from=Eer9zWiGlEbx
=> Checkbox for standard error

app/rdf/queries.ts
Fixes #348.
`a.out(ns.schema.version)?.value` had a string type, so cube 9 would be considered as more recent than cube 10. This PR fixes the issue in one of the homepage examples.
=> Fix newer cubes sorting by version in RDF query

app/charts/area/chart-area.tsx, app/charts/bar/chart-bar.tsx, app/charts/column/chart-column.tsx, app/charts/line/chart-lines.tsx, app/charts/map/chart-map.tsx, app/charts/pie/chart-pie.tsx, app/charts/scatterplot/chart-scatterplot.tsx, app/charts/table/chart-table.tsx, app/components/data-download.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/datatable.tsx, app/domain/data.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers.ts, app/graphql/schema.graphql, app/rdf/queries.ts, app/utils/dimension-hierarchy.ts
Previously, we would load all columns to get the distinct values of a dimension (to show in the right filters). Now we only load a subset of the columns (in most cases only the dimension displayed, but for hierarchical dimensions, we would need to load all the dimensions pertaining to the dimension.
- Since measures was not used inside the getCubeObservations I removed it
- Added dimensions as a parameters for datacubeByIri > observations so that we can fetch observations with only a subset of dimensions
#fix https://github.com/visualize-admin/visualization-tool/issues/374
=> feat: Only load relevant values in right filter

app/configurator/components/chart-configurator.tsx
This removes a patological case where filters are completely removed. In most cases we do not want filters to be completely removed automatically, it's better if "no data" is shown.
In the case where filters can be changed to show data they will be changed (starting from the bottom).
fix #385
=> Do not set automatically empty filters

app/configurator/components/chart-configurator.tsx, app/domain/data.ts
Fix https://github.com/visualize-admin/visualization-tool/issues/383
Filters out standard error dimension from possible left filters.﻿
=> feat: Do not show standard error in possible filters

app/configurator/components/chart-configurator.tsx, app/graphql/resolvers.spec.ts, app/graphql/resolvers.ts
Possible filters query would make a too big slice of the filters resulting
in possible filters trying twice with 2 filters if filters initial length
is 2. This would result in empty results and the filters not being changed
in the UI.
fix #400
=> fix: Not changing filters when initial filters length = 2

app/configurator/components/ui-helpers.ts, app/configurator/map/map-chart-options.tsx, app/icons/components/IcColor.tsx, app/icons/components/index.tsx
Closes #405.
I think it makes sense to change the icon there, as segments in all cases are represented by colors and we already have a "Color" label instead of "Segment".
=> feat: Change icons for segments

app/components/autocomplete.tsx, app/docs/form.docs.tsx
The search autocomplete needed to be wrapped into a context provided. Additionally I had to set a high z-index for it to be over other components (unfortunately, theme-ui does not surface CSS variables for z-index).
=> docs: Docs for form works

CHANGELOG.md, app/charts/map/map-state.tsx, app/charts/map/map-tooltip.tsx, app/components/debug-panel.tsx, app/configurator/components/ui-helpers.ts, app/domain/data.ts
As for column chart, the map tooltip now show the standard error along
with its unit if the measure dimension has an associated SE dimension.
- Tested with COVID dataset for "-" edgecase
- Tested with Waldfläche dataset for SE in tooltip
=> Standard error in map tooltip

app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/shared/interaction/tooltip-box.tsx, app/charts/shared/interaction/tooltip.tsx
- Only allow top placement, this way we do not hide chart data (future work could include having the same behavior that the tooltip stays at the same place vertically). Checked with Annina
- Improve x placement by considering right edge of columns
- Tooltip is now absolutely positionned and portalled so that it can escape the chart container, this removes problems with tooltip being cut
Fix #315
=> feat: Improve tooltip placement

app/configurator/components/chart-type-selector.tsx
Disables a way of selecting a disabled chart type using tab.
=> fix: Selecting disabled chart types with tab

app/pages/_app.tsx, app/themes/index.ts
Previously, we had a dark theme and a federal theme and the dark theme could
be asynchronously loaded via a query param. Since we removed the dark theme,
we are only left with one theme so async loading does not make sense.
Also, with async loading, hot reload was not working with the theme, we had
to reload the page after changes to the theme.﻿
=> feat: Remove async loading of theme so that hot reload works

CHANGELOG.md, app/configurator/components/ui-helpers.ts, app/rdf/parse.ts
Closes #461.
Also, changes the formatting of Month timeUnit to a shortened month name + year.
=> Account for xsd:gYearMonth timeFormat when parsing a TemporalDimension

app/pages/_app.tsx
Move CssBaseline in the hope that the CssBaseline overrides rules will work in production.
=> fix: Make CssBaseline work

CODEOWNERS, app/components/hint.tsx, app/configurator/components/dataset-browse.tsx, app/configurator/components/select-dataset-step.tsx, yarn.lock
Previously, even if the query for loading datasets was in error, the spinner
was shown. Now, a proper error is shown.﻿
=> fix: Do not show loading when dataset browse query is in error

app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/chart-data-filters.tsx, app/configurator/interactive-filters/interactive-filters-configurator.tsx
- fix: Prevent scatterplot chart from crashing when data segment value does not have an IRI
- fix: Prevent margins due to empty interactive filters component
- refactor: Typo in type
=> Fix scatterplot crash

app/charts/index.ts, app/configurator/config-types.ts, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/test/__fixtures/dev/chartConfig-table-covid19.json
This PR introduces segment retaining when switching from and to a table chart.
**Non table chart with segment -> Table chart:** _Segment is used to choose a grouping column_
**Table chart with at least one grouping column -> Non table chart that supports segment:** _First grouping column is used as a segment (if possible, in tables it's possible to use TemporalDimensions or Measures as grouping columns, which is not permitted in segments)_
=> feat: Include tables in chart config retaining logic

app/themes/federal.tsx
- fix: Re-enable svg block rule that was deactivated due to extra "
- fix: Set focus outline to none for elements with tabindex=-1
=> Remove outline for elements non navigable by keyboard

.github/workflows/lint-test.yml
I saw a warning during build from next telling we should cache things.
Apparently we did not cache node_modules.
Using a cache should speed things up.
* I upgrade setup-node action and tells to cache things related to yarn.
* I also cache .next/cache and the cache key depends on yarn.lock and source files
=> feat: Cache node_modules and .next/cache folder

app/components/data-download.tsx
If a dimension has a unit, it is included in parenthesis in the Excel export
Fix https://github.com/visualize-admin/visualization-tool/issues/544
﻿
=> feat: Column names contain unit if its there

app/charts/shared/brush.tsx
Closes #183.
It turned out that the brush's handle was disappearing not only on mobile, but also on desktop – when the user clicked the brush outside the current selection.
It was due to the fact that the event's selection was empty in such cases, and d3's brush internally sets visibility and position of handles to none then. To overcome this, there is a need to check for empty selections and if they appear, move the brush "in-place", so it doesn't disappear and snaps to actual dates.
Also, as consulted with @AnninaWalker, there is a new default behavior when clicking outside the current selection – the current selection is then moved to the center of user's click.
=> fix: Clicking on a time brush

app/charts/table/cell-desktop.tsx, app/charts/table/table-state.tsx, app/configurator/components/datatable.tsx, app/configurator/components/ui-helpers.spec.ts, app/configurator/components/ui-helpers.ts
Fixes https://github.com/visualize-admin/visualization-tool/issues/556
To allow for proper formatting of values inside cells, we instantiate
dimension values formatters at a high level (parent table) instead
of relying on useFormatDateAuto. The metadata of the column (dimension.timeUnit
to know which format to apply, dimension.timeFormat to parse) is used
to create the proper formatter.
=> Cell value formatters

app/charts/shared/interaction/tooltip-box.tsx, app/charts/shared/interaction/tooltip.tsx, app/charts/shared/overlay-horizontal.tsx
Although it probably wasn't noticeable by the end user (but surely by developers as lots of console errors), we had an infinite loop running when hovering over a chart (even when the mouse stopped moving). It was due to useState + useEffect without an empty dependency array. In addition, this PR improves performance of finding closest value for horizontal tooltip by only looking for these when X values changes (and not on every mouse move as previously).
=> fix: Infinite loop when hovering over chart

app/charts/table/cell-desktop.tsx, app/charts/table/cell-mobile.tsx, app/charts/table/table-state.tsx
I am not sure if this is a proper fix, it seems like it works, but I would really appreciate if @ptbrowne you could test and adjust if necessary (I've seen that before your changes in some places there were "formatNumber(cell)" instead of cell.render("Cell") as currently, and I'm not sure if it's ok?
Also, I discovered and fixed a bug in widths of the bars in the table bar cells – we missed "px" at the end and Visualize was sometimes treating the values as "px", but sometimes as "%" and this leads to strange results – you can see them if you revert the change and select bar cells styles in any dataset (e.g. Bathing water quality :)).
=> fix: Formatter can be optional

app/configurator/interactive-filters/editor-time-interval-brush.tsx
Closes #187.
I have noticed that the editor brush (the one that appears when selecting temporal dimensions either in X axis or a filter inside a table) has some sizing issues, see below:
the text is almost overflowing on the right side and is not properly centered. Additionally, it faces the same issue as Interactive Slider I fixed yesterday – when min and max dates are the same, brush handles disappear.
This PR fixes both issues:
=> fix: Editor brush issues

app/configurator/components/chart-configurator.tsx, app/rdf/queries.ts
Fix https://github.com/visualize-admin/visualization-tool/issues/564
Previously, only the min / max values were shown inside a temporal filter with timeUnit='Month'. Now we use a select for this case.
You can test by starting from [this dataset](https://visualization-tool-git-filter-month-select-ixt1.vercel.app/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FUBD010705%2F3?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22Luftbelastung%22%7D) and selecting a x-axis different from the date, so that the date is available in the filters.
=> Show all monthly values inside filter

app/components/chart-footnotes.tsx, app/components/form.tsx, app/configurator/components/dataset-metadata.tsx, app/configurator/components/filters.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers.ts, app/graphql/schema.graphql, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/utils/opendata.ts
Inside footnotes, the dataset title is now a link to opendata.swiss.
There, the user can have more information on the dataset.
Since the link is external, it opens in a new tab.
fix #135
=> feat: Add link to opendata.swiss

app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers.ts, app/graphql/schema.graphql, app/graphql/shared-types.ts, app/rdf/parse.ts, app/utils/opendata.ts
We have to look at the workExamples predicates to know if a cube has been
published on open data swiss.
Documentation on cube creator: https://github.com/zazuko/cube-creator/wiki/LINDAS-Specifics#needed-attributes-that-a-cube-shows-up-on-opendataswiss
fix #135
﻿
=> fix: Show opendata.swiss link only if it is published there

app/pages/browse/[type]/[iri].tsx, app/rdf/query-cube-metadata.ts, app/typings/rdf.d.ts
When looking at the dataset preview /browse/dataset/[iri], we try to redirect (server side) to the latest published IRI (in case the person comes from an external link where the cube version is not there). Some cubes do not have a version. Here, to make sure it is a valid cube, we make an extra request to check if the IRI has a shape. If the iri returned by the function looking for the last versioned iri is the same as the query passed in parameter, we do not do any redirect.
Previously, it was working when going first to a theme since the route for theme/iri and dataset/iri is "the same", and no server side redirect was triggered when going from /browse/theme/[iri] to /browse/dataset/[iri] (whereas the server side redirect was triggered by going from /browse to /browse/dataset/[iri]).
cc …
=> Support unversioned cubes

app/configurator/components/filters.tsx, app/rdf/query-hierarchies.ts, app/utils/dimension-hierarchy.ts
Since a hierarchy can encompass values that are much wider than what's in the data, we need to prune the tree to remove leafs whose value do not appear in the data. To do this, we query for distinct values inside the dimension and filter the hierarchical tree accordingly.
=> Hierarchical filters only shows values appearing in data

app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/pages/_app.tsx, app/pages/_cube-checker.tsx, app/pages/_cube-health.tsx, app/pages/browse/[type]/[iri].tsx, app/rdf/query-hierarchies.ts, app/rdf/sparql-client.ts, app/utils/flashes.tsx
- feat: Add a way to check the cube health
- feat: When redirecting to home page due to bad cube, show an error message
- feat: Add translations
When cannot load a cube, we have a message on home page:
We can see the cube in a new cube checker page that checks some of the attributes of the cube to see if they are correct.
=> Cube checker

app/rdf/query-cube-metadata.ts
When coming from the cube creator directly, we want to be able to see a versioned/unversioned iri even if they are in draft status.
=> fix: When looking for versioned/unversioned cube through IRI, remove draft filter

app/browser/dataset-browser.tsx, app/charts/shared/legend-color.tsx, app/components/chart-published.tsx, app/configurator/configurator-state.tsx, app/docs/chart-selection-tabs.docs.tsx, app/docs/dataset-browse.docs.tsx, app/pages/create/[chartId].tsx, app/pages/v/[chartId].tsx, app/src/index.ts, app/test/__fixtures/int/configs.ts, cypress/integration/edition.spec.ts
This way, the legend can use the chart config
Elements that do not need to change the chart config can use the
readonly version of the useReadOnlyConfiguratorState function
=> fix: Wrap published chart in Config provider

app/charts/map/map-state.tsx, app/configurator/components/filters.tsx, app/configurator/map/map-chart-options.tsx
As hierarchy is now handled at dimension level and not anymore as part of the geoshapes, we do not need the hierarchy options for the maps.
Fixes were made on the multi filters display so that they handle cases without color mapping
=> feat: Do not hierarchy level section for maps as this is handled in filters

app/configurator/components/chart-configurator.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.tsx, app/scripts/cube.ts
When selecting a dimension for segmentation, due to missing sourceUrl and sourceType in the client.query call, we would not retrieve the hierarchy and select 7 values without care for the hierarchy. Now we select 7 leaves.
I've added also proper types to client.query calls so now we are warned.
=> Better initial state for segment

app/configurator/configurator-state.tsx
Fixes #622.
For old charts there is no dataSource prop defined. This PR makes sure that a chart uses a default data source for a given Visualize env if it's not defined in its config.
=> fix: Copying of chart with empty data source

app/configurator/components/ui-helpers.ts
Here we articifically clamp the left side of the sequential color palette as it is
too white and is not visible on maps.
I think I saw somewhere (maybe on GitLab) an issue that was talking about this,
and I experienced the problem myself.
I'd like to have your views on these. cc @rdataflow @anninawalker @bprusinowski﻿
=> feat: Artificially clamp range of sequential palettes for colors to be less white

app/components/chart-panel.tsx, app/components/chart-selection-tabs.tsx, app/components/form.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-controls/control-tab.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/table/table-chart-configurator.tsx, app/themes/federal.tsx
Previously, we had extracted the chart type choice inside the tabs. Here we revert this choice and put it back in the left panel.
=> Make chart choice more visible

.gitlab-ci.yml, scripts/docker-build-push.sh
When building the release docker image, the necessary environment variables (namely `MAPTILER_STYLE_KEY` and `VECTOR_STYLE_URL`) were not passed.
Now the build and release commands use the same command, so we will not be able to
have discrepancies between build and release.﻿
=> Fix maps in production

app/configurator/components/filters.tsx, app/configurator/interactive-filters/editor-time-interval-brush.tsx
Closes #571.
I think it makes more sense to use the same date format as visible above the time slider, see picture below. I don't think we should use formatDateAuto when we have an easy access to a timeUnit of given TemporalDimension.
=> fix: Use a proper time unit to format brush extent dates

CHANGELOG.md, app/configurator/components/chart-controls/drag-and-drop-tab.tsx, app/configurator/table/table-chart-configurator.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Add empty component for when there are no groups in table chart options. Still draft, need input from @AnninaWalker.
=> DnD empty groups

app/components/debug-search.tsx, app/rdf/query-search.ts
Add wildcards to the Lucene query used in the search to support
partial terms.
﻿
=> Support partial search terms

app/components/form.tsx, app/configurator/components/chart-annotations-selector.tsx, app/configurator/components/chart-annotator.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-controls/section.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/field.tsx, app/configurator/interactive-filters/interactive-filters-config-options.tsx, app/configurator/interactive-filters/interactive-filters-configurator.tsx, app/configurator/map/map-chart-options.tsx, app/configurator/table/table-chart-configurator.tsx, app/configurator/table/table-chart-options.tsx, app/configurator/table/table-chart-sorting-options.tsx
This PR fixes padding between base layer options in maps + adds padding to other options sections in the right panel, as they went missing after recent changes. Also, it fixes sizing issues with table chart sorting options.
=> fix: Design issues

app/components/debug-search.tsx, app/configurator/components/ui-helpers.spec.ts, app/configurator/components/ui-helpers.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers/index.ts, app/graphql/resolvers/sql.ts, app/graphql/schema.graphql, app/graphql/shared-types.ts, app/rdf/parse.ts, app/rdf/queries.ts, app/rdf/query-unit-labels.ts
When we detect a currency in the data (from the unit in qudt.unit), we format the data with currencyExponent digits.
In this issue, the usecase of data where the floating precision is more than currencyExponent (for example for currency exchange datasets) is not tackled. It would be possible to tackle this when the dimension metadata informs us on the precision necessary.
Fixes https://github.com/orgs/visualize-admin/projects/1/views/18
This can be tested with the "State accounts - Office" dataset where amounts should have a precision of 2 digits after comma since the currency is CHF, and the currency exponent of CHF is 2.
=> Format currencies improvements

app/components/chart-published.tsx
When PublishedChart is not using a trusted DataSource.
=> fix: Use correct color for warning

app/charts/area/chart-area.tsx, app/charts/bar/chart-bar.tsx, app/charts/column/chart-column.tsx, app/charts/index.ts, app/charts/line/chart-lines.tsx, app/charts/map/style-helpers.ts, app/charts/scatterplot/chart-scatterplot.tsx, app/charts/table/chart-table.tsx, app/components/debug-search.tsx, app/configurator/components/field.tsx, app/tsconfig.json
Part II of removing unused stuff.
=> chore: Remove unused II

app/components/chart-footnotes.tsx, app/configurator/components/dataset-metadata.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Move landing page link to the blue links.﻿
=> Move landing page link

app/components/debug-search.tsx, app/graphql/context.tsx, app/graphql/devtools.dev.ts, app/graphql/devtools.prod.ts, app/graphql/query-meta.ts, app/graphql/resolvers/rdf.ts, app/pages/api/graphql.ts, app/rdf/query-search.ts
To provide the debug search page with the actual graphql queries that were sent to the sparql server, I use the extensions part of the graphql response.
I use the context to store the particular query times (at each query I push the meta information in context.queries)
Then I use the formatResponse callback from apollo-server to add to the extensions part of the response the queries that were stored in the context while the response is processed.
=> feat: Provide query timings in debug search page

app/configurator/components/select-dataset-step.tsx, app/configurator/components/use-redirect-to-versioned-cube.spec.tsx, app/configurator/components/use-redirect-to-versioned-cube.tsx, app/domain/datasource/index.spec.ts, app/stores/data-source.ts, app/utils/flashes.tsx, app/utils/router/helpers.ts
After the implementation of the datasource functionality, we moved the redirect to the front-end as we needed to access the localStorage. It seems that when we did that we missed one of the redirect.
I also experimented an issue with the router.replace function (an error while access /browser/dataset/iri, see the description of the commit), so I simplified the saving of the dataSource param in the URL, and used directly history.pushState.
Fixes https://github.com/visualize-admin/visualization-tool/issues/288
Going to the following URLs should correctly redirect to the versioned IRI and the cube preview should be displayed.
- `/en/browse/dataset/https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Function?dataSource=Int`
- `/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen …
=> Fix link unversioned dataset

cypress/integration/edition.spec.ts, cypress/integration/unversioned.spec.ts
Add a simple test to ensure that we do not have the unversioned link bug again in the future
=> feat: Add E2E test for unversioned link to dataset

app/configurator/components/filters.tsx, app/configurator/configurator-state.tsx
Fixes #675.
In some cases, the dimension used to create ColorMapping is filtered; in such situations users can't set color values for new values which appeared on chart during filtering. This PR fixes that by firing `handleRecomputeColorMapping` on first load of color mapping to assure it will use all dimension's values.
=> fix: Initialize ColorMapping with all values

CHANGELOG.md, app/browser/dataset-browser.tsx, app/components/debug-search.tsx, app/components/form.tsx, app/configurator/components/dataset-browse.tsx, app/rdf/query-search.ts, cypress/integration/search.spec.ts
- feat: Split query in two for search, 1st search in name + description, then search in creator, publisher, theme
- feat: Ability to use a custom search in debug search page
- fix: When sharing a search URL, search input was not retrieved
improves for #683 
fix https://github.com/visualize-admin/visualization-tool/issues/699
=> Feat: Improve search time + custom search in debug page + search input enhancement

app/charts/shared/legend-color.tsx, app/test/__fixtures/config/int/map-waldflasche.json, cypress/fixtures/map-waldflasche-chart-config.json, cypress/integration/symbol-layer-colors.spec.ts
As mentioned in #692, this PR adds a basic E2E test for SymbolLayer colors (checks if it's possible to select a nominal dimension and if a color legend shows up afterwards).
=> feat: Add basic SymbolLayer color selection E2E test

app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/map/map-state.tsx, app/charts/map/map-tooltip.tsx, app/charts/pie/pie-state.tsx, app/charts/shared/use-chart-formatters.ts, app/components/common-chart.tsx
We have rules for formatting numbers according to what their dimension specifies.
Previously those rules applied only to the table.
Now they apply to the tooltips of the charts.
=> feat: Tooltips show numbers that are formatted according to their dimension formatter

.eslintrc.json, app/charts/table/cell-desktop.tsx, app/charts/table/cell-mobile.tsx, app/charts/table/group-header.tsx, app/charts/table/table-content.tsx, app/charts/table/table-state.tsx, app/components/chart-filters-list.tsx, app/components/form.tsx, app/configurator/components/datatable.tsx, app/configurator/components/field.tsx, app/configurator/table/table-chart-options.tsx, app/docs/components.tsx, app/docs/tooltips.docs.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers/index.ts, app/graphql/schema.graphql, app/graphql/shared-types.ts, app/pages/docs/index.tsx, app/rdf/parse.ts, app/themes/federal.tsx
- feat: Add tooltip for dimension which have descriptions
- feat: Use drop-shadow for arrow to be included in shadow
- feat: Add dimension tooltip in data table
=> Dimension description

app/charts/map/map-legend.tsx, app/components/chart-filters-list.tsx, app/docs/components.tsx, app/docs/tooltips.docs.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers/index.ts, app/graphql/schema.graphql, app/graphql/shared-types.ts, app/pages/docs/index.tsx, app/rdf/parse.ts, app/themes/federal.tsx
Dimension related formatting was not applied to continuous color and circle legend of map legend.
fix #712
To test with the einmalverguetung_fuer_photovoltaikanlagen dataset.
/en/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen%2F13?previous=%7B%22includeDrafts%22%3Afalse%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22photovoltaik%22%7D&dataSource=Int
=> Better formatting for map legend items

app/rdf/query-search-score-utils.ts, app/rdf/query-search.spec.ts, app/rdf/query-search.ts
Removing full text search and use simple contain for search.﻿
=> feat: Cube search does not use full text search engine

app/components/chart-footnotes.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-table-preview.tsx
We have logic to watch the height of the container for chart and table
in published view. This is to ensure that when switching from table
to chart, we have no jump of content.
Before, we would watch the height automatically and it sometimes would
make the container a bit too short to accomodate the map when it mounts.
I suspect it would for a brief time show scrollbars on Edge, and those
scrollbars would offset the layers that were drawn at this point.
Now, we measure the height just before switching to the other view,
instead of doing it continuously. This ensures that the height is stable
and it removes the geojson layers offset bug on Edge.
fix https://github.com/visualize-admin/visualization-tool/issues/723
=> fix: Map offset on edge

CHANGELOG.md, app/charts/index.ts, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, cypress/integration/filters.spec.ts
Fix #708
Since filters for the map have been improved to initially contain the downmost areas, they did not retain the previous filters.
Here, we put back the filters from the previous config inside the new config.
=> Retain filters when switching to map

app/charts/map/map.tsx
The map offset problem would disappear after a window resize.
Here, we trigger a resize after the style data has been loaded
and it fixes the offset problem between viz layer and base layer.
=> fix: Map offset in edition page

app/components/debug-search.tsx, app/configurator/components/dataset-browse.tsx, app/configurator/components/select-dataset-step.tsx, app/configurator/components/stepper.tsx, app/rdf/query-cube-metadata.ts, app/rdf/query-search-score-utils.spec.ts, app/rdf/query-search-score-utils.ts, app/rdf/query-search.spec.ts, app/rdf/query-search.ts, app/rdf/query-utils.ts, cypress/integration/filters.spec.ts, cypress/integration/search.spec.ts, cypress/integration/selectors.ts, cypress/integration/symbol-layer-colors.spec.ts
Fix #740 and #730
- The inconsistency between the left panel and the number of results was due to the query for the results not returning datasets without theme or creator.
- There was also a problem that we did not search via theme / creator if we already had results through name description. To fix this problem, we only do one query. Since some datasets can miss the theme / creator / publisher, we have to do a `bound()` check.
=> Search improvements

app/charts/area/areas-state.tsx, app/charts/bar/bars-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/axis-height-linear.tsx, app/charts/shared/axis-width-linear.tsx, app/charts/shared/chart-data-filters.tsx, app/charts/table/table-content.tsx, app/components/chart-filters-list.tsx, app/components/form.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/field.tsx, app/utils/maybe-tooltip.tsx
=> feat: Add dimension descriptions to more places in UI

CHANGELOG.md, app/charts/chart-config-ui-options.ts, app/charts/column/columns-simple.tsx, app/charts/column/columns-state.tsx, app/charts/index.ts, app/charts/pie/pie-state.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/config-types.ts, app/domain/data.ts
When I was starting to implement Ordinal Measures in maps, I noticed that we do not allow to sort Geo dimensions (by name or measure).
I think we should enable this, as essentially they are just Nominal dimensions with coordinates attached – this PR adds support for sorting Geo dimensions.
Additionally, I've noticed that sorting doesn't work properly when there are undefined values, see screenshots down below – it was related to treating undefined values as NaNs instead of -1s. Also, the switch between Pie chart and Column / Area chart (and vice versa) was resulting in blank sorting by value in the segment field (it's also fixed now).
- create a new column chart
- add segmentation by Parameter
- set sorting by total size
-  switch to pie chart
- go to segmentation
- see that it's …
=> feat: Sorting improvements

app/pages/_cube-checker.tsx
Correctly detect multi valued predicates in cube checker
If there were multiple values in one field, the cube checker
would incorrectly mark those as failing.
=> fix: Correctly detect multi valued fields in cube checker

app/rdf/queries.ts, e2e/actions.ts, e2e/high-filter-value-count.spec.ts, e2e/selectors.ts, e2e/types.ts, yarn.lock
When a filter had too much values in it, the HTTP query to Stardog
would fail due to a too large HTTPPayload (since the filter values
were inside the query).
Now if a filter has too much values, the filtering on our end. Too much here is > 100.
We will fetch more data from SPARQL, but I do not see another way.
Presumably, when we have more than 100 values in a filter, from a user
point of view, we want more values *in* than *out*, so hopefully the
number of values  from the SPARQL result that will not be used, will be low.
- Use a dataset with a high number of values inside a filter (for example, this dataset with the population for each cantons of Zurich: `/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_hierarchy_test13_switzerland_canton_municipality%2F3?dataSource= …
=> High filter value count

app/components/chart-footnotes.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
- feat: Use bold for footnotes labels, and use swiss date format
I used a translation string for the colon since in French, there is a space before the colon.
Fixes https://github.com/orgs/visualize-admin/projects/1/views/18
=> Bold footnotes label

app/rdf/queries.ts
As dimensions of nominal scale type can also be used as color mappings, we should also fetch `schema:color` for them to potentially populate default colors.
=> feat: Fetch colors for nominal dimensions

CHANGELOG.md, app/charts/map/map-legend.tsx, app/charts/map/map-state.tsx, app/charts/map/map-tooltip.tsx, app/charts/shared/colors.tsx, app/charts/shared/legend-color.tsx, app/configurator/components/chart-controls/color-picker.tsx
As we use D3's `color` function to parse color strings, we are free to use any CSS Color Module Level 3 compatible strings to specify colors.
In the test dataset provided by @Rdataflow ([test_ord_507](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!testcolor507d-znxzma1yb17/)) several different conventions are used and all of them work; however, when trying to edit the pre-defined colors in visualize, it's not possible to use the original conventions if it's not a HEX color.
This PR simplifies the color logic to remove the constraint of having to use HEX colors in the color picker.
=> feat: Open up color formats

CHANGELOG.md, app/charts/area/areas-state.tsx, app/charts/chart-config-ui-options.ts, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/index.ts, app/charts/line/lines-state.tsx, app/charts/pie/pie-state.tsx, app/charts/shared/brush.tsx, app/charts/shared/legend-color.tsx, app/charts/shared/use-sync-interactive-filters.tsx, app/configurator/components/chart-controls/section.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/ui-helpers.ts, app/configurator/config-types.ts, app/configurator/configurator-state.tsx, app/configurator/interactive-filters/editor-time-brush.tsx, app/configurator/interactive-filters/editor-time-interval-brush.tsx, app/docs/lines.docs.tsx, app/domain/data.ts, app/rdf/queries.ts, app/rdf/query-literals.ts, app/utils/sorting-values.ts, e2e/filter-position.spec.ts, e2e/selectors.ts, e2e/sorting.spec.ts, yarn.lock
Added a new sort option called "Automatic" for column / lines / area and pie chart. It uses either
the identifier or the position of the value to sort the values.
Legend is sorted according to this and also the tooltip content values.
Technically, I've tried to group the sorting logic that was dispersed
across chart to be able to more easily add the new sorting method.
- Go to the preview deployment (See "Visit preview" link below)
- Go to the photovoltaik dataset *on int*: `/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/13&dataSource=Int`
- Select {areas,pie,column,lines} charts
- Go the segment and pick "Standort der Anlage" to color
- "Automatic" should be the default selected options, Zurich should come first, Jura should come …
=> feat: Automatic sort based on identifier and position

app/configurator/components/chart-configurator.tsx, app/configurator/config-types.ts, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, e2e/actions.ts, e2e/color-mapping-maps.spec.ts, yarn.lock
When implementing new color field for maps, I missed one place in the code which handled proper mapping of filters. This PR fixes this issue.
1. Go to `/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftest_ordinal_507%2F7?dataSource=Int`
2. Create a map chart.
3. Activate areaLayer.
4. Select `ord1` as a color mapping dimension.
5. Open filter panel for colors and de-select one value (any).
6. Close the panel and see that the filters work.
7. Repeat the same process on TEST to see how they break currently.
=> fix: Broken color mapping for area layer's categorical color field

app/configurator/components/filters.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Refreshing of colors in multi filter panel wasn't working for map's area layer – this PR makes the handling of color mapping updates more generic (by using `field` + `colorPathField`).
It also introduces a distinction between reshuffling colors (default) and resetting colors (when a dimension has pre-defined colors coming from LINDAS).
=> fix: Resetting color palette for color field with pre-defined colors

app/rdf/queries.ts
When we fetch dimension values, we treat undefined values as
`{ value: "https://cube.link/Undefined", label: "–" }`,
while when we fetch observations, we do
`{ value: "https://cube.link/Undefined", label: "https://cube.link/Undefined" }`,
which can lead to some unexpected bugs. This PR fixes that by using a proper label for such cases (-).
=> fix: Use proper label for undefined namedNodes when fetching observations

app/charts/map/map-state.tsx, app/charts/map/map-tooltip.tsx
Tooltip row for radius was being shown when area layer color was using the same dimension, which resulted in duplicated rows showing the same information – this PR fixes that (and also makes it easier to see the logic for displaying tooltip rows).
Also, it fixes the issue of missing color in map color legend.
=> fix: Map tooltip duplicated values in symbol layer + missing legend colors

app/charts/index.spec.ts, app/charts/index.ts, app/components/debug-search.tsx, app/configurator/components/chart-controls/color-ramp.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/components/field.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-options.tsx, app/graphql/context.tsx, app/graphql/query-meta.ts, app/jest.setup.ts, app/rdf/query-search.ts
Part of technical improvements for the Sprint 4.4.
=> refactor: readQuery instead of passing dataSetMetadata

app/configurator/components/chart-options-selector.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx
Fixes #803.
The filters created by a new color field weren't cleared when switching to a new color dimension. This PR fixes that.
Additionally, it fixes another bug that appeared when no dimension values were selected (undefined color assessor) + it adds fetching of un-filtered dimensions and measures to be used as `dataSetMetadata` (as in general, we need unfiltered values in configurator state).
=> fix: Color field filters not cleared when switching dimensions

app/configurator/components/field.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx
Fixes #788.
In some rare scenarios, user could re-select (or select another dimension) of a field that was still being computed.
In such cases, we would trigger an "update" of a field, which by default cleared all the contents of a field, keeping only `componentIri`, which led to errors with the map charts, as in other places we were expecting `(area | symbol)Layer.color` to be defined.
This PR fixes this issue by populating the color field for map charts while the field is updated.
I am not 100% happy with this solution, as ideally we should set the select value immediately and fetch the hierarchies afterwards (as the part that makes the selection slow is [this part](https://github.com/visualize-admin/visualization-tool/blob/main/app/configurator/config-form.tsx#L79-L95), which fetches …
=> fix: Crashing of charts when selecting component "too fast"

app/charts/shared/legend-color.tsx, app/graphql/resolvers/rdf.ts, app/pages/_document.tsx, app/rdf/queries.ts, e2e/actions.ts, e2e/sorting.spec.ts
In case of hierarchy, we would not sort legend items and instead rely
on hierarchy order, which is not what we want.
Fixes : https://github.com/visualize-admin/visualization-tool/issues/806
- Use the NFI dataset `/en/create/new?cube=https://environment.ld.admin.ch/foen/nfi/49-19-44/cube/1`
- Color by production region
- Verify that legend items are sorted automatically and can sorted in reverse, and by name
=> Sort legend items in case of hierarchy

app/charts/index.ts, app/charts/shared/colors.tsx, app/charts/table/table-state.tsx, app/configurator/components/chart-controls/color-palette.tsx, app/configurator/components/filters.tsx, app/configurator/components/ui-helpers.ts, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-options.tsx, app/configurator/table/table-chart-sorting-options.tsx, app/palettes.ts
Closes #808.
Previously we incorrectly enabled bar and heat map column style options for some dimension types; this PR improves that by enabling them only for numerical measures and allowing to use categories for other dimension types. It also moves a placeholder text "Select a dimension" to top, instead of being the last option.
Additionally, there is now a "dimension" color palette, which exists when there are pre-defined colors attached to dimension values; we are then able to select such palette from ColorPalette picker.
1. Go to `/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftest_ordinal_507%2F7?dataSource=Int`
2. Select `ord1` dimension in Columns section.
3. Change column style to `Categories`.
4. See that the values are colored according to custom dimension …
=> feat: Refinements to table column styles

app/.env.development, app/components/chart-footnotes.tsx, app/components/debug-panel/DebugPanel.tsx, app/configurator/components/dataset-preview.tsx, app/configurator/components/datatable.tsx, app/domain/datasource/index.ts, app/domain/env.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolvers/index.ts, app/pages/api/client-env.ts, app/rdf/queries.ts, app/rdf/sparql-utils.spec.ts, app/rdf/sparql-utils.ts, app/scripts/cube.ts
Closes #563.
Fixes #779.
- Add a "Run SPARQL query" button to dataset preview
- Fix "Run SPARQL query" urls pointing to wrong LINDAS environments (now it's based on current DataSource)
- Consolidate fetching of data cube preview + preview observations (so we have access to editor url in the right place)
1. Go to any dataset preview and see that there is a Run SPARQL query button below table.
2. Choose other datasets from different data source environments (Prod, Int, Test) on the same Visualize environment (TEST) and see that the button works correctly with every data environment.
=> feat: Run SPARQL query enhancements

app/components/form.tsx, app/configurator/components/dataset-browse.tsx, app/docs/form.docs.tsx, app/graphql/resolvers/rdf.ts, app/rdf/query-search.ts, e2e/actions.ts, e2e/search.spec.ts, e2e/selectors.ts
Fixes https://github.com/visualize-admin/visualization-tool/issues/811
- feat: Default sort order is newest, when a search is made, it switches to relevance
=> Default search order

app/gql-flamegraph/devtool.tsx, app/graphql/client.tsx, app/graphql/devtools.prod.ts
=> Show contents of urql panel in PROD

app/docs/testing.mdx
Add explanation on graphql devtool in docs
=> docs: Add docs on graphql devtool

app/configurator/components/chart-configurator.tsx, app/graphql/context.tsx, app/graphql/resolvers.spec.ts, app/graphql/resolvers/rdf.ts, app/rdf/queries.ts, app/rdf/query-hierarchies.ts, app/rdf/query-literals.ts, app/rdf/query-unit-labels.ts, app/typings/rdf.d.ts, app/utils/cached-with-ttl.ts, app/utils/timed.ts
While investigating queries, I noticed that we were loading the cubes a lot,
since the dataCubeByIri resolver is high and needs to load the cube shape.
Since the cube can be shared across resolvers, I used a loader.
Since the cube does not change a lot, I added also an application level
cache through the cachedWithTTL helper. This means that even across requests,
within a 60s timespan, the cube will be resolved through a cache.
Every interaction with cubes in the cube configurator should be faster.
=> Use a cube loader

app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/pie/pie-state.tsx, app/utils/sorting-values.ts
When ordering segment, "position" has priority over "identifier".
fix https://github.com/visualize-admin/visualization-tool/issues/580
fix https://github.com/visualize-admin/visualization-tool/issues/820
=> fix: Order for sorting is position / identifier

app/configurator/components/filters.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/palettes.ts
Recently we enabled fetching of default colors attached to dimensions, but it turned out they weren't enabled for segment fields – this PR fixes that. It also corrects display of reset / refresh based on whether a palette is `dimension` or not (and not as previously, where we just checked if dimension has custom colors).
=> fix: Use dimension colors for segments

app/components/header.tsx, app/configurator/components/layout.tsx, app/configurator/components/select-dataset-step.tsx
Based on [this comment](https://github.com/visualize-admin/visualization-tool/pull/818#issuecomment-1302328451).
Additionally, this PR fixes configurator size (again takes the full width of the page).
=> feat: UI refinements

app/configurator/components/use-hierarchy-parents.spec.ts, app/configurator/components/use-hierarchy-parents.tsx, app/test/__fixtures/data/tarrifs-hierarchy.json
- fix: Do not uniqueBy hierarchy values
- feat: Add debug method for graphviz
Fix https://github.com/visualize-admin/visualization-tool/issues/822#issuecomment-1308752418
=> Fix unique values hierarchy

app/configurator/components/dataset-browse.tsx
Open search results only on title
Hover effect on all the search result is misleading since the chips for themes / organisations can
be clicked. Here only the title is clickable, and it gets an underline on hover.
=> feat: Open search result only on title

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, app/configurator/components/chart-configurator.tsx, app/configurator/table/table-chart-options.tsx, app/graphql/context.tsx, app/pages/_cube-checker.tsx, e2e/filters.spec.ts, e2e/sorting.spec.ts, e2e/symbol-layer-colors.spec.ts
Fixes #852.
While Temporal dimensions should have Interval scale type, there is no restriction on Cube Creator side to define them in such way; that's why they can have other scale types. I think we should still enable the usage of these "incorrect" combinations.
This PR adds support for such cases & adds a cube rule check to inform the users that the mapping anyways should be changed.
=> fix: Missing dates in filters

app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/axis-height-linear.tsx, app/formatters.ts
Fixes #861.
E2E test fixed in #866 (update of the dataset)
1. Go to /en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd000502_sad_01%2F6?dataSource=Int and create a new chart.
2. Select `Gas = Methane` and `Source of emission = Forest land`.
3. Check that Y axis looks correct.
4. Optional: Switch Source of emission filter to other values and see that the axis looks correct for all combinations of filters.
=> fix: Y axis formatting for small values

CHANGELOG.md, app/components/data-download.tsx, app/configurator/components/datatable.tsx
Closes #753.
1. Go to `/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd010701%2F7?previous=%7B"includeDrafts"%3Afalse%7D&dataSource=Prod` (or any other dataset).
2. Download a CSV or Excel file.
3. The order of columns in the downloaded file should match what's visible in the dataset preview.
=> feat: Sort columns properly in downloaded files

app/charts/shared/chart-data-filters.tsx, app/components/form.tsx, app/components/select-tree.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/field.tsx, app/configurator/config-form.tsx, app/docs/form.docs.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/rdf/queries.ts, app/themes/federal.tsx, app/themes/index.ts, e2e/actions.ts, e2e/tooltip.spec.ts, e2e/unversioned.spec.ts
- Use bathing water with hierarchies (check draft when searching)
- In the data filters, the "observation location" select should display the hierarchy as a tree
- When activating interactive filters, the interactive filter also displays the hierarchy as a tree
=> Use trees in selects when hierarchy is present

app/charts/table/table-state.tsx, app/utils/sorting-values.ts, e2e/filters.spec.ts
Closes #871.
`position -> label`?
1. Go to `/en/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd003001_colors%2F2&dataSource=Int`.
2. Create a table chart.
3. Look at the values inside the table and see that they are sorted left to right, according to `position -> identifier -> label`.
4. Check that it's still possible to sort individual columns and that they still take the above logic into account. Best visible with `Status` column.
=> feat: Sort table values properly

app/configurator/components/filters.tsx
Closes #891.
For first-level depths (-1 or 0), we depend on expandability of the whole group to render expand buttons; for following levels, we should always render (and conditionally show / hide) them, so that the indent is correct.
=> fix: Render expand button for depth > 0

app/pages/embed/[chartId].tsx
Otherwise the parsing of `created_at` throws an error.
=> fix: Serialize props in embed mode

app/charts/area/chart-area.tsx, app/charts/column/chart-column.tsx, app/charts/line/chart-lines.tsx, app/charts/pie/chart-pie.tsx, app/charts/scatterplot/chart-scatterplot.tsx, app/charts/shared/legend-color.tsx, app/components/form.tsx, app/configurator/components/chart-annotator.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-controls/section.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/configurator.tsx, app/configurator/components/filters.tsx, app/configurator/configurator-state.tsx, app/configurator/interactive-filters/helpers.ts, app/configurator/interactive-filters/interactive-filters-config-options.tsx, app/configurator/interactive-filters/interactive-filters-config-state.tsx, app/configurator/interactive-filters/interactive-filters-configurator.tsx, app/docs/lines.docs.tsx, app/docs/scatterplot.docs.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/themes/federal.tsx, e2e/filters.spec.ts, e2e/tooltip.spec.ts
This moves the checkbox for "interactive" from the dedicated "interactive filters" section to the data filters and segment settings. The date filters changes will be in another PR.
- Go to any dataset
- "Interactive" switches should be inside the "Filters" section on the left
- "Interactive" switch is also available for segments
=> In place interactive filters

app/charts/column/columns-state.tsx, app/charts/shared/chart-data-filters.tsx, app/components/form.tsx, app/components/select-tree.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx, app/rdf/tree-utils.ts, app/utils/hierarchy.ts, app/utils/sorting-values.ts
Hierarchies inside filters are sorted by identifier.
A search input helps navigate a value inside a large hierarchy.
Open a dataset with a hierarchy ([bathing water with hierarchy](https://visualization-tool-git-feat-tree-sort-search-ixt1.vercel.app/en/browse?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22bathing+water%22%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd0104%2F11&dataSource=Int), [photovoltaik](https://visualization-tool-git-feat-tree-sort-search-ixt1.vercel.app/en/browse?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22photovoltaik%22%7D&dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen%2F13&dataSource=Int), [gas …
=> feat: Sort hierarchy by id + add search input

app/charts/index.ts, app/charts/shared/legend-color-helpers.ts, app/charts/shared/legend-color.tsx, app/configurator/components/use-hierarchy-parents.tsx, app/configurator/config-form.tsx, app/domain/data.ts, app/gql-flamegraph/devtool.tsx, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/schema.graphql, app/rdf/queries.ts, app/rdf/query-dimension-values.ts, app/rdf/query-hierarchies.ts, app/rdf/query-labels.ts, app/rdf/tree-utils.spec.ts, app/rdf/tree-utils.ts, app/test/__fixtures/data/forest-area-by-production-region.json, app/test/__fixtures/data/multiple-root-hierarchy.json, app/utils/bfs.ts, app/utils/dfs.ts, app/utils/hierarchy.ts, e2e/abbreviations.spec.ts, e2e/filters.spec.ts, e2e/query-hierarchies.spec.ts, e2e/selectors.ts, e2e/sorting.spec.ts, e2e/tooltip.spec.ts, yarn.lock
Handle multiple root hierarchy on the server by transforming the tree
```
Switzerland (hierarchy: cantons)
Zurich, Appenzell, Schwiz....
Switzerland (hierarchy: production region)
Jura, Plateau ...
Switzerland (hierarchy: protection region)
Jura + Plateau, Southwestern alps
```
We notice that it is the same root (Switzerland) for the 3 hierarchies, so we transform the tree into
```
Switzerland (hierarchy: cantons)
Cantons
Zurich, Appenzell, Schwiz....
Production region
Jura, Plateau ...
Protection region
Jura + Plateau, Southwestern alps
```
This way, the front-end does not have to know about those multiple roots.
Putting this PR in draft as I'd like to see with Thomas Bettler if the hierarchy is correct as I see multiple hierarchy nodes with "-".
Should fix …
=> Multiple hierarchy root handling

app/charts/shared/legend-color.tsx, app/components/chart-footnotes.tsx, app/components/chart-published.tsx, app/components/metadata-panel.tsx, app/components/publish-actions.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/pages/__test/[env]/[slug].tsx, app/pages/embed/[chartId].tsx, app/pages/v/[chartId].tsx, app/utils/embed.tsx
Adds an option in the embed popover to choose either minimal or standard view for the chart when it's embedded.
Technically, it adds a query parameter "embedOptions" that is then picked up by the view to hide some elements under the chart.
Fix #943 
How to test:
- Open on https://visualization-tool-git-feat-embed-options-ixt1.vercel.app/en/v/sO8qHplebSER?dataSource=Prod
- Click the embed options
- Choose either standard or minimal options.
- The page should refresh to show how the chart would be embedded (right now, on smaller screen, the refresh triggers a layout change, which makes the popover move a little, a possible solution could be to have an [alternate layout for published view](https://github.com/visualize-admin/visualization-tool/pull/948) but I am keeping the dicussion into the …
=> Embed options

app/gql-flamegraph/devtool.tsx, app/package.json, app/rdf/batch-load.ts, app/rdf/queries.ts, app/rdf/query-cache.ts, app/rdf/query-dimension-values.ts, app/rdf/query-hierarchies.ts, app/utils/chart-config/versioning.ts, yarn.lock
Introduce LRU caches for some SPARQL queries that could take a long time (>1000ms).
Due to the nature of LRU caches, queries that are not used are removed from the cache.
If a dataset has not been opened yet, it takes time since the cache is not primed but then all interactions with the dataset are snappier.
=> Performance improvements

app/rdf/query-search.ts
Fixes on search
- Empty list of IRIs was not taken into account
- Different languages lead to combinatorial explosion and poor performance as the dataset list grew 
Previously the table returned in the results would be like so
`cubeIRI` | `cube` | `theme` | `creator` 
--- | --- | --- | ---
1 | Snowfalls | Snow | WSL
1 | Schneefall | Schnee | WSL
1 | Snowfalls | Schnee | WSL
1 | Schneefall | Snow | WSL
So for a single cube we would have 4  (more generally N_LANGUAGE*N_FIELDS_WITH_LANGUAGE) different rows instead of 2 (one row for each language). The added equality filter ensures each row is in the same language.
Fix https://github.com/visualize-admin/visualization-tool/issues/963
Fix https://github.com/visualize-admin/visualization-tool/issues/959
=> fix: Search performance and empty results

app/docs/rdf-to-visualize.mdx
=> docs: Add documentation for sh:in

app/components/hint.tsx, app/graphql/resolvers/rdf.ts
Throw error when cube is not found
Fix https://github.com/visualize-admin/visualization-tool/issues/967
=> fix: Do not show spinner in chart page when cube is not found

app/components/metadata-panel.tsx, app/components/publish-actions.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/field.tsx, app/domain/data.ts, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/rdf/queries.ts, app/utils/sorting-values.ts
1. Dimension values were not parsed when fetched in batch
2. The sorters from makeDimensionValueSorters return sorters that must receive dimension labels, not dimension values
=> Sorting values

app/charts/map/chart-map.tsx, app/charts/shared/legend-color.tsx, e2e/sorting.spec.ts
The categorical values in map legend were not sorted by position. Fixes Fixes https://github.com/visualize-admin/visualization-tool/issues/986
- refactor: Use generic so the caller does not have to do as
- feat: Sort map categorical legend values by position
- fix: Prevent error flash on map
=> Sorting of map legend items

app/components/content-mdx-provider.tsx, app/components/footer.tsx, app/components/header.tsx, app/components/layout.tsx, e2e/actions.ts, e2e/home.spec.ts
=> fix: Go to right page when switching page on content pages (legal / impress)

app/components/header.tsx, app/components/hint.tsx, app/configurator/components/configurator.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #1000.
This PR adds a loading state when `Configurator` state is equal to "INITIAL" but user is actually on "/create/[chartId]" page. Previously we were showing a blank page, now there is a centered spinner. This is a case when we wait for chart state to be initialised (`initChartStateFromCube`, `initChartStateFromChart`).
Also, additional message is shown within `Loading` component when 7.5s has passed and the data is still being loaded.
=> feat: Show Loading spinner between SELECTING_DATASET and CONFIGURING_CHART steps

app/configurator/components/datatable.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts
Fixes #1002.
As the dimensions are only required to know how to sort the columns, we do not need to load the hierarchies in the `DataCubePreview` query. Loading them can be the most time consuming part of the query in some cases.
Basing on the example shared in #1002, it makes it fast  to load the preview, instead of taking ~10s as is currently the case.
=> perf: Do not load hierarchies when fetching DataCubePreview

app/utils/router/helpers.ts
Fixes #853.
In order for the browser buttons to work properly there was a need to include current window state when doing `window.history.replaceState` when setting URL params; otherwise the navigation didn't work properly.
=> fix: Navigation with browser buttons

app/configurator/components/use-redirect-to-versioned-cube.tsx, app/configurator/configurator-state.tsx
Fixes #939.
We were initializing configurator state with default data source – this PR fixes that by correctly initializing the state with correct data source.
1. Go to `/en/browse?dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd102_fuellstand_gasspeicher&dataSource=Int `(see that no cube version is specified in the URL).
2. See that the cube loads correctly (version 6).
=> fix: Redirect to versioned cube

app/charts/column/columns-state.tsx, app/charts/index.ts, app/configurator/components/datatable.tsx, app/configurator/configurator-state.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/types.ts
Contributes to fixing #1002.
Previously, we loaded hierarchies every time we depended on `dimensionMetadata` fragment. However, I believe it's not necessary to load hierarchies everywhere, as for example, they don't seem to be used in places that use `DataCubeObservations` query. When we don't fetch them there, the loading times of the chart inside the editor & published mode can be improved for datasets that use hierarchies (in the example in #1002, the published chart loads in 1.5s instead of ~10s).
This PR excludes loading of hierarchies across multiple queries if they are not required further down in the app.
1. Go to [this published chart](https://visualization-tool-git-perf-published-chart-ixt1.vercel.app/en/v/RF4kn1KqqdDN?dataSource=Test) from this PR's deployment preview
2. Go to …
=> perf: Only load hierarchies where necessary

app/configurator/components/filters.tsx, app/configurator/configurator-state.tsx, app/configurator/table/table-chart-options.tsx
Fixes #872.
There was an issue with subsetting the chart config (lodash's `get`) when using strings for table fields, which are iris and not "regular" strings, like `segment` or `x`. This PR fixes that by using an array instead of string.
Also, there was a problem with refreshing color mappings for table, as we were expecting a `segment` field to be passed to `updateColorMapping`, while we also can pass table fields.
1. Go to https://visualization-tool-7acz0ufkc-ixt1.vercel.app
2. Look for Einmalvergütung für Photovoltaikanlagen dataset (INT).
3. Create a chart.
4. Switch to a table chart.
5. Change Standort der Anlage's column type to Category.
6. See that it's possible to map the colors individually to each value.
7. See that it's possible to refresh the colors.
8. Switch to Jahr …
=> fix: Color mapping for tables

app/charts/index.spec.ts, app/charts/index.ts, app/components/chart-filters-list.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-selection-tabs.tsx, app/components/debug-panel/DebugPanel.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-controls/drag-and-drop-tab.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/configurator/interactive-filters/helpers.ts, app/configurator/interactive-filters/interactive-filters-config-options.tsx, app/configurator/interactive-filters/interactive-filters-configurator.tsx, app/configurator/table/table-chart-configurator.tsx, app/configurator/table/table-chart-options.tsx, app/configurator/table/table-chart-sorting-options.tsx, app/graphql/apollo-sentry-plugin.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/types.ts, app/scripts/cube.ts, app/utils/opendata.ts
Fixes #1017.
The main problem with #1016 was that I only updated the types in `client.readQuery` in `configurator-state.tsx` 
`DataCubeMetadataWithComponentValuesQuery` → `DataCubeMetadataWithComponentValuesQueryVariables`
`DataCubeMetadataWithComponentValuesQueryVariables` → `DataCubeMetadataWithComponentValuesAndHierarchiesQueryVariables`
but missed updating the document (`DataCubeMetadataWithComponentValuesDocument` → `DataCubeMetadataWithComponentValuesAndHierarchiesDocument`), so we were accessing dimensions without hierarchies in this place.
This PR fixes that (and also adds a unit test to make sure we select top-most hierarchy value by default in filters).
TODO
=> fix: Selecting top-most hierarchy value by default in filters

app/charts/area/chart-area.tsx, app/charts/chart-loading-wrapper.tsx, app/charts/column/chart-column.tsx, app/charts/column/columns-state.tsx, app/charts/line/chart-lines.tsx, app/charts/map/chart-map.tsx, app/charts/pie/chart-pie.tsx, app/charts/scatterplot/chart-scatterplot.tsx, app/charts/table/chart-table.tsx, app/components/chart-footnotes.tsx, app/components/data-download.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/datatable.tsx, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolvers/rdf.ts, app/pages/_pivot.tsx, app/rdf/query-dimension-values.ts, app/utils/sorting-values.spec.ts, app/utils/sorting-values.ts
Fixes #1015 (sorting issue).
The main goal of this PR is to improve sorting of hierarchical dimensions (X field) in column charts.
As mentioned in #1015, we should first sort by hierarchical values and then by non-hierarchical values (by depth). We also fall back to sorting by label in `byAuto` mode, as it seems that sometimes `identifier` and `position` are undefined.
This required us to fetch components with hierarchies, but this change is only scoped to column charts, for other charts we do not need to fetch hierarchies for this reason.
Additionally, I refactored GQL queries, so we do not fetch dimensions & measures in `DataCubeObservations` query, but we need to explicitly fetch them with `Components` query. I believe it makes it more clear (and potentially efficient) to separate this …
=> feat: Improve sorting for mix of hierarchical and regular values

app/components/chart-footnotes.tsx, app/components/chart-published.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
=> feat: Update minimal embed mode chart footnotes

app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/pie/pie-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/chart-helpers.spec.tsx, app/charts/shared/chart-helpers.tsx, app/charts/shared/use-abbreviations.ts
Fixes #1024.
We were creating the lookups in `useMaybeAbbreviations` by using dimension values. While it's not a problem for most dimensions, we only fetch min and max values for temporal dimensions which leads to problems described in #1024.
This PR fixes that by passing "fake" dimension values (based on the ones that appear in the data) for column charts (X axis).
=> fix: Temporal values in X axis in column charts

app/charts/area/chart-area.tsx, app/charts/column/chart-column.tsx, app/charts/line/chart-lines.tsx, app/charts/map/chart-map.tsx, app/charts/map/map.tsx, app/charts/map/ref.ts, app/charts/pie/chart-pie.tsx, app/charts/scatterplot/chart-scatterplot.tsx, app/charts/shared/chart-helpers.spec.tsx, app/charts/shared/chart-helpers.tsx, app/charts/table/chart-table.tsx, app/components/chart-filters-list.tsx, app/components/chart-footnotes.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/common-chart.tsx, app/components/data-download.tsx, app/configurator/components/datatable.tsx, app/configurator/config-types.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers/rdf.ts, app/graphql/schema.graphql, app/rdf/queries.ts
Contributes towards fixing #1028.
This PR aims to improve data loading performance for published charts.
The main change from this PR is about fetching only the dimensions that are actually used in the chart (for the published chart) to reduce the need to fetch values for them, which can lead to unnecessary fetch of dozens of dimensions and their values for some datasets. It means that we only show the dimensions that are actually used in chart in the metadata panel, table preview and data download. I think that from the end user perspective it makes sense, as what we see on the chart is reflected in all the other places. Let me know about your opinions here @RDataflow @ptbrowne.
Additionally to the change described above, I also tried to understand what causes the time difference …
=> perf: Only fetch necessary components

app/rdf/namespace.ts, app/rdf/queries.ts, app/typings/rdf.d.ts
Until the appropriate change is implemented in rdf-cube-view-query library, we manually override sorting of dimensions to improve performance.
For more context see the description and discussion in #1031.
cc: @Rdataflow
=> perf: Do not sort dimensions in View

app/charts/column/columns-grouped.tsx, app/charts/column/columns-simple.tsx, app/charts/column/columns-stacked.tsx, app/charts/column/rendering-utils.tsx, app/configurator/components/chart-configurator.tsx
- Animation field is now hidden behind a feature flag
- Columns now animate correctly during a resize event
=> feat: Hide Animation behind feature flag & fix column animations

app/package.json, app/rdf/queries.ts, app/typings/rdf.d.ts, yarn.lock
As the [new version of rdf-cube-view-query library](https://github.com/zazuko/rdf-cube-view-query/releases/tag/v1.12.0) has been released, there is no need to manually disable sorting of the columns anymore.
=> chore: Update rdf-cube-view-query

app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/utils/sorting-values.spec.ts
Fixes #1063.
This PR fixes broken horizontal axis sorting in column charts. It turns out that the sorting logic (`makeDimensionSorters`) was not connected to grouped & stacked bar charts – now this should work correctly, including sorting by measure.
1. Recreate the chart from #1063.
2. See that it's possible to sort by auto, measure and name (including reverse-sort).
=> fix: Horizontal axis sorting (column charts)

app/charts/shared/legend-color-helpers.ts, app/charts/shared/legend-color.spec.ts
Fixes #1068.
Previously, the ColorLegend would display all values present inside a hierarchical dimension, even if the chart didn't have these values. This PR fixes that by only showing values actually present in a chart.
=> fix: Only show values actually present in the data in ColorLegend

CHANGELOG.md, app/graphql/client.tsx, app/graphql/context.tsx, app/pages/api/graphql.ts
When investigating the performance of SPARQL queries, I noticed that the payload sent to the client in the debug mode (query, time of execution) is sent always, even when debug mode is off.
As this additional data can account for significant amount of additional payload size that's not always needed, I restricted this behavior to only occur when the debug mode is explicitly turned on.
Change in payload size using default chart when editing the dataset (with server-side cache disabled):
- Bathing water quality: 507kB vs 273kB
- Forest fire danger: 378kB vs 252kB
=> perf: Only send GQL extensions to the client when needed

CHANGELOG.md, app/components/content-mdx-provider.tsx, app/homepage/intro.tsx, app/pages/[slug].tsx, app/pages/_app.tsx, app/pages/index.tsx
- Do not import `ContentMDXProvider` in `_app.tsx`, to prevent adding ~2.8MB in payload size to every page, but rather only use it where it's necessary
Right now, if we want to render a simple column chart, we bundle all column chart related logic, including the grouped chart state, stacked chart state, code for rendering grouped & stacked charts, etc.
I believe that this could be avoided if we split the code in a manner that we treat these are different chart types and not include them in one function (ChartColumnsVisualization) that conditionally renders a given chart subtype. I think this would be a bigger change, as we would need to treat these chart subtypes as chart types, e.g. "column-simple", "column-grouped", "column-stacked". With this we wouldn't bundle things that are not …
=> perf: Improve code splitting

CHANGELOG.md, app/charts/column/columns-stacked-state.tsx
Fixes #1088.
As we use d3's `stacked` method in stacked bar chart, there can be situations similar to area chart, where we need imputation when some data point does not have some value defined in previous / following data point. We also need to impute such values, to make sure there are no NaNs returned when computing the coordinates for the chart.
I think it doesn't make sense to provide imputation options to users, as we can safely treat non-existing, imputed values as 0, as they do not have influence of how the chart is drawn, as in area chart (lines connecting the data points), and we do not show such values in the tooltip anyway.
=> fix: Stacked column chart with missing values

CHANGELOG.md, app/rdf/queries.ts
This PR fixes the server-side filtering of versioned dimensions.
It turns out that the server-side filtering didn't work when dimension was a versioned dimension – we were comparing unversioned filter values with versioned filter values.
1. Open `Bathing water quality` dataset.
2. Add coloring by Bathing site.
3. See that the chart works.
4. Follow above steps on other environments (e.g. Prod) to see that no data is returned.
=> fix: Server-side filtering for versioned dimensions

CHANGELOG.md, app/charts/shared/chart-data-filters.tsx, app/components/form.tsx, app/components/select-tree.tsx
Closes #1104.
It turned out we didn't refresh the `filteredOptions` in the `SelectTree` component when `options` property changed. This PR fixes this, which means users can now switch the language in the published mode and see correctly updated select values.
It also adds some space between list of filters and button to activate interactive filters.
=> fix: Hierarchical interactive filter language switch

CHANGELOG.md, app/charts/index.ts, app/configurator/components/chart-type-selector.tsx
Closes #1038.
This PR adds an object that holds the preferred chart order, which makes the table chart the least preferred option.
=> feat: Make table chart type the least preferred option

CHANGELOG.md, app/graphql/context.tsx, app/graphql/resolvers/index.ts, app/rdf/query-geo-shapes.ts
Closes #1106.
This PR drops the usage of a federated SPARQL query and adds a dedicated `geoSparqlClient` instead, to vastly improve the performance of fetching geographical shapes.
When testing the cube from #1106, we **went down from around 120 to 1.5 seconds**.
=> perf: Improve performance of fetching geoShapes

app/charts/map/chart-map.tsx, app/charts/shared/axis-height-linear.tsx, app/rdf/query-geo-shapes.ts
When testing #1106, I noticed that some cubes still load the data for quite long time (e.g. [this Elcom cube](https://test.visualize.admin.ch/en/browse?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22elcom%22%7D&dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Felcom%2Felectricityprice&dataSource=Prod)).
After investigation, it turned out that we wrongly handle potential undefined geometries when fetching the shapes. This PR fixes that (and also removes a case of infinite loading spinner when there is an error during geo shapes fetching – now an empty map will be shown).
cc @sosiology
=> fix: Infinite geographical shapes loading

app/graphql/apollo-sentry-plugin.ts, app/sentry.server.config.js
This PR uses a correct Sentry instance in the Apollo plugin (the one with the environment already set).
=> fix: Import correct Sentry in Apollo plugin

CHANGELOG.md, app/charts/chart-config-ui-options.ts, app/charts/map/map-legend.tsx, app/charts/map/map-state.tsx, app/charts/shared/legend-color.tsx, app/configurator/components/chart-controls/color-ramp.tsx, app/formatters.ts, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #1139.
This PR:
- adds a warning message when no temporal dimensions are available to be animated (when they are being used in other fields),
- improves spacing of interactive color legend items,
- fixes Jenks color legend (thresholds calculations),
- makes height of numerical color legend dynamic, depending of the height of tick labels.
=> feat: UI improvements

app/charts/shared/chart-data-filters.tsx, app/charts/shared/chart-helpers.tsx, app/configurator/configurator-state.tsx, app/rdf/query-dimension-values.ts
This PR:
- changes the way we treat setting "No filter" values in filters. Previously we would remove the filter, but this behavior is not desired in interactive filters. We keep the filter in this case now, as we have a way to remove the filters in the editing mode anyway (by clicking a trash bin icon),
- fixes frozen interactive filters, by comparing new possible filters with interactive filters, and not chart filters.
cc @sosiology
=> fix: Interactive cascading filters

CHANGELOG.md, app/components/data-download.tsx
This PR fixes sorting of dates in XLSX download by sorting upfront, before parsing, to access raw observation values, where dates are formatted in YYYY-MM-DD manner.
It should be safe to do so, as dates in Cube Creator are formatted according to ISO standards (https://www.w3.org/TR/owl-time/#time:GeneralDateTimeDescription).
=> fix: Dates sorting in data download

CHANGELOG.md, app/browse/datatable.tsx, app/browser/dataset-preview.tsx, app/components/use-redirect-to-versioned-cube.spec.tsx, app/components/use-redirect-to-versioned-cube.tsx, app/pages/_app.tsx, app/utils/l10n-provider.tsx
Fixes #1174.
This PR fixes overwriting of locale when redirecting to a versioned cube by removing locale from `pathname`. There is no need to pass the locale here, and using it led to making the router switch to old locale, while it previously had already updated the locale via `routeChangeComplete` event.
This behavior was only visible when previewing larger cubes, probably due to a fact that it took longer to update the content and a small lag was introduced that made the broken behavior visible.
=> fix: Locale overwriting

CHANGELOG.md, app/charts/shared/chart-data-filters.tsx, app/utils/hierarchy.ts
Fixes #1176.
It turns out we didn't filter hierarchy when passing it to a filter. This PR fixes that, as well as makes it necessary to pass `possibleValues` to `hierarchyToOptions` function, so this error shouldn't appear again.
To test, replicate a chart from #1176 using the preview deployment.
=> fix: Hierarchical cascading filters

app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/chart-dimensions.tsx, app/charts/shared/chart-state.ts
Fixes #1183.
It turns out we need to have one more type of chart data, where we filter it only by interactive color legend filters to properly compute left chart margin.
To test, recreate the chart from #1183 and see that the labels are no longer cut.
=> fix: Cut Y axis labels

CHANGELOG.md, app/configurator/configurator-state.tsx
Fixes #1188.
As only some charts support hierarchies, we need to try to retrieve both ComponentsWithHierarchies – and when they're not available, fall back to Components.
=> fix: Changing chart type when copying non-hierarchical charts

CHANGELOG.md, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers/rdf.ts, app/graphql/schema.graphql, e2e/abbreviations.spec.ts, e2e/color-mapping-maps.spec.ts, e2e/filter-position.spec.ts, e2e/ordinal-measures.spec.ts, e2e/sorting.spec.ts, e2e/symbol-layer-colors.spec.ts
Closes #1192.
To improve performance of fetching the dataset preview, this PR disables loading of dimension values along with it.
It means that we lose the feature to sort the preview by value positions, but for 10-observations preview that might not be necessary anyway.
At first I tried to add a new GQL fragment, `DimensionMetadataWithoutValuesFragment`, but ultimately I decided to introduce a new property to `dataCubeByIri` query – `disableValuesLoad` – to keep the same types, as we use `DimensionMetadataFragment` across the whole application, and the preview query is scoped to one components (dataset preview table).
=> perf: Disable loading of dimension values for preview query

CHANGELOG.md, app/charts/shared/chart-data-filters.tsx
...need to spread the object to force re-load of the components.
=> fix: Infinite loading of cascading filters

CHANGELOG.md, app/components/debug-panel/DebugPanel.tsx, app/components/debug-panel/index.tsx, app/docs/chart-preview-via-api.mdx, app/pages/docs/index.tsx
Closes #1200.
As the types can differ a lot between different chart types, and there are some hidden dependencies to some properties (e.g. multi filter connected to temporal X field, some sorting options only available for column charts, segmentation not available for maps, etc, etc), I decided to point to the file with types in the docs and **expose the configurator & interactive filters debug panel via flag**.
By doing this, editors will be able to edit a chart, tailor it to their needs, and dump the state to the console to copy and modify it slightly to fit their needs. With this we don't need to prepare a complete list of all combination possibilities between the types, which would be really difficult, but rather encourage to pre-create a chart and edit it afterwards, making sure that …
=> docs: Describe chart preview via API + expose DebugPanel via flag

README.md, app/components/header.tsx, app/components/login-menu.tsx, app/configurator/components/layout.tsx, app/db/config.ts, app/login/components/login-menu.tsx, app/login/components/profile-content-tabs.tsx, app/login/components/profile-header.tsx, app/login/components/profile-tables.tsx, app/login/utils.ts, app/pages/profile.tsx
This PR updates the login-related UI elements to bring them closer to the design.
=> feat: Login UI improvements

app/charts/index.ts, app/configurator/components/chart-options-selector.tsx
This PR disables selecting measures without units in multi-line combo chart.
=> feat: Disable no-unit measures in multi line combo charts

CHANGELOG.md, app/docs/rdf-to-visualize.mdx, app/rdf/parse.ts, app/rdf/queries.ts
=> chore: Also retrieve dimension units via qudt:hasUnit

CHANGELOG.md, app/domain/data.ts, app/rdf/queries.ts
Closes #1219.
This PR includes retrieval or min and max values stored behind `sh:or`.
=> perf: Retrieve (min|max)Inclusive values stored behind sh:or

app/charts/chart-config-ui-options.ts, app/components/form.tsx, app/themes/federal.tsx
This PR:
- fixes changing combo charts measures (correctly updates color mapping)
- updates Select style
=> fix: Combo charts measure changes

CHANGELOG.md, app/formatters.ts
=> fix: Dates with timezones are now correctly parsed

app/browser/dataset-preview.tsx, app/charts/index.spec.ts, app/charts/index.ts, app/charts/shared/legend-color.tsx, app/charts/shared/use-sync-interactive-filters.spec.tsx, app/components/chart-published.tsx, app/components/chart-selection-tabs.tsx, app/components/debug-panel/DebugPanel.tsx, app/config-types.ts, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/components/configurator.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.tsx, app/configurator/interactive-filters/interactive-filters-configurator.tsx, app/configurator/table/table-chart-configurator.tsx, app/db/config.ts, app/docs/annotations.docs.tsx, app/docs/columns.docs.tsx, app/docs/fixtures.ts, app/docs/lines.docs.tsx, app/docs/scatterplot.docs.tsx, app/login/components/profile-tables.tsx, app/utils/chart-config/api.ts, app/utils/chart-config/versioning.spec.ts, app/utils/chart-config/versioning.ts
This PR provides the technical foundation for the dashboards to allow charts based on different datasets within the same configurator state.
Essentially, it moves the `dataSet` property from the configurator state down to the charts themselves.
1. Go to the deployment preview.
2. Add the following object to the local storage (use `vizualize-configurator-state:EpXqRKzyJxIy` key):
```
{"version":"3.0.0","state":"CONFIGURING_CHART","dataSource":{"type":"sparql","url":"https://lindas.admin.ch/query"},"meta":{"title":{"de":"","fr":"","it":"","en":""},"description":{"de":"","fr":"","it":"","en":""}},"chartConfigs":[{"key":"tPfhn1Lsv4u1","version":"2.3.0","meta":{"title":{"en":"","de":"","fr":"","it":""},"description":{"en":"","de":"","fr":"","it":""}},"dataSet":"https://energy.ld.admin.ch/sfoe/b …
```
=> refactor: Move dataSet from configurator state to chart state

app/charts/combo/chart-combo-line-single.tsx, app/charts/shared/legend-color.tsx, app/components/form.tsx, app/configurator/components/chart-controls/color-palette.tsx, app/configurator/components/chart-controls/color-picker.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/filters.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
This PR updates the Combo charts-related styles along with several other styling adjustments.
- Removed text input from `ColorPicker`
- Removed axis orientation radio buttons from `ComboColumnLine` chart
- Added `OpenMetadataPanelWrapper` to legend items in `ComboLineSingle` chart
- Updated UI strings for left / right axes (`ComboColumnLine` chart)
=> style: Combo charts UI alignments

app/browser/select-dataset-step.tsx
This PR fixes the Framer dataset preview animations not showing sometimes by adding keys where needed.
=> fix: Dataset preview not showing

app/charts/index.spec.ts, app/charts/index.ts
This PR introduces a change to only enable multiline combo chart when there are at least two numerical measures of the same unit.
=> fix: Only enable multiline chart when makes sense

app/browser/context.tsx, app/browser/dataset-browse.tsx, app/browser/select-dataset-step.tsx, app/components/presence.tsx
This PR fixes the issue of metadata panel not showing in dataset preview when some filters were applied prior to navigating there.
The problem was that the `AnimationPresence's` `onExitAnimation` was not triggered, probably related to nesting of `AnimatePresences` with layout animations, some bugs with exit layout animations have been reported e.g. [here](https://github.com/framer/motion/issues/1619). Wrapping the `SearchFilters`' children with `AnimatePresence` fixed the error.
To reproduce go to https://test.visualize.admin.ch/en/browse/theme/https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Fcategory%2Fadministration?dataSource=Prod and select the first dataset.
I also fixed a smaller issue with search filters being cleared when going to dataset preview, this bug looked like in the …
=> fix: Navigation issue with metadata not showing up

CHANGELOG.md, app/rdf/cube-filters.ts, app/rdf/query-utils.ts
=> chore: Remove deprecated validThrough cube filters

app/login/utils.ts
This PR removes providers presence checking each time we want to get current user, as there doesn't seem a reason to do so at this point, and this causes the username to switch back between currently logged in username and "Sign in" string when navigating through the pages.
=> fix: Flickering username

.vscode/extensions.json, .vscode/launch.json, README.md
Some minot tweaks to the DX by:
1. Replacing the extension recommendations with a non-depreciated MDX extension
1. Added launch.json with setup for using vscode debugger
1. Added documentation in README.md
=> chore(DX): :technologist: add debug launcher and fix extension recommendations

CHANGELOG.md, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-grouped.tsx, app/charts/column/columns-state.tsx, app/charts/column/columns.tsx, app/charts/column/rendering-utils.ts
It was requested to remove the Standard Errors from the column visualization (#589) so that the ErrorWhiskers component does not show for these columns.
While I was able to filter the chartDatum for any values where the getYError was null, I was also able to remove the getError from the getAnnotationinfo when null
=> fix(column): :recycle: remove ErrorWhisker and Tooltip when error is null

.vscode/tasks.json
We don't need to have `tsc` run explicitly in the background to check the types anymore; I guess this was needed with an older VS Code / TS version.
=> chore: Remove outdated task

app/charts/index.spec.ts, app/charts/shared/chart-helpers.spec.tsx, app/configurator/components/field.spec.tsx, app/configurator/components/filters.spec.ts, app/configurator/configurator-state.spec.tsx, app/graphql/context.tsx, app/package.json, app/pages/_cube-checker.tsx, app/rdf/create-source.ts, app/test/cube-view-query-mock.ts, app/typings/rdf.d.ts, yarn.lock
This PR updates `cube-view-query` library to allow to pass SPARQL client directly into `Source`, instead of being re-created each time.
This allows us to keep track of queries made through this library inside the `DebugPanel`, which means we will now track every query :)
=> chore: Make all queries traceable (DebugPanel)

CHANGELOG.md, app/rdf/queries.ts, app/typings/rdf.d.ts
This PR improves performance of fetching dataset previews by using a[ new version](https://github.com/zazuko/rdf-cube-view-query/commit/a83ec4c789dada1d8300bec4fefc28576f0184c2) of cube-view-query library.
Open any dataset in deployment preview and TEST to see the difference :)
=> perf: Optimize dataset previews performance

app/components/select-tree.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/components/field.tsx, app/pages/__test/[env]/[slug].tsx, app/test/__fixtures/config/int/configs.ts, e2e/actions.ts, e2e/color-mapping-maps.spec.ts, e2e/filters.spec.ts, e2e/fixtures/map-nfi-chart-config.json, e2e/ordinal-measures.spec.ts, e2e/query-hierarchies.spec.ts, e2e/selectors.ts, e2e/sorting.spec.ts, e2e/symbol-layer-colors.spec.ts, e2e/tooltip.spec.ts
There are a number of E2E tests that are failing, making it harder to judge if the dependabot can be safely merged in.  From the latest github Actions there are 14 failing tests.
__Completed__
__Skipped__
This PR is to act as a benchmark so I can figure out overtime which E2E tests are still failing.
=> chore(e2e): :white_check_mark: fix E2E tests

app/charts/shared/interaction/tooltip-box.tsx
>The Mouse Over Box should appear on the right Side so as not to be cut off. The Problem appears only by embedding in AEM or iFrame. The URL to share is ok : https://visualize.admin.ch/en/v/uCDwLYAzMW5c
>
>![image](https://github.com/visualize-admin/visualization-tool/assets/59728961/69fbd344-9d43-4a60-a6bc-14def589ae48)
>
>#1266
After investigating it seems the bug is cased on small containers where the tooltip size is larger then the allotted space.  Since larger screens still work, I looked to create a solution that could conditionally place the tooltip based on the charts size rather then measuring the window.
Created a fold function that accepts the `chartWidth` and returns a function that can be used to define the behaviour of the xPlacement depending on that size.  Here we can …
=> fix(interaction): :bug: create conditional Xplacement based on container width

app/db/config.ts
This PR fixes dataset migrations. The problem should not appear again, as now the `chartConfig` is typed, as it should have been, since it's migrated to the latest version already.
=> fix: Dataset migration

app/sentry.client.config.js, app/sentry.edge.config.js, app/sentry.server.config.js
To reduce noise in Sentry, we should only focus on logging the things in deployed instances of the application.
=> chore: Disable Sentry in development

CHANGELOG.md, app/charts/chart-config-ui-options.ts, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx
Fixes #1256.
This PR:
- consolidates handling of multi-filters (by setting top-most hierarchy value by default),
- fixes setting filter values when removing fields,
- fixes changing segmentation component in column charts.
=> fix: Segmentation / filtering issues

app/package.json, app/sentry.client.config.js, app/sentry.edge.config.js, app/sentry.server.config.js, yarn.lock
This PR upgrades Sentry to v7.7.0 and decreases sample trace rate from 100% to 10%.
=> chore: Sentry updates

app/components/debug-panel/DebugPanel.tsx, app/graphql/context.tsx, app/rdf/create-source.ts, app/rdf/queries.ts, app/rdf/query-literals.ts, app/typings/rdf.d.ts
This PR attempts to better scope pragmas when fetching the cube preview by using a clean Source, without pragmas, as having `#pragma join.hash off` breaks previews for some cubes for yet unknown reasons (see e.g. https://test.visualize.admin.ch/en/browse?previous=%7B%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-94%2Fcube%2F2023-1&dataSource=Prod).
For more information see [this conversation on Zulip](https://zulip.zazuko.com/#narrow/stream/40-bafu-ext/topic/performance/near/377890).
I aimed for a simple solution by overriding `getMainSource`  View's method, which might not be ideal, but:
- I didn't see a better, simple way of doing so (we can't just pass a clean Source into the View constructor, as [this is how it's retrieved …
=> fix: Better scope pragmas to fix data cube preview query

CHANGELOG.md, app/rdf/query-cube-metadata.ts, app/rdf/query-utils.spec.ts, app/rdf/query-utils.ts
This PR adds support for localized landing pages (e.g. new BLW cubes).
As it looks like these are the only cubes that currently support localized landing pages, I kept support for non-localized ones by falling back to non-translated properties.
Also see https://zulip.zazuko.com/#narrow/stream/40-bafu-ext/topic/blw-cubes/near/379002
=> feat: Landing page can be localized

CHANGELOG.md, app/browser/dataset-preview.tsx
Fixes #1289.
1. Go to [this link](https://visualization-tool-git-fix-add-datasource-when-copy-0d3e63-ixt1.vercel.app/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22photo%22%7D&dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen%2F14&dataSource=Int).
2. Copy the link from "Start a visualization" button.
3. ✅ See that the link includes data source at the end (`&dataSource=Int`).
4. Go to [the corresponding link on TEST](https://test.visualize.admin.ch/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22photo%22%7D&dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen%2F14&dataSource=Int).
5. Copy the link from "Start a visualization" button.
6. ❌ See that …
=> fix: Include dataSource in new visualization link

app/browse/datatable.tsx, app/charts/shared/chart-data-filters.tsx, app/charts/shared/chart-helpers.tsx, app/components/chart-filters-list.tsx, app/components/chart-footnotes.tsx, app/components/chart-with-filters.tsx
Closes #1318.
This PR improves the performance of published charts by only querying components that are actually used in the chart.
=> perf: Specify component iris in query filters

app/components/form.tsx, app/components/select-tree.tsx, app/configurator/components/field.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/rdf/queries.ts, app/rdf/query-dimension-values.ts, app/themes/federal.tsx
Closes #1310
Closes #1317
The initial implementation of most recent date filter didn't take other filters into account – we were simply taking max date for a given dimension, even if such selection led to missing data.
This PR fixes this by querying max date taking other filters into account, to effectively take "most recent date with data for current filter selection".
It also enables this logic for `TemporalOrdinalDimensions`.
1. Go to [this link](https://visualization-tool-git-fix-most-recent-date-filter-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd0104/6&dataSource=Prod).
2. Change chart type to a pie chart.
3. Toggle "Use most recent" in the date filter.
4. See that the selected date equals to 09.09.2021.
5. Repeat the same process on INT.
6. See that …
=> fix: Most recent date filter needs to take other filters into account

app/charts/index.ts, app/components/chart-preview.tsx, app/components/debug-panel/index.tsx, app/components/form.tsx, app/config-types.ts, app/configurator/components/configurator.tsx, app/configurator/components/field-i18n.ts, app/configurator/components/ui-helpers.ts, app/configurator/configurator-state.tsx, app/icons/components/IcLayoutSingleURLs.tsx, app/icons/components/index.tsx, app/icons/svg/ic_layout_single_urls.svg, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #1325.
This PR introduces a single URLs layout mode, where user can publish several charts separately.
A new browser tab is opened for every chart, instead of the first one, which behaves in a regular way (goes to `/v/chart-id?publishSuccess=true` page).
⚠️ **Publishing possible to test when deployed to TEST.**
1. Go to [the preview link](https://visualization-tool-git-feat-single-urls-layout-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod&flag__layoutStep=true) (only to test the non-publishing behavior) or to [TEST link](https://test.visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod&flag__layoutStep=true) …
=> feat: Single URLs layout

app/rdf/query-cube-preview.spec.ts, app/rdf/query-cube-preview.ts
We need to account for a fact that sometimes dimension can have a generic iri, like `schema:name` – when creating observations, we need to bypass subjects of `BlankNode` type.
1. Go to [deployment preview](https://visualization-tool-git-fix-dataset-preview-generic-07a3d2-ixt1.vercel.app/en/browse?previous=%7B%7D&dataset=https%3A%2F%2Ftransport.ld.admin.ch%2Ffoca%2FFOCA_Air_traffic_statistics_movements%2F3&dataSource=Prod) and see that it's not broken.
3. Go to [TEST](https://test.visualize.admin.ch/en/browse?previous=%7B%22order%22%3A%22CREATED_DESC%22%2C%22search%22%3A%22%22%7D&dataset=https%3A%2F%2Ftransport.ld.admin.ch%2Ffoca%2FFOCA_Air_traffic_statistics_movements%2F3&dataSource=Prod) and see that it's broken.
=> fix: Observations creation in dataset preview

.github/workflows/performance-tests.yml, k6/performance-tests/generate-github-action.js, k6/performance-tests/graphql/DataCubeComponents.js, k6/performance-tests/graphql/DataCubeMetadata.js, k6/performance-tests/graphql/DataCubeObservations.js, k6/performance-tests/graphql/DataCubePreview.js, k6/performance-tests/graphql/PossibleFilters.js
This PR:
- increases number of test iterations from 1 to 2 to decrease number of false-positives (long query duration caused by some factor not related to code change),
- adds `k6_http_req_duration_avg` metric to the payload sent to Prometheus (average request duration computed from 2 iterations),
- adds data correctness checks to every GQL performance test.
These changes are coordinated with accompanying changes to Grafana dashboard.
=> chore: Update k6 performance tests II

app/components/chart-selection-tabs.tsx, app/configurator/configurator-state.tsx, app/db/config.ts, app/login/components/profile-content-tabs.tsx, app/login/components/profile-tables.tsx, app/pages/api/config-create.ts, app/pages/api/config-remove.ts, app/pages/api/config-update.ts, app/server/config-controller.ts, app/server/nextkit.ts
- Reduce flickering the 1st time we save a draft (not changing the page)
- Correctly saving published state the 1st time when we first create the config : I had not seen this because I had first put published state's default as "DRAFT" in Prisma schema locally,  then had changed it to default=PUBLISHED without running the migration. Then on test, the default was PUBLISHED and I could see that at creation time, published draft was not taken into account. After running prisma migrate locally, I could reproduce the bug and fix it.
=> Save draft

CHANGELOG.md, app/configurator/components/filters.tsx, app/configurator/config-form.tsx, app/configurator/table/table-chart-options.tsx
This PR:
- disables "Interactive" toggle for temporal dimension in table charts, as we can't use interactive filters with tables,
- fixes empty select elements in tables.
**Fixed version (PR)**
1. Go to [this link](https://visualization-tool-git-fix-tables-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
3. Select Kanton column.
4. See that the select elements are filled.
5. Go to Jahr der Vergütung column.
6. See that the "Interactive" toggle is not here.
**Broken version (TEST, INT, PROD)**
Go to [this link](https://visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9) and repeat the steps above to …
=> fix: Table issues

app/config-types.ts, app/configurator/configurator-state.tsx, app/docs/columns.docs.tsx, app/docs/fixtures.ts, app/docs/lines.docs.tsx, app/docs/scatterplot.docs.tsx, app/utils/chart-config/versioning.spec.ts, app/utils/chart-config/versioning.ts
Made a silly mistake where I put published_state in the config and also
in the configurator state. Published_state should only be in the config,
not the state.
This resulted in old charts not being able to edited/copied/viewed due
to missing property while decoding configurator state.
Fix https://github.com/visualize-admin/visualization-tool/issues/1354
=> fix: Remove extra published_state property in the configurator state

CHANGELOG.md, app/configurator/components/field.tsx
Fixes #1359.
This PR fixes the accessing of max dimension value in case there are no values.
=> fix: Non-optional accessor

CHANGELOG.md, app/pages/api/graphql.ts
This PR increases GQL API timeout duration from [default 15s](https://vercel.com/docs/functions/runtimes#max-duration) to 60s (see https://vercel.com/docs/functions/configuring-functions/duration), so larger cubes should also load in deployment previews.
=> chore: Increase GQL API timeout duration (Vercel)

app/charts/index.spec.ts, app/charts/index.ts
fix #1373
When creating a column chart, we take either temporal or temporal ordinal dimension as default
for x axis.
This can be verified with NFI cubes where the "Inventory" dimension is a Temporal Ordinal Dimension.
For ex: `/en/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_T-6.1%40bundesamt-fuer-umwelt%2Fcube%2F2024-1&dataSource=Test`
=> feat: Temporal ordinal dimension is taken as second priority when inferring x-axis for columns

app/components/chart-selection-tabs.tsx, app/components/confirmation-dialog.tsx, app/config-types.ts, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/db/config.ts, app/login/components/profile-tables.tsx, app/server/config-controller.ts, app/themes/federal.tsx, app/utils/chart-config/api.ts
Fixing #1379.
When copying over a chart, the key was not removed, and due to small changes in how chart were published, we would try to create a new chart config under the "old" key, leading to an error.
Now, since the key is removed from the config after it has been copied, the new key is correctly used.
=> Fix: Publish chart from copy

CHANGELOG.md, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx
Fixes #1384.
1. Go to [this link](https://visualization-tool-git-fix-single-urls-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
2. Add a second chart.
3. Proceed to layout options.
4. Switch to Separate URLs layout.
5. Publish.
6. See that the first chart replaced the current page and second chart was opened in a new tab.
=> fix: SingleURLs publishing

CHANGELOG.md, app/charts/chart-config-ui-options.spec.ts, app/charts/chart-config-ui-options.ts, app/charts/index.spec.ts, app/charts/index.ts, app/configurator/components/chart-controls/color-ramp.tsx, app/configurator/components/chart-options-selector.tsx, e2e/filters.spec.ts
Fixes #1321.
1. Go to [this link](https://visualization-tool-git-fix-wrong-config-props-setting-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd000502/4&dataSource=Prod).
2. Change chart type to scatterplot.
3. ✅ See that the segment is initialized automatically with `Hierarchy` dimension.
4. Change segment dimension to `Year`.
5. Publish.
6. Click on `Copy and edit this visualization`.
7. ✅ See that the chart correctly loaded into the editor mode.
8. Switch to a column chart.
9. ✅ See that the segment is empty.
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd000502/4&dataSource=Prod).
2. Change chart type to scatterplot.
3. ❌ See that no segment is selected by default.
4. Select `Hierarchy` …
=> fix: Issues with copying published charts

CHANGELOG.md, app/browser/select-dataset-step.tsx, app/components/use-redirect-to-latest-cube.spec.tsx, app/components/use-redirect-to-latest-cube.tsx, app/rdf/light-cube.ts, app/rdf/query-cube-metadata.ts, app/rdf/query-latest-cube-iri.ts
Fixes #1390.
I think the problem was that we didn't treat the cube with version "2023-2" as versioned cube and failed to fetch latest iri. This PR solves this on a SPARQL query level (and removes relying on checking if a cube is versioned by a heuristic).
With this change, we try to look for newest version of the cube if an older version was passed in the URL (respecting published status).
**PR**
1. Go to [this link](https://visualization-tool-git-fix-redirects-to-latest-cube-ixt1.vercel.app/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22nfi%22%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-20%2Fcube%2F2023-2&dataSource=Prod) (NFI/2023-02).
2. ✅ See that the latest version of the cube has been loaded.
**TEST**
1. Go to [this …
=> fix: Redirects to latest cube

CHANGELOG.md, app/login/components/profile-tables.tsx, e2e/selectors.ts
This PR keeps the currently selected locale when using profile actions (view, edit, copy, share) from the user profile.
1. Go to [this link](https://visualization-tool-git-fix-keep-locale-in-user-actions-ixt1.vercel.app/en?dataSource=Prod).
2. Log in (e.g. as `ixt` test user).
3. Navigate to user profile.
4. Edit an example chart.
5. See that the page opened in English (on TEST it opens in German).
=> fix: Keep locale in user actions

CHANGELOG.md, app/charts/chart-data-wrapper.spec.tsx, app/charts/chart-data-wrapper.tsx, app/charts/map/helpers.ts, app/charts/map/map.tsx
Fixes #1394.
1. Go to any map chart from the deployment preview, e.g. [here](https://visualization-tool-git-fix-initial-map-zoom-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
2. Switch to a map chart.
3. Refresh the page several times.
4. See that the initial zoom level is correctly applied.
=> fix: Initial map zoom

CHANGELOG.md, app/configurator/components/chart-configurator.spec.ts, app/configurator/components/chart-configurator.tsx
Fixes #1402.
1. Go to [this link](https://visualization-tool-git-fix-adding-filter-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd0066/12&dataSource=Prod).
2. Add a new, optional filter (e.g. Year).
3. See that the filter is correctly added.
=> fix: Can't add an optional filter

CHANGELOG.md, app/components/chart-preview.tsx, app/configurator/components/chart-controls/color-palette.tsx, app/configurator/components/configurator.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx, app/urql-cache.mock.ts
This PR tackles the first point of #1423 to initialize chart config with filters that make sense (only applicable when starting a chart from scratch).
While in some cases it will improve performance, in other cases it might decrease it (depending on the scale of a cube / number of dimensions, etc) – but generally it should increase UX to never show a chart w/o observations.
**PR**
1. Go to [this link](https://visualization-tool-git-perf-load-possible-filters-upfront-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1&dataSource=Test).
2. Watch closely that the first chart that loads is not empty.
**TEST**
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1&da …
=> perf: Load PossibleFilters upfront

app/charts/shared/chart-data-filters.tsx, app/charts/shared/ensure-possible-filters.ts, app/configurator/components/chart-configurator.tsx, app/configurator/configurator-state.tsx, app/rdf/query-possible-filters.ts, app/utils/ordered-is-equal.ts
Fixes #1430
This PR prevents the `PossibleFilters` query from being fired when it doesn't make sense (no filters are present). It also shares some logic related to `PossibleFilters` query across different parts of the application.
**PR**
1. Go to [this link](https://visualization-tool-git-fix-possible-filters-error-ixt1.vercel.app/en/create/new?cube=https://communication.ld.admin.ch/ofcom/map_tv_konz/8&dataSource=Int).
2. ✅ See that there's no error in the `Filters` section.
**TEST**
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://communication.ld.admin.ch/ofcom/map_tv_konz/8&dataSource=Int).
2. ❌ See that there's an error in the `Filters` section.
=> fix: PossibleFilters firing when doesn't make sense

scripts/docker-build-push.sh
Right now, it is difficult given an image retrieved via docker pull registry.ldbar.ch/visualize-admin/visualization-tool:release
to know which is the version. Using labels, we should be able to know exactly the version by doing docker inspect on the image.
=> Label docker image

app/sentry.client.config.js
Ignore Outlook caused error
This seems to be a safe error to ignore, and was already listed in our list of common
errors.
https://www.notion.so/interactivethings/Common-Sentry-Ignore-Rules-f0b1e94a6ac34ffd8d39b53498c48a45?pvs=4
=> fix: Error Outlook safe link crawler error

app/charts/chart-data-wrapper.spec.tsx, app/charts/chart-data-wrapper.tsx, app/components/hint.tsx, app/graphql/hooks.spec.tsx, app/graphql/hooks.ts
Closes #1126
Currently we unmount the whole chart component and use `<Loading />` when data is being fetched via the `ChartDataWrapper` component.
In my opinion, this is suboptimal user experience, as we lose track of the old chart state when the data is being loaded, and immediately are presented with new state, losing the sense of the difference between prior and current charts.
As we take advantage of smooth transitions between chart states in several chart types, it should result in less obtrusive behavior of the chart component, especially when manipulating chart filters.
For an initial implementation I applied a semi-transparent `LoadingOverlay` component, this might be changed after @KerstinFaye's review 😁
I also discovered a bug in the hook for data loading we use, that results in …
=> feat: Do not unmount the chart when data is being loaded

CHANGELOG.md, app/components/chart-panel.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/filters.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.spec.tsx, app/configurator/configurator-state.tsx
This PR fixes a bug discovered by @sosiology that made the temporal X axis filtering not working with cubes merged by a temporal dimension. It also fixes an error of not displaying date pickers for joinBy dimensions.
1. Go to [this link](https://visualization-tool-git-fix-year-filtering-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod&flag__add-dataset=true).
2. Add a new cube – Heavy Metal Soil Contamination.
3. Go to horizontal axis.
4. ✅ See that the date pickers are displayed.
5. ✅ See that date filtering works.
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod&flag__add-datase …
=> fix: Temporal joinBy dimension X axis filters

CHANGELOG.md, app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/combo/combo-line-column-state.tsx, app/charts/combo/combo-line-dual-state.tsx, app/charts/combo/combo-line-single-state.tsx, app/charts/line/lines-state.tsx, app/charts/map/helpers.ts, app/charts/map/map-state.tsx, app/charts/map/map.tsx, app/charts/pie/pie-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/table/table-state.tsx, app/components/chart-with-filters.tsx, app/components/hint.tsx, app/configurator/components/chart-options-selector.tsx
Closes #1459
This PR makes use of `keepPreviousData` property in data fetching hooks to not unmount sidebar contents on option change. It also improves the situation around content jumps when changing chart type.
1. Go to [this link](https://visualization-tool-git-fix-do-not-unmount-sidebar-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
2. ✅ Change chart type from column to line back and forth several times and see that there is only a small blink when doing so.
3. Open Horizontal Axis.
4. Change year filter either by using a slider or time picker.
5. ✅ See that the sidebar is slightly dimmed when data is being loaded, mirroring the chart's behavior.
1. Go to [this …
=> fix: Do not unmount sidebar content when data is being re-fetched

app/.env.development, app/domain/datasource/index.ts, app/domain/env.ts, app/stores/data-source.ts
This PR fixes `ENDPOINT` variable to correctly reference cached LINDAS endpoint, which should fix missing data source selection in preview deployments.
=> fix: Cached endpoint variables

CHANGELOG.md, app/browse/datatable.tsx, app/charts/area/chart-area.tsx, app/charts/chart-data-wrapper.tsx, app/charts/column/chart-column.tsx, app/charts/combo/chart-combo-line-column.tsx, app/charts/combo/chart-combo-line-dual.tsx, app/charts/combo/chart-combo-line-single.tsx, app/charts/line/chart-lines.tsx, app/charts/map/chart-map.tsx, app/charts/pie/chart-pie.tsx, app/charts/scatterplot/chart-scatterplot.tsx, app/charts/shared/ChartProps.tsx, app/charts/shared/chart-data-filters.tsx, app/charts/shared/chart-helpers.spec.tsx, app/charts/shared/chart-helpers.tsx, app/charts/table/chart-table.tsx, app/components/chart-filters-list.tsx, app/components/chart-footnotes.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-with-filters.tsx, app/components/copy-to-clipboard-text-input.tsx, app/components/publish-actions.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/configurator-state.tsx, app/docs/publish-actions.stories.tsx, app/pages/v/[chartId].tsx
Closes #1423
This PR removes a need to pass dimensions to get query filters, as it looks like this behavior is not needed. It was used to filter out interactive data filters that are a part of dimensions, which should always be true (except when a dimension was completely removed from a cube, which would most probably break the chart anyway).
With this change we fire `DataCubesObservations` query in parallel to `DataCubesComponents` fetching, not waiting for it to finish first.
1. Go to [this link](https://visualization-tool-git-perf-fire-observations-query-asap-ixt1.vercel.app/en/v/ENrCApdv5Cbo?dataSource=Prod).
2. Open Developer Tools (e.g. [see how to do so on Chrome](https://developer.chrome.com/docs/devtools/open)).
3. Switch to the Network tab.
4. Reload the page.
5. ✅ See that the …
=> perf: Fire DataCubesObservations query as soon as possible

CHANGELOG.md, app/charts/shared/containers.tsx, app/charts/shared/use-width.tsx, app/utils/use-timed-previous.ts
This PR improves resize behavior by disabling transitions during resizing. It also makes the Observer container a flex one, so the `Loading` indicator is centered when the chart is being loaded.
1. Go to [this link](https://visualization-tool-git-feat-improve-resizing-behavior-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/14&dataSource=Int).
2. Disable browser fullscreen mode if applicable.
3. Grab the edge of the browser window and resize it.
4. ✅ See that the chart resizes immediately.
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/14&dataSource=Int).
2. Disable browser fullscreen mode if applicable.
3. Grab …
=> feat: Improve resizing behavior

app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-utils.ts
Fixes #1468
This PR fixes broken `ChartPreview` subgrid positioning in Tall dashboard in edit mode when interactive filters were applied in one chart and not in the other. It also shares common styles between `ChartPreview` and `ChartPublished`.
1. Go to [this link](https://visualization-tool-git-fix-dashboard-layout-with-in-f57b73-ixt1.vercel.app/en?dataSource=Prod).
2. Select a cube and create a chart.
3. Add two more charts, so there are three in total.
4. Enable interactive filter for the third chart.
5. Proceed to Layout options.
6. Change Layout to Tall Dashboard layout.
7. ✅ Scroll down to see that the last chart has correct layout.
1. Repeat the above process on TEST.
2. ❌ Scroll down to see that the last chart has broken layout.
=> fix: ChartPreview with Tall dashboard layout in edit mode and interactive filters active

app/browser/dataset-browse.tsx, app/browser/filters.tsx, app/browser/search-page-data.tsx, app/browser/select-dataset-step.tsx, app/components/graphql-search.stories.tsx, app/configurator/components/add-dataset-dialog.tsx, app/domain/data.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers/index.ts, app/graphql/resolvers/rdf.ts, app/graphql/resolvers/sql.ts, app/graphql/schema.graphql, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/rdf/query-cube-termsets.ts, app/rdf/query-search.ts, app/rdf/query-termsets.ts
Adds a section in the search page to filter cubes per termsets.
The visualize filter is there. I have added the `distinct` in the count clause when
counting by cube, since multiple dimensions of the same cube might have the termset.
```
PREFIX cube: <https://cube.link/>
PREFIX meta: <https://cube.link/meta/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT DISTINCT (COUNT(distinct ?iri) as ?count) ?termsetIri ?termsetLabel WHERE {
?iri cube:observationConstraint/sh:property ?dimension .
?dimension a cube:KeyDimension .
?dimension sh:in/rdf:rest*/rdf:first ?value.
?value schema:inDefinedTermSet ?termsetIri .
?termsetIri a meta:SharedDimension .
OPTIONAL { ?termsetIri schema:name ?termsetLabel_en . …
```
=> Termset search filter

app/configurator/components/chart-configurator.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state.tsx
This PR fixes removing of optional data filters by choosing `No filter` option.
1. Go to [this link](https://visualization-tool-git-fix-removing-optional-dimensions-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1&dataSource=Prod).
2. Add `Active since` filter.
3. Change filter value to `No filter`.
4. ✅ See that the filter was correctly removed.
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1&dataSource=Prod).
2. Add `Active since` filter.
3. Change filter value to `No filter`.
4. ❌ See that the filter was not removed and that there's a PossibleFilters error.
=> fix: Removing of optional filters

app/configurator/components/annotation-options.tsx
Closes #1427
This PR adds a "Save" button to the annotations panel. As we save the changes dynamically anyway, it acts as a "close panel" button.
=> feat: Add Save button to annotations panel

app/configurator/components/chart-configurator.tsx
Closes #1504
This PR introduces a safety net to not allow missing key dimension filters. Such situation could happen e.g. by manually modifying the `localStorage` state; in the current implementation, we do not add back key dimensions, but rather keep them as addable filters, which breaks the charts.
=> feat: Add safety net for missing key dimension filters

CHANGELOG.md, app/domain/datasource/constants.ts, app/utils/chart-config/versioning.ts
This PR:
- adds `dataSource` in case it's missing (might be the case for very old chart configs), defaulting to PROD,
- migrates non-cached PROD `dataSource` to cached one.
=> fix: Add dataSource in case it's missing

app/charts/shared/containers.tsx
Remove min height constraint on charts in grid layout
- Prevents footer to be cut when charts is resized vertically.
- :warning" Chart could become invisible if legend is too high (should be a problem that is less grave than having the footer cut)
=> feat: Remove min height constraint on grid layout

README.md
Add docs on how and when to use the vercel development db.
=> docs: Add bit on migrations & dev database

CHANGELOG.md, app/components/chart-panel-layout-grid.tsx, app/components/chart-panel.tsx, app/components/chart-preview.tsx, app/components/chart-selection-tabs.tsx, app/components/drag-handle.tsx, app/components/menu-action-item.tsx, app/components/row-actions.tsx, app/config-types.ts, app/configurator/components/add-new-dataset-panel.tsx, app/configurator/components/annotators.tsx, app/configurator/components/dataset-control-section.tsx, app/configurator/components/field-i18n.ts, app/configurator/components/layout-configurator.tsx, app/configurator/components/ui-helpers.ts, app/configurator/configurator-state.tsx, app/icons/components/IcDuplicate.tsx, app/icons/components/IcLayoutCanvas.tsx, app/icons/components/index.tsx, app/icons/svg/ic_duplicate.svg, app/icons/svg/ic_layout_canvas.svg, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/profile-tables.tsx
Add action menu for layout mode allowing the user to go back to the chart
and go back to the configure mode.
Align the menu used in the configure mode to use the ArrowMenu to have
coherence between the views.
=> Dashboard action menu

app/components/chart-panel-layout-grid.tsx, app/components/chart-panel.tsx, app/components/chart-published.tsx
Dashboard canvas works in published mode
I had not repercuted some of the improvements from chart-preview to chart-published.
Passing ref, className, and children is necessary for react-grid-layout to work
correctly.
=> Dashboard canvas works in published mode

CHANGELOG.md, app/charts/shared/chart-data-filters.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-shared.tsx, app/components/metadata-panel.tsx, app/configurator/components/field.tsx
Closes #1528
1. Go to [this link](https://vercel.live/open-feedback/visualization-tool-git-style-metadata-button-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1).
2. Select any dataset.
3. Start making a chart.
4. See that the metadata button and show filters buttons are in the same row, after chart's title.
=> style: Update metadata and filters positions + styles

app/browser/dataset-browse.tsx, app/components/chart-selection-tabs.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/dataset-control-section.tsx, app/configurator/components/field.tsx, app/configurator/components/layout-configurator.tsx, app/flags/flag.tsx, app/flags/ls-adapter.ts, app/flags/store.ts, app/flags/types.ts, app/flags/useFlag.ts, app/gql-flamegraph/devtool.tsx
Allowing to deploy to int without features that have not been approved by
BAFU.
Here the following functionalities are put behind flags.
- Searching cubes via termsets
- Merging of cube
- Free canvas functionality for dashboard
- Adding new chart from new dataset
Those flags are set automatically on test.visualize.admin.ch, on Vercel
previews, and on localhost.
=> WIP features behind flags

CHANGELOG.md, app/pages/api/graphql.ts
The default cache of Apollo 3 is using an unbounded cache by default,
which would be vulnerable to denial of service attacks.
The warning was issued when the application was started and Philipp from
Abraxas told us about that.
> Persisted queries are enabled and are using an unbounded cache. Your
> server is vulnerable to denial of service attacks via memory exhaustion.
> Set `cache: "bounded"` or `persistedQueries: false` in your ApolloServer
> constructor, or see https://go.apollo.dev/s/cache-backends for other
> alternatives.
=> fix: Use cache bounded as prescribed by the warning

app/browser/dataset-preview.tsx, app/configurator/components/add-dataset-dialog.tsx, app/locales/en/messages.po
=> feat: Add showing first 10 rows to merging of cubes

Dockerfile, app/domain/env.ts, app/pages/api/auth/[...nextauth].ts, scripts/docker-build-push.sh
As we are using a public OIDC flow with PKCE we should be able to remove the client secret.
=> chore: eIAM cleanup

app/browser/dataset-preview.tsx, app/components/chart-footnotes.tsx, app/components/data-download.spec.ts, app/components/data-download.tsx
=> fix: Full data download (merged cubes)

app/config-types.ts, app/configurator/configurator-state/context.tsx, app/configurator/configurator-state/init.tsx, app/login/components/profile-tables.tsx
=> feat: Initialize layout step when editing saved dashboard

app/charts/chart-data-wrapper.tsx, app/configurator/configurator-state/reducer.tsx
fix: No JoinBy dimension found in cube
When merging some datasets together, we ended up with a "no joinBy dimension
found in cube" error in chart hooks. It seems it is due to stale data
inside useQuery hooks. To prevent those, we unmount the whole ChartDataWrapper
and remount it when cubeIris and or joinBy change.
Fix https://github.com/visualize-admin/visualization-tool/issues/1475
=> Chart data wrapper key

app/utils/chart-config/versioning.ts
Fixes #1475
I am not 100% happy with the solution, but after spending more than 2h researching what might be the underlying problem, I didn't manage to solve it in another way.
I think there is some issue with caching behavior, as `ChartDataWrapper` that loads the data does not immediately switch to a new query, even though the variables were updated.
The current flow is:
- `AddDatasetDialog` fetches the new data via `executeDataCubesComponentsQuery`, which should populate the client-side cache,
- after fetching is done, it dispatches `DATASET_ADD` action that updates the configurator state, which then propagates the changes downstream,
- `ChartDataWrapper` receives updated data, but for some reason does not immediately trigger new query, which leads to joinBy dimension not found error …
=> fix: No joinBy dimension found in cube

app/components/chart-selection-tabs.tsx, app/locales/index.ts
Add labels to tabs in editor mode and preview mode.
We use the title of the charts.
The behavior of the tabs is as follows:
- Each tab is of the same size for consistency
- The ellipsis of the title is done by a semi transparent element
- The tabs have a minimum width
- The tabs list content can scroll once the tabs are too numerous and cannot shrink
- The tabs list also indicate cut-off content via semi transparent element
1. Open a chart
2. Add 4 to 5 charts
3. Add titles to each of the charts
https://github.com/visualize-admin/visualization-tool/assets/465582/97d19e39-bea6-4a4e-9d3d-af874f5a25ae
=> Add labels to tabs

app/components/react-grid.tsx, app/configurator/components/layout-configurator.tsx, app/configurator/configurator-state/reducer.tsx
**PR**
1. Go to [this link](https://visualization-tool-git-feat-another-dashboards-impr-f30f7c-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod&flag__layouter.dashboard.free-canvas=true).
2. Add two more charts.
3. Proceed to layout options.
4. Switch to a Free Canvas Dashboard layout.
5. ✅ See that all charts are initialized next to each other (max four in one row).
**TEST**
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod&flag__layouter.dashboard.free-canvas=true).
2. Add two more charts.
3. Proceed to layout options.
4. Switch to a Free Canvas Dashboard layout.
5. ❌ See that …
=> feat: Make initial free canvas charts smaller

app/components/chart-panel.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-selection-tabs.tsx, app/configurator/components/layout-configurator.tsx
Activate dashboard filters for tab layout
=> feat: Activate shared filters for "tab" layout

app/components/dashboard-interactive-filters.tsx, app/configurator/components/layout-configurator.tsx, app/domain/user-configs.ts, app/graphql/hooks.spec.tsx, app/graphql/hooks.ts, app/homepage/examples.tsx, app/utils/promises.ts, app/utils/use-fetch-data.ts
The shared filter configurator would fetch all the components for all cubes at once,
when in fact they should be fetched independently for each chart config. This PR
fixes that. It takes care of deduping fetching of components for the same cube
filter values.
=> Shared filter configurator filter

app/db/config.ts, app/flags/types.ts, app/pages/statistics.tsx
This PR is a first step towards bringing more understanding about how Visualize evolves.
**Statistics page**
1. Go to [this link](https://visualization-tool-git-feat-statistics-page-ixt1.vercel.app/statistics?dataSource=Prod).
2. See that the chart with basic statistics on the number of charts created on Vercel environments is shown (this page will show information for an environment it's deployed on, once we deploy to PROD, it will show PROD data).
3. Add a new chart using [this link](https://visualization-tool-git-feat-statistics-page-ixt1.vercel.app/?dataSource=Prod).
4. Refresh the Statistics page.
5. See that the number of charts increased 🎉
6. _Optional_: Add a `&flag__easter-eggs=true` to the end of the URL to see an alternative version of the chart.
=> feat: Set up Statistics page

app/components/chart-footnotes.tsx, app/components/chart-published.tsx
In https://github.com/visualize-admin/visualization-tool/pull/1571, we  introduce the use of cube query filters, but this does not play well with tab layout when components are reused.
Some of the data hooks were reused, introducing a mismatch between what was fetched inside the hooks and the new chartConfig.
To force remounting, I used a key on ChartPublishedInner and made it so that we cannot forget it.
This fixes going to the second chart of https://test.visualize.admin.ch/en/v/FeByTTGfNhxL
=> Fix: cube query filters not found

app/components/dialog-close-button.tsx
=> fix: Dialog close button being overlapped by other elements

app/components/dashboard-interactive-filters.tsx
Fixes #1618
**PR**
1. Go to [this link](https://visualization-tool-git-fix-dashboard-filter-initialization-ixt1.vercel.app/en/v/RuxtIhQLBvM7?dataSource=Prod).
2. ✅ See that the chart is loaded correctly (only shows years between 2017 and 2020).
**TEST**
1. Go to [this link](https://test.visualize.admin.ch/en/v/vHwhkeidxzHz?dataSource=Prod).
2. ❌ See that the chart is not loaded correctly (shows full data – between 2014 and 2022, while slider is constrained to 2017-2020).
=> fix: Correctly initialize time filters in dashboard

app/components/chart-selection-tabs.tsx
Fixes #1603
This PR makes sure that we set the correct configurator state when saving the dashboard from layout mode for the first time (no entry in the database yet).
=> fix: Saving draft dashboard from layout options

app/db/config.ts, app/pages/embed/[chartId].tsx, app/pages/statistics.tsx, app/pages/v/[chartId].tsx, app/prisma/schema.prisma
Closes #1611
Contributes towards #1596
This PR sets up a new `ConfigView` table in our database which is used to track the chart views. We store every chart view, to potentially be able to make use of this information in the future and e.g. show charts trending in the last week or month, to understand at what time of the day the charts are viewed, how the metrics are influenced by e.g. Open Linked Day events, etc.
A chart view is counted when:
- there's a visit to `/v/` page,
- there's a visit to `/embed/` page,
or precisely, when `getServerSideProps` function is triggered for these pages.
There's also a new card that shows statistics on views in the Statistics page (see [this link)](https://visualization-tool-git-feat-set-up-chart-view-statistics-ixt1.vercel.app/statistics). The card …
=> feat: Set up chart view statistics

app/rdf/query-termsets.ts
@bprusinowski just caught by accident...
`GET` can in some cases result in `414 URI too long`
proposition:
apply `POST` as for the other queries :+1: - THX for your review
=> use `POST` to avoid `414 URI too long` for longer queries

app/rdf/queries.ts, app/rdf/query-dimension-values.ts
Closes #1470
This PR is an exploration of the feasibility to fetch values for multiple dimensions in a single SPARQL query.
- We need to be able to filter each dimension individually, due to cascading filters behavior. Could be achieved with ```FILTER(IF(?dimensionIri = <A>, ?dimensionIri = <a> && ?dimensionIri = <a>, ?dimensionIri))```
- We need to be able to unversion dimension values per individual dimension (can't unversion values outside of individual SELECT queries, as sometimes `schema:sameAs` is not used to indicate unversioned values, this is only the case when a dimension is versioned).
we need to combine individual queries into a big one (at least that's my current assumption).
=> refactor: Combined query to fetch dimension values

app/rdf/query-dimension-values.ts
add missing pragma to make query evaluation uniform among all dimensions
@bprusinowski
=> add missing pragma

app/rdf/query-cube-preview.ts, app/rdf/query-search.ts
currently cube search queries for subthemes regardless of the organization filter 
- effectively there is no need for this information unless foen org is chosen
currently the subtheme graph isn't constrained (unless org is foen)
- this leads to degraded performance by needlessly crawling among graphs
=> fix cube search performance

app/browser/dataset-browse.tsx, app/components/maybe-link.tsx
Closes #1641
This PR fixes sub-theme filters both on regular search page (URL-based) and in the modal search when adding a chart based on another cube (in-app-state-based).
**PR**
1. Go to [this link](https://visualization-tool-git-fix-subtheme-filters-ixt1.vercel.app/en/browse?dataSource=Prod).
2. Filter by **Federal Office for the Environment FOEN** (Organizations section).
3. ✅ Filter by **Climate** and see that it works.
4. Select **Greenhouse gas emissions by sector and gas** cube.
5. Start a new visualization.
6. Add a new chart based on another cube (click plus button, and afterwards a **Select dataset** button).
7. Filter by **Federal Office for the Environment FOEN** (Organizations section).
8. ✅ Filter by **Climate** and see that it works.
**TEST**
1. Go to [this …
=> fix: Sub-theme filters

CHANGELOG.md, app/charts/map/map.tsx, app/charts/shared/containers.tsx, app/components/chart-panel-layout-grid.tsx, app/components/chart-panel.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/debug-panel/index.tsx, app/components/react-grid.stories.tsx, app/components/react-grid.tsx, app/configurator/configurator-state/reducer.tsx
Closes #1637
**PR**
1. Go to [this link](https://visualization-tool-git-feat-minimum-chart-height-in-b362d7-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
2. Add a super-long title for the chart, e.g. _Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum._
3. Add a new pie chart.
4. Add the same long title to the …
=> feat: Minimum chart height in a dashboard

app/charts/shared/ensure-possible-filters.ts, app/graphql/apollo-sentry-plugin.ts, app/graphql/queries/data-cubes.graphql, app/graphql/query-hooks.ts, app/graphql/resolver-types.ts, app/graphql/resolvers/rdf.ts, app/graphql/resolvers/sql.ts, app/graphql/schema.graphql, app/locales/constants.ts, app/locales/de/messages.po, app/locales/locales.ts, app/utils/chart-config/upgrade-cube.ts, e2e/varnish-cache-preload.spec.ts, k6/load-tests/har/int/edition.js, k6/load-tests/har/prod/edition.js, k6/load-tests/har/test/edition.js, k6/performance-tests/graphql/PossibleFilters.js
Fixes https://github.com/visualize-admin/visualization-tool/pull/1599#issuecomment-2205133720
=> perf: Missing caching per cube iri for some queries

app/charts/map/map-legend.tsx
Closes #1657
1. Go to [this link](https://visualization-tool-git-feat-improve-map-legend-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
2. Switch to a map chart.
3. ✅ See that the color measure unit is visible in the legend title.
=> feat: Add unit to map legend

app/components/arrow-menu.tsx, app/components/chart-selection-tabs.tsx
Closes #1660
1. Go to [this link](https://visualization-tool-git-fix-menu-alignment-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
2. Click on a chevron next to chart icon in the top tabs.
3. ✅ See that the popover's arrow is correctly centered.
=> fix: Menu alignment

app/utils/opendata.spec.ts, app/utils/opendata.ts
Fixes #1656
1. Go to [this link](https://visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-1029%2Fcube%2F2024-1&dataSource=Prod).
2. Click the `OpenData.swiss` button in the left sidebar.
3. ❌ See that there's an error page displayed.
1. Go to [this link](https://visualization-tool-git-fix-opendata-link-ixt1.vercel.app/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22nfi%22%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_T-changes%2Fcube%2F2024-1&dataSource=Prod).
2. Click the `OpenData.swiss` button in the left sidebar.
3. ✅ See that the page opened with errors.
=> fix: ODS links when identifier already contains organization

CHANGELOG.md, app/charts/table/table-state.tsx, app/configurator/components/chart-controls/drag-and-drop-tab.tsx, app/configurator/components/filters.tsx, app/configurator/config-form.tsx
Fixes #1674
Fixes #1632
1. Go to [this link](https://visualization-tool-git-fix-column-side-panel-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod).
3. ✅ Look at the Columns section in the left panel and see that the drag handles are centered.
4. Click on the **Kanton** column.
5. Hide the column.
6. ✅ See that Zürich option is highlighted as selected and when clicking on the radio buttons, they are also correctly highlighted.
=> fix: Column chart issues

app/db/config.ts
Fixes #1686
In order to be able to delete a chart config, we need to first remove all related entries from the `config_view` table, to avoid foreign key constraint errors.
It will be possible to test the change on TEST once the PR is merged by logging in, creating a chart and removing it using the user profile table.
=> fix: Deleting saved charts

CHANGELOG.md, app/components/rename-dialog.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/profile-tables.tsx
Fixes #1634
This PR fixes a problem with chart titles not being retrieved in the user profile for single charts. The problem was that we used a nullish coalescing operator operator (`??`) instead of a regular or (`||`), when layout title was an empty string by default. This led to actual chart title not being even considered to be displayed.
I've also added new transition strings for "single" and "dashboard" texts in user profile, and fixed rename dialog in a way that now it:
- updates chart title in case of single charts,
- updates layout title in case of multi-charts.
This PR can be tested once merged and deployed to TEST by renaming a single chart.
=> fix: [ No title ] single charts

CHANGELOG.md, app/charts/shared/chart-data-filters.tsx, app/configurator/components/field-date-picker.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx, app/configurator/components/layout-configurator.tsx
Fixes #1689
This PR fixes manually entering the dates in date pickers fields.
1. Go to [this link](https://visualization-tool-git-fix-manually-entering-date-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Open Horizontal Axis.
3. Click on a `From` text field and manually change the year from 2014 to e.g. 2017.
4. ✅ See that the change was applied.
1. Go to [this link](https://visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Open Horizontal Axis.
3. Click on a `From` text field and manually change the year from 2014 to e.g. 2017.
4. ❌ See that the change was not applied.
=> fix: Manually entering dates

app/charts/line/lines-state.tsx, app/charts/map/chart-map.tsx, app/charts/shared/chart-data-filters.tsx, app/components/chart-published.tsx, app/configurator/configurator-state/reducer.tsx, app/rdf/query-hierarchies.ts, app/rdf/query-search.ts
This PR:
- fixes termsets fetching in the merging of datasets overlay,
- improves handling of merged cubes with map charts by not always taking the first cube to fetch geometries, but by looking at the cube containing the dimension and "unjoining" if needed.
In the next steps I will try to introduce `cubeIri` to chart config fields, so that we can distinguish cubes correctly in case we have dimension with the same iri across several cubes.
1. Go to [this link](https://visualization-tool-git-feat-merging-of-cubes-improvements-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd000504/8&dataSource=Prod).
2. Add a new data source.
3. Search for `photo`, choose the dataset and confirm.
4. Switch to a map chart.
5. ✅ See that it works.
1. Go to [this …
=> fix: Map charts with merged cubes & termsets fetching

app/charts/index.spec.ts, app/charts/index.ts, app/components/chart-selection-tabs.tsx, app/config-types.ts, app/configurator/components/add-dataset-dialog.mock.ts, app/configurator/components/annotation-options.tsx, app/configurator/components/configurator.tsx, app/configurator/components/field-i18n.ts, app/configurator/configurator-state/initial.tsx, app/configurator/configurator-state/mocks.ts, app/configurator/configurator-state/reducer.spec.tsx, app/docs/charts.stories.tsx, app/docs/columns.mock.ts, app/docs/fixtures.ts, app/docs/lines.mock.tsx, app/docs/lines.stories.tsx, app/docs/scatterplot.mock.ts, app/docs/tooltip.stories.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/utils/chart-config/versioning.ts
This PR introduces a `label` property to the `Meta` object both in chart configs and layout definitions. For now, it's only used in chart config to label chart tabs, but in the future could be extended to e.g.:
- label dashboard charts in the left panel in layouts different than tab layout,
- label dashboards to keep a "working name", instead of showing the full title in user profile.
1. Go to [this link](https://visualization-tool-git-feat-tab-labels-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. ✅ See that there's an `Add label` button in chart tab.
3. ✅ Click on it and see that you can edit the label.
4. Add a new chart.
5. Proceed to layout options.
6. ✅ See that it's no longer possible to …
=> feat: Add chart and dashboard labels

app/package.json
v3.0.0 has the same functionality
- fixes a specific issue with some SPARQL query engines
- performs equally
see perf results at https://rdataflow.github.io/speedtest-cubehierarchy/
@bprusinowski thanks for your review & merge
=> bump cube-hierarchy-query to v3.0.0

CHANGELOG.md, app/components/chart-footnotes.tsx, app/components/chart-selection-tabs.tsx, app/components/confirmation-dialog.tsx, app/components/menu-action-item.tsx, app/components/metadata-panel-store.tsx, app/components/metadata-panel.tsx, app/components/react-grid.tsx, app/configurator/components/add-dataset-dialog.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/login-menu.tsx, app/login/components/profile-tables.tsx, package.json
This PR:
- (merging of cubes) removes dimension selection from merging of cubes modal,
- (login) adds time to last edit date in user profile,
- (login) adds a new login popover menu when clicking on logged user name,
- (dashboard) adds a new, 3-column layout to free canvas dashboard,
- (general) updates styles and closing behavior of confirmation dialog.
Changes marked with (login) can only be tested on TEST after merging the PR.
To test other changes, go to [this link](https://visualization-tool-git-feat-improvements-2-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod&flag__debug=true) and try to:
- add a chart and remove it to see new dialog design,
- add a new dataset to see removed dimension …
=> feat: General improvements

CHANGELOG.md, app/charts/shared/use-combined-temporal-dimension.ts, app/components/dashboard-interactive-filters.tsx, app/configurator/components/layout-configurator.tsx
Fixes #1617
This PR fixes a problem of wrong positioning of marks in `DashboardTimeRangeSlider`. Due to the conversion of dates to milliseconds, and interpolation of values between min and max dates, there were some non-obvious issues with marks positioning. To see one such issue, see [this link](https://test.visualize.admin.ch/en/v/ZJSPzC4KHBvM?dataSource=Prod) from TEST and slide through the slider values – see that 2022 and 2023 and extra-close to each other, while they should have the same spacing as previous years.
To fix this issue, I changed the Slider's behavior from continuous to discrete, passing the values that actually appear in the data. It also makes sure that we use combined values from merged date dimension.
1. Go to [this …
=> fix: DashboardTimeRangeSlider

README.md, app/.env.development, app/login/components/login-menu.tsx, app/pages/api/auth/[...nextauth].ts
Fixes #1691
This PR fires a request to eIAM servers when user signs out, to also terminate the session on their side.
As we can't connect to eIAM infrastructure from localhost, I wasn't able to test out if this works – we would be able to do so when the change is deployed to TEST.
It would be extremely helpful to be able to connect to e.g. TEST eIAM auth server to work on such issues. @adintegra @ptbrowne do you know if we have such access, maybe I missed this? If not, could we potentially request it?
=> fix: Server-side eIAM session termination

app/components/chart-panel-layout-tall.module.css, app/components/chart-panel-layout-tall.tsx, app/components/chart-panel.tsx, app/components/chart-shared.tsx, app/configurator/components/preview-breakpoint.tsx, app/jest.config.js
This PR:
- fixes https://github.com/visualize-admin/visualization-tool/pull/1724#issuecomment-2334360578 by using container queries,
- adjusts width of smallest preview breakpoint from `sm` (768px) to 480px,
- fixes an overflowing issue with previewing / resizing the window in the Tall layout.
=> feat: Improve chart sizes preview

app/charts/shared/containers.tsx, app/charts/table/chart-table.tsx, app/charts/table/table.tsx, app/components/chart-panel-layout-grid.tsx, app/components/chart-preview.tsx, app/components/chart-selection-tabs.tsx, app/components/react-grid.stories.tsx, app/components/react-grid.tsx, app/configurator/components/annotators.tsx, app/configurator/components/field-i18n.ts, app/configurator/components/preview-breakpoint.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/package.json, yarn.lock
Fixes #1732
This PR:
- fixes some issues with tab labels in layouting step,
- fixes computations of minimal height of free canvas when adding a new chart to an existing layout,
- increases minimal height of free canvas chart from 100 to 150 pixels, which should help with wrong initializations in some cases,
- improves Table appearance in free canvas layout (correct initial sizing and non-overflowing content).
There's still a potential to improve the table chart in free canvas further, as it looks that compact view doesn't work as expected in small sizes and scrollbar position doesn't seem right, but this can be done in another PR, as it seems like a table issue, and not free canvas-related problem.
1. Go to [this link](https://visualization-tool-git-fix-minimum-dashboard-chart-sizes-ixt1.v …
=> fix: Minimum dashboard chart sizes

CHANGELOG.md, app/components/chart-panel-layout-grid.tsx, app/components/chart-preview.tsx, app/components/react-grid.tsx, app/config-types.ts, app/configurator/components/configurator.tsx, app/configurator/components/layout-configurator.tsx, app/configurator/components/layout.tsx, app/configurator/components/preview-breakpoint.tsx, app/configurator/components/show-drawer-button.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/utils/chart-config/versioning.ts
Closes #1739
This PR:
- saves the changes made while previewing free canvas layout in different breakpoints, and keeps the layouts separate for each breakpoint (`xl`, `lg`, `md`, `sm`),
- makes the preview mode size reflect the true size of the breakpoint, making the area horizontally scrollable when the screen size if lower than the breakpoint that's being previewed,
- adds a new preview breakpoint (`xl`) and aligns all of them with free canvas layout breakpoints.
1. Go to [this link](https://visualization-tool-git-feat-allow-editing-free-canv-12397f-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Add two new charts.
3. Proceed to layout options.
4. ✅ See that there are four options in the …
=> feat: Allow editing free canvas in preview mode

CHANGELOG.md, app/charts/area/areas-state-props.ts, app/charts/column/columns-grouped-state-props.ts, app/charts/column/columns-stacked-state-props.ts, app/charts/column/columns-state-props.ts, app/charts/combo/combo-line-column-state-props.ts, app/charts/combo/combo-line-dual-state-props.ts, app/charts/combo/combo-line-single-state-props.ts, app/charts/line/lines-state-props.ts, app/charts/map/map-state-props.ts, app/charts/pie/pie-state-props.ts, app/charts/scatterplot/scatterplot-state-props.ts, app/charts/shared/chart-state.ts, app/charts/table/table-state-props.ts
Fixes https://github.com/visualize-admin/visualization-tool/issues/1669#issuecomment-2373370535
1. Go to [this link](https://test.visualize.admin.ch/en/v/46J-ffwMimrI?dataSource=Prod).
2. ❌ See that using a shared time filter breaks the first chart.
1. Go to [this link](https://visualization-tool-git-fix-shared-time-filters-data-c8c019-ixt1.vercel.app/en/v/_FWl8l-02fkr?dataSource=Prod).
2. ✅ See that using a shared time filter doesn't break the first chart.
=> fix: Shared time slider in case of multiple cubes with and without temporal dimensions

app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/profile-tables.tsx
- `Copy` -> `Duplicate`
- Removed `Share` button, as it's the same as primary, "View" action, until we clarify the behavior proposed in #1758.
cc @sosiology
=> feat: Smaller login improvements

CHANGELOG.md, app/charts/line/lines.tsx
Fixes #1743
1. Go to [this link](https://test.visualize.admin.ch/v/yK9n8dvm0Lya?dataSource=Test-uncached).
2. ❌ See that whiskers are all blue, making it hard to distinguish to which line they belong.
1. Go to [this link](https://visualization-tool-git-fix-error-whisker-colors-ixt1.vercel.app/en/v/_3Ekb3oeeRdu?dataSource=Test).
2. ✅ See that whiskers take color from the line they belong to.
=> fix: Segmented line chart whisker colors

app/components/chart-preview.tsx, app/configurator/configurator-state/reducer.tsx
Closes #1769
This PR allows duplication of charts in the layouting step. What still could be improved is to maintain the size of the duplicated chart in the layout mode, now it initializes in "initial" size and adjusts the height like a new chart.
See #1769
1. Go to [this link](https://visualization-tool-git-fix-duplicating-charts-in-la-b0c5bf-ixt1.vercel.app/en/create/new?copy=4WaHLAUCWEq-).
2. Proceed to layout options.
3. ✅ See that it's possible to duplicate charts using any layout.
=> fix: Allow duplication of charts in layouting step

CHANGELOG.md, app/rdf/queries.ts
Closes #1775
This PR adds pragmas to SPARQL query button. They were used in the application, as they are appended automatically through `sparqlClient`, but here we needed to explicitly add them.
1. Go to [this link](https://test.visualize.admin.ch/en/v/sR3dVqbrEZHE?dataSource=Prod).
2. Open Details panel.
3. Click on SPARQL query button.
4. ❌ See that the query fails to fetch the data.
1. Go to [this link](https://visualization-tool-git-perf-sparql-query-button-pragmas-ixt1.vercel.app/en/v/5P82vNyimdaa?dataSource=Prod).
2. Open Details panel.
3. Click on SPARQL query button.
4. ✅ See that the query successfully fetches the data.
=> perf: Add pragmas to SPARQL query button

CHANGELOG.md, app/pages/statistics.tsx
This PR adds:
- most popular charts (all time),
- most popular charts (last 30 days),
to the `Statistics` page.
1. Go to [this link](https://visualization-tool-git-feat-improve-statistics-page-ixt1.vercel.app/statistics).
2. ✅ See that there are two new cards, showcasing most popular charts (all time and in last 30 days).
=> feat: Add most popular charts to Statistics page

CHANGELOG.md, app/components/arrow-menu.tsx, app/components/row-actions.tsx, app/components/use-flip-menu.tsx
Fixes #1773
This PR adds a `useFlipMenu` hook with logic to automatically position `Menu` component, depending on its top / bottom position on the screen.
1. Go to [this link](https://test.visualize.admin.ch/en).
2. Log in.
3. Go to `My visualizations`.
4. Click on an action button close to the bottom of the screen.
5. ❌ See that it's rendered in the middle, overlapping the button, with arrow not being correctly positioned (in the screenshot below, I clicked on the last row's button).
Once the PR is deployed to TEST, it will be possible to test using the above instructions, and the result should look like below. Clicking on top items should still display the component in its default, top-to-bottom state.
=> fix: Misaligned Menu in login profile table on smaller screens

CHANGELOG.md, app/components/chart-shared.tsx
=> feat: Make the Delete action consistently the last one

CHANGELOG.md, app/charts/table/table-content.tsx, app/charts/table/table-state.tsx, app/charts/table/table.tsx
Fixes #1792
Fixes #1790 
1. Go to [this link](https://visualization-tool-git-fix-table-height-ixt1.vercel.app/en/create/new?cube=https://health.ld.admin.ch/fsvo/BT_table/17&dataSource=Prod).
3. ✅ See that the content is not cut.
4. Publish the chart.
5. ✅ See that the table is not cut there either.
6. Reduce the browser window width to activate the compact view option.
7. ✅ Enable the compact view option, scroll down and see that the content is not cut.
8. Repeat the above steps for another cube, e.g. Photovoltaikanlagen, to see that long tables are also not cut. You can also disable the search box from table settings to see that this doesn't make the table cut as well.
=> fix: Table height

app/components/footer.tsx, app/components/publish-actions.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Let know if this is works technically @bprusinowski, unfortunately I had difficulties spotting the border in the first place. Once the technically side is clear I will tag Kerstin to Review the design. - Currently don't know how to test exactly because I haven't seen a border in the first place...
1. This PR allows the users to remove the border during Embed Selection 
2. This PR tackles the issue #1809 
---
1. Go to this [link](https://visualize.admin.ch) 
2. See how in the footer there is the id of the last commit ❌
4. Click on the Link get navigated to last commit ❌ 
1. Go to this [link](https://visualization-tool-c62th0teo-ixt1.vercel.app)
2. See how in the footer it now says "Change Log" translated in all languages ✅
3. Click on the link get navigated to the Change log ✅
1. Go to …
=> Complete smaller enhancements

app/components/chart-preview.tsx, app/components/chart-published.tsx
This PR fixes Issue #1813 
1. Go to this [Link](https://visualization-tool-azw7yjcr8-ixt1.vercel.app) 
2. Publish, a tab layout see how "Created with..." is visible ✅
3. Publish a Dashboard Layout with 1 Chart see how "Created with..." is in the Chart ✅
4. Publish a Dashboard Layout with more than 1 Chart see how the "Created with..." is only at the bottom of the layout ✅
=> fix: Added Links for all Charts in Preview & Published Mode

app/charts/area/areas-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/combo/combo-line-column-state.tsx, app/charts/combo/combo-line-dual-state.tsx, app/charts/combo/combo-line-single-state.tsx, app/charts/line/lines-state.tsx, app/charts/pie/pie.tsx, app/charts/pie/rendering-utils.ts, app/charts/scatterplot/chart-scatterplot.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/interaction/ruler.tsx, app/charts/shared/interaction/tooltip-box.tsx, app/utils/use-is-mobile.ts
@bprusinowski please check if this is the correct approach, if so I will continue implementing this for all charts and for tooltips that are larger the arrow will have to be more dynamic of course.
This PR: 
- Fixes Mobile Tooltip for all Chart except (Pie Charts, Scatterplot Charts, Map Charts)
- The exceptions still need design criteria, @KerstinFaye 
- This PR also uncovered a new Issue [#110](https://github.com/visualize-admin/visualization-tool-private/issues/110)
- This PR is the start to fix Issue [#94](https://github.com/visualize-admin/visualization-tool-private/issues/94)
This PR will resolve #94
---
1. Go to this [Visit Preview](https://vercel.live/open-feedback/visualization-tool-git-fix-mobile-tooltip-positioning-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) …
=> fix: Fixed tooltip for Mobile Area Charts

.github/dependabot.yml
dependabot will create PR once new versions of GH actions become available, so no need for manual updates anymore ;-)
see dependabot docs at https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide
See also: https://github.com/visualize-admin/visualization-tool/issues/1820
=> automated pr to maintain dependencies for github actions

app/components/publish-actions.tsx, app/pages/v/[chartId].tsx
**This PR:** 
- This PR tackles the request from @sosiology to only allow border removable for single Charts
- Resolves #1794 
1. Go to this [Link](https://vercel.live/open-feedback/visualization-tool-git-feat-border-embed-layouts-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)
2. Create a Visualization 
3. Publish a Single Chart, See how "remove border toggle" is available ✅
4. Publish multiple Charts, See how "remove border toggle" is no available ✅
CC: @KerstinFaye
=> feat: Restricted Toggle to single Charts only

app/components/publish-actions.tsx, app/login/components/profile-tables.tsx
**This PR:** 
- This PR adds the possibility for embedding and sharing on the user profile page e
- This PR resolves #1758 
**Review Hints**
@bprusinowski I am not 100% certain if this is the best way of implementing it. It heavily depends on custom positioning, because the anchor element by itself would not detect the position correctly and place it at the top left of the screen.
- Perhaps there is a better place also to put the `adjustPopoverPosition`.
---
1. This feature can only be tested on Prod
2. Go to User Profile
3. Click the 3 dots for more on a Published Chart 
4. See that there is a Share button✅ 
5. See that there is a Embed button ✅ 
6. On click of either of those buttons, see how the same popup from the "Published Page" popup ✅ 
---
<details>
<summary><strong>Images from my …
=> feat: Implement Share and Embed on Profile Page

app/components/publish-actions.tsx, app/login/components/profile-tables.tsx
**This PR:**
- This PR prevents users from making removed border charts for tab layout. 
- This PR does not yet allow removed border charts on the user profile 
- This PR resolves #1892 
1. Go to this [link](https://vercel.live/open-feedback/visualization-tool-git-fix-embed-remove-border-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 
2. Create a new Chart 
3. Add a second Chart and proceed to layout selection 
4. Select Tab layout and publish the Charts
5. Try to Embed the chart and see how the "Remove Border" option is gone ✅
6. Once deployed you can also test this on the user "Visualizations" page ✅
---
CC: @sosiology , @KerstinFaye
=> fix: Changed EmbedContent to detect chart layout type changes

CHANGELOG.md, app/browser/dataset-browse.tsx, app/charts/index.spec.ts, app/charts/index.ts, app/components/form.tsx, app/components/graphql-search.stories.tsx, app/components/info-icon-tooltip.tsx, app/components/metadata-panel.tsx, app/config-types.ts, app/configurator/components/add-dataset-dialog.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/configurator.tsx, app/configurator/components/dataset-control-section.tsx, app/configurator/components/field.tsx, app/configurator/config-form.tsx, app/configurator/configurator-state/actions.tsx, app/configurator/configurator-state/reducer.tsx, app/configurator/interactive-filters/time-slider.tsx, app/domain/data.ts, app/graphql/join.ts, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, e2e/actions.ts, e2e/selectors.ts
Closes #1830
This PR:
- removes termsets from merging of cubes modal dropdown,
- renames "Contains values from" to "Join by" when hovering over a shared dimension tag in merging of cubes modal,
- prefers dual-line and column-line chart before multi-line chart and tries to initialize the dual-line chart with measures from different charts, if other conditions are met (e.g. that dimensions have different units),
- adds an info tooltip to explain what `Concepts` are on the browse page,
- groups filters and dropdown options by cube, in case we have more than one.
1. Go to [this link](https://visualization-tool-git-feat-merging-of-cubes-ui-imp-b426b5-ixt1.vercel.app/en/browse?dataSource=Prod).
2. ✅ Scroll a bit down to see that there's an icon tooltip next to `Concepts` navigation menu.
3. …
=> feat: Merging of cubes UI improvements

CHANGELOG.md, app/browse/datatable.tsx, app/charts/index.spec.ts, app/charts/index.ts, app/charts/shared/legend-color.tsx, app/components/form.tsx, app/components/info-icon-tooltip.tsx, app/components/maybe-tooltip.tsx, app/components/tooltip-utils.tsx, app/configurator/components/add-dataset-dialog.tsx, app/configurator/components/chart-controls/control-tab.tsx, app/configurator/components/chart-controls/section.tsx, app/configurator/components/chart-options-selector.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/components/dataset-control-section.tsx, app/configurator/components/filters.tsx, app/configurator/configurator-state/index.spec.tsx, app/configurator/configurator-state/init.tsx, app/configurator/configurator-state/reducer.spec.tsx, app/configurator/configurator-state/reducer.tsx, app/configurator/interactive-filters/interactive-filters-configurator.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #1448
This PR adds tooltip that explains why a given chart type can be selected and consolidates the tooltips used across the editor mode (excluding chart tooltips).
1. Go to [this link](https://visualization-tool-git-feat-tooltip-for-disabled-ch-9b046b-ixt1.vercel.app/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Month&dataSource=Prod).
2. ✅ Hover over disabled chart types and see that a tooltip with explanation on why it can't be selected is shown.
@KerstinFaye UI strings can be adjusted via Accent (string ids start with `controls.chart.disabled`), I used the most down-to-code explanations, but maybe they can be tweaked :)
=> feat: Tooltip for disabled chart types

CHANGELOG.md, app/configurator/components/add-dataset-dialog.tsx, app/configurator/components/dataset-control-section.tsx
**This PR:**
- This PR Removes the Beta Tag from the Datasets section 
- This PR resolves #1884 
1. Go to this [Link](https://vercel.live/open-feedback/visualization-tool-git-feat-remove-beta-tag-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 
2. Select a Dataset for a visualization 
3. See how the beta Tag from the Datasets Section is removed
---
CC: @sosiology , @KerstinFaye
=> feat: removed beta tag

CHANGELOG.md, app/components/data-download.tsx, app/formatters.ts
This PR: 
- This PR ensures that downloaded data files format `undefined` and `null` to `"-"` instead of `"0"`
- -
- This PR resolves #1888 
1. Go to this [link](https://www.visualize.admin.ch/de/v/-u-BR-bpgybi)
2. Create a visualization w/ this Data => `LFI: Themen nach Baumart (5 Klassen)`
3. Publish Visualization 
4. Click on Dataset in the bottom left corner 
5. Click on Download data 
6. Click CSV 
7. Scroll through the file see how there are a bunch of zeros ❌
_repeat steps 1 - 6 with this [link](https://visualization-tool-git-fix-zero-for-undefined-values-ixt1.vercel.app/)_ 
8. See how some of the zeros, were actually undefined values now they are replaced with `"-" `dashes ✅
---
CC: @sosiology
=> fix: undefined and null values get replaced w/ "-"

app/charts/shared/chart-state.ts, app/rdf/light-cube.ts, app/rdf/query-termsets.ts
This PR:
- improves confidence intervals formatting based on @sosiology's [comment](https://github.com/visualize-admin/visualization-tool/pull/1910#issuecomment-2498778455),
- removes some unused code.
1. Go to [this link](https://visualization-tool-git-feat-confidence-intervals-fo-e6757e-ixt1.vercel.app/en/create/new?cube=https://mock.ld.admin.ch/cube/mock-two-sided/1&dataSource=Test).
2. ✅ Hover over bars and see that errors are formatted in `, [-x, +y]` way.
=> feat: Improve confidence intervals formatting

CHANGELOG.md, app/browser/dataset-browse.tsx, app/components/form.tsx, app/configurator/components/add-dataset-dialog.tsx, app/configurator/components/layout-configurator.tsx
This PR aligns the add dataset dialog search controls with the design (with one change to also include draft datasets toggle).
1. Go to [this link](https://visualization-tool-git-feat-improve-add-dataset-dia-1fc1e3-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Clink on `Add dataset`.
3. ✅ See that the design of the search controls is aligned with [the Figma file](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=4417-131083&t=rM5yJXUP5EDdPaUa-4).
4. ✅ See that it's possible to sort the results and enable draft datasets.
=> feat: Improve search options for add dataset dialog

CHANGELOG.md, app/charts/combo/axis-height-linear-dual.tsx, app/charts/combo/combo-line-dual-state.tsx, app/utils/use-axis-title-adjustments.ts
**This PR:** 
- This PR increase yAdjustment for axis Titles, like this they stop overlapping 
- This PR resolves #1878 
1. Go to this [link](https://visualization-tool-git-fix-minor-bugs-ixt1.vercel.app/) 
2. Search Photo and Select (Einmalvergütung für Photovoltaikanlagen) Dataset
3. Select a Combo Chart type 
4. Select the longest titles for but indicators 
5. Publish the Chart resize your screen up to 350px
6. See how the Titles never overlap ✅
---
CC: @sosiology
=> fix: increased yAdjustment for axis labels

CHANGELOG.md, app/pages/_preview.tsx, app/pages/preview.tsx, e2e/preview-via-api.spec.ts
Fixes #1941
This PR fixes broken chart preview via API (iframe version) and adds an E2E test so we can avoid such regression going forward.
1. Go to [this link](https://visualization-tool-git-fix-preview-via-api-iframe-ixt1.vercel.app/_preview).
2. ✅ See that the chart loads.
1. Go to [this link](https://int.visualize.admin.ch/_preview).
2. ❌ See that the chart doesn't load.
=> fix: Preview via API (iframe)

CHANGELOG.md, app/charts/shared/containers.tsx
Fixes #1939
This PR fixes some chart container sizing issues by:
- re-mounting the container when chart type changes, which fixes errors most noticeable in bar charts, which were scrollable when not needed (due to taking an old height value from the old, mounted container),
- uses flex display for chart container, which makes the table chart correctly take up 100% of the remaining parent container, not 100% of the parent container, which was resulting in cut scrollbars and double scroll.
1. Go to [this link](https://visualization-tool-git-fix-chart-sizing-ixt1.vercel.app/en/create/new?cube=https://health.ld.admin.ch/fsvo/Lebensmittelkontrolle_Steckbriefe_Table/21&dataSource=Int).
3. ✅ See that the _Total number of lines: 389_ note is visible in the right bottom …
=> fix: Chart sizing

CHANGELOG.md, app/login/components/profile-content-tabs.tsx, app/login/utils.ts, app/pages/profile.tsx
**This PR**
- fixes #1688
**Description**
This PR adds the Footer to the Profile Page
=> feat: Added Footer to Profile Page

CHANGELOG.md, app/charts/map/map-state.tsx
**This PR**
- fixes #480 
**Description**
Values that are null, undefined or 0 will be not displayed and values that are very small will be scaled up slightly. In the future it might make sense to display null, undefined and 0 visibly in some form.
=> fix: Changed map radiusScale for increased size for small values

CHANGELOG.md, app/components/chart-footnotes.tsx
Closes https://github.com/visualize-admin/visualization-tool/issues/1928#issuecomment-2577355736
This PR makes sure we only have one "Created with visualize.admin.ch" footnote when making a screenshot of a published chart.
1. Go to [this link](https://visualization-tool-git-fix-double-made-with-visuali-e7a011-ixt1.vercel.app/en/v/FwN1UJUrMywH?dataSource=Prod).
2. Download an image of the chart.
3. ✅ See that the "Created with visualize.admin.ch" footnote is only there once.
1. Go to [this link](https://test.visualize.admin.ch/en/v/Md9KZ3H4AipE?dataSource=Prod).
2. Download an image of the chart.
3. ❌ See that the "Created with visualize.admin.ch" footnote is there twice.
cc @sosiology
=> fix: Double visualize.admin.ch footnote in published chart image downloads

CHANGELOG.md, app/configurator/components/field-date-picker.tsx
Fixes #1689
This PR makes entering the dates manually via text input work correctly again in date picker fields. Not sure why, but the `onChange` callback was set to an empty function, which prevented this behavior from working properly.
1. Go to [this link](https://visualization-tool-git-fix-manual-date-entry-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd01041prod/4&dataSource=Prod).
2. Select `Horizontal axis`.
3. ✅ Enter 10.05.2016 in the `From` input field and see that it works.
Check https://github.com/visualize-admin/visualization-tool/issues/1689#issuecomment-2577567527.
=> fix: Entering dates via text input in DatePickerField

CHANGELOG.md, app/configurator/components/filters.tsx, app/themes/federal.tsx, app/utils/time-filter-options.spec.ts, app/utils/time-filter-options.tsx
This PR fixes #1963
1. Go to [this link](https://visualization-tool-git-fix-timezone-parsing-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1&dataSource=Prod).
3. Open `Active since` field.
4. ✅ See that the application didn't crash.
Follow the steps from #1963.
=> fix: Opening temporal timezone dimension table field

CHANGELOG.md, app/utils/use-screenshot.ts, e2e/chart-actions.spec.ts
Closes #1969
This PR makes sure we screenshot whole charts, not only visible parts (currently applicable to scrollable bar charts).
1. Go to [this link](https://visualization-tool-git-feat-screenshot-whole-svgs-ixt1.vercel.app/en/v/6_FlCR1TC3ve?dataSource=Prod).
2. Export PNG image of the chart.
3. ✅ See that the whole chart was included in the screenshot.
1. Go to [this link](https://test.visualize.admin.ch/en/v/nuUuhNIiBjeq?dataSource=Prod).
4. Export PNG image of the chart.
5. ❌ See that only the visible was included in the screenshot.
=> feat: Make sure we screenshot the whole chart

CHANGELOG.md, app/package.json, app/pages/_preview.tsx, app/pages/preview_post.tsx, app/test/__fixtures/config/prod/map-1.json, app/utils/chart-config/versioning.spec.ts, app/utils/chart-config/versioning.ts, e2e/preview-via-api.spec.ts, yarn.lock
Fixes #1941
This PR:
- fixes chart config migrations for maps (correctly migrates `palette` to `paletteId`),
- adds a map chart to `_preview` page,
- adds a `decodeConfiguratorState` call in POST preview.
See the comments from #1941.
1. Go to [this link](https://visualization-tool-git-fix-config-migrations-ixt1.vercel.app/_preview).
2. ✅ See that two charts loaded (column and map) – map being the chart from #1941 that is currently broken on INT.
=> fix: Configurator state migrations

CHANGELOG.md, app/gql-flamegraph/devtool.tsx, app/gql-flamegraph/resolvers.ts, app/graphql/resolvers/index.ts, app/pages/api/graphql.ts, e2e/debug-panel.spec.ts
Fixes #1973
This PR:
- decorates the resolvers immediately, so that the query times can be traced like when we used them directly, before switching to using [`schema`](https://github.com/visualize-admin/visualization-tool/blob/31c98836c0508471919c72d454cae51886f846ae/app/pages/api/graphql.ts#L27-L33),
- adds an end-to-end test for GQL Flamegraph.
See https://github.com/visualize-admin/visualization-tool/issues/1973.
1. Go to [this link](https://visualization-tool-git-fix-graphql-debug-flamegraph-ixt1.vercel.app/en?flag__debug=true).
2. Click on a 🛠 emoji in the right bottom corner.
3. ✅ See that the queries are tracked.
=> fix: GraphQL Flamegraph

app/next.config.js
This pull request includes updates to the Content Security Policy (CSP) in the `app/next.config.js` file to enhance security and functionality. The most important changes involve adding new sources for styles, images, scripts, and connections.
Updates to Content Security Policy:
* Added `https://fonts.googleapis.com` and `https://cdn.jsdelivr.net` to the `style-src` directive to allow loading styles from these sources.
* Added `https://api.mapbox.com` and `https://api.maptiler.com` to the `connect-src` directive to allow connections to these APIs.
* Added `https://cdn.jsdelivr.net` to the `img-src` directive to allow loading images from this source.
* Added `https://cdn.jsdelivr.net` to the `script-src-elem` directive to allow loading scripts from this source.
See #1988.
**Note**: …
=> Additional CSP policies

CHANGELOG.md, app/components/markdown.tsx, app/configurator/components/chart-type-selector.tsx, app/configurator/components/field.tsx, app/configurator/components/layout-configurator.tsx, app/flags/flag.tsx, app/flags/local-storage-adapter.ts, app/flags/store.ts, app/flags/types.ts, app/flags/useFlag.ts, app/gql-flamegraph/devtool.tsx, e2e/chart-actions.spec.ts
This PR:
- automatically removes depreciated flags from user's local storage,
- hides dashboard text blocks, Markdown editor and bar charts behind an `enable-experimental-features` flag.
1. Go to [this link](https://visualization-tool-git-feat-flags-ixt1.vercel.app/en).
2. ✅ See that no bar chart is available to be selected in the left panel.
3. ✅ See that no bar chart is available to be selected in the add new chart button.
4. ✅ Check chart's title and description and see the old input field (without Markdown UI buttons).
5. Add a new chart and proceed to layout options.
6. Switch to a dashboard layout.
7. ✅ See that `Objects` are not available to be added.
8. Add `&flag__enable-experimental-features=true` to the end of the URL and hit Enter.
9. ✅ Re-do the above steps and see that …
=> feat: Hide new features behind flags + remove depreciated flags automatically

CHANGELOG.md, app/charts/shared/interaction/tooltip-box.tsx, app/charts/shared/interaction/tooltip.tsx, e2e/tooltip.spec.ts
Closes #1978
This PR changes the behavior of `usePosition` hook to re-calculate tooltip's position on `y` coordinate change. Previously we were returning early when bounding client rect was already set, which led to using outdated coordinates when scrolling.
1. Go to [this link](https://visualization-tool-git-fix-tooltip-scroll-ixt1.vercel.app/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Month&dataSource=Prod&flag__enable-experimental-features=true).
2. Switch to a bar chart.
3. ✅ Hover over the chart, scroll and see that the tooltip correctly positions itself after the scrolling event.
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Mont …
=> fix: Bar chart tooltip scroll

CHANGELOG.md, app/charts/index.ts, app/pages/preview.tsx, app/pages/preview_post.tsx, app/utils/chart-config/versioning.spec.ts, app/utils/chart-config/versioning.ts
This PR:
- fixes `/preview` page to not try to load invalid data to the iframe,
- correctly adds PUBLISHED state before trying to decode configurator state in `/preview` and `/preview_post` pages,
- fixes two edge cases in configurator state migrations.
1. Go to [this link](https://visualization-tool-git-fix-invalid-states-api-preview-ixt1.vercel.app/_preview).
2. Open debug console.
3. ✅ See that the errors about "data.version" are not there.
1. Go to [this link](https://test.visualize.admin.ch/_preview).
2. Open debug console.
3. ❌ See that the errors about "data.version" are there.
---
=> fix: API preview and configurator state migrations

CHANGELOG.md, app/configurator/components/filters.spec.ts, app/configurator/components/filters.tsx
Closes #2000
This PR fixes the `Selected values` display by setting `hasColorMapping` to false in case of `SingleColorField`s.
1. Go to [this link](https://visualization-tool-git-fix-color-mapping-detection-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Open `Horizontal Axis` field.
3. Switch the measure to `Kanton`.
4. See that Selected values are correctly displayed.
See instructions in #2000.
---
=> fix: Selected values display

CHANGELOG.md, app/charts/pie/pie-state.tsx, app/charts/pie/rendering-utils.ts, app/charts/shared/interaction/tooltip-box.tsx, app/charts/shared/interaction/tooltip-content.tsx, app/charts/shared/interaction/tooltip.tsx
Closes #1916
This PR:
- allows chart tooltip to wrap in case of long text, constraining it to the container its in,
- makes pie chart tooltip always positioned on top of the chart, closer to it than before, which should decrease a chance of going off the screen when in iframe embed mode,
- simplifies some code and uses correct chart state types in `TooltipInner` component.
1. Go to [this link](https://seleniumbase.io/w3schools/iframes).
2. Remove all content and paste the following instead.
```html
<!DOCTYPE html>
<html>
<body>
<h2>HTML Iframes (nested iframes)</h2>
<p>Use CSS width & height to specify the iframe size:</p>
<iframe src="https://visualization-tool-git-fix-tooltip-issues-ixt1.vercel.app/en/embed/Q48H8AbY6OU_" width="500px" style="height: 1183px; border: 0px #ffffff none;" …
```
=> fix: Chart tooltip issues

CHANGELOG.md, app/components/chart-shared.tsx
Closes #2007
Closes #2023
This PR brings back interactive legend colors and uses a correct font family styles for "Created with visualize.admin.ch" footnote in PNG image downloads.
1. Go to [this link](https://visualization-tool-git-fix-interactive-filter-colors-png-ixt1.vercel.app/en/v/k3xovfSAmIjQ?dataSource=Prod).
2. Export a PNG image.
3. ✅ See that the interactive legend colors are persisted and the "Created with visualize.admin.ch" font style is the same as above footnotes.
1. Go to [this link](https://test.visualize.admin.ch/en/v/BNvRsJwgC70E?dataSource=Prod).
2. Export a PNG image.
3. ❌ See that the interactive legend colors are not persisted and the "Created with visualize.admin.ch" font style is not the same as above footnotes.
---
=> fix: PNG download colors and fonts

CHANGELOG.md, app/charts/shared/containers.tsx
Closes #2022
This PR changes the CSS overflow property from "scroll" to "auto" to not show scroll bars when not necessary.
1. If you are using MacOS, go to your operating system settings → `Appearance` → `Show scroll bars` → `Always`.
2. Go to [this link](https://visualization-tool-git-fix-scrollbars-ixt1.vercel.app/en/v/31mPAoyVKxB_?dataSource=Prod).
3. ✅ See that there are no scroll bars inside the chart itself.
See instructions in #2022.
---
=> fix: Do not show scroll bars when not needed

CHANGELOG.md, app/charts/scatterplot/scatterplot-state.tsx
Closes [#2002](https://github.com/visualize-admin/visualization-tool/issues/2002)
Adjusts the margin so that the chart no longer overlaps the label
1. Go to [this link](https://visualization-tool-git-fix-scaterplot-overlap-ixt1.vercel.app/en/create/yT1_R3J0aGr2?dataSource=Prod)
2. switch to scatterplot chart
3. notice the label no longer overlaps
---
=> Fix scatterplot overlap

CHANGELOG.md, app/components/form.tsx
Closes #2010
This PR removes the `multiline` property from Input so that it does not extend when hitting Enter. This change was introduced while working on the dashboard text blocks, but as we switched to using a third-party library for Markdown inputs, this should have been removed.
1. Go to [this link](https://visualization-tool-git-fix-multiline-input-ixt1.vercel.app/en/v/Oa9u2jQOjAtr?dataSource=Prod).
2. Enter some text in the search bar above the table and hit Enter.
3. ✅ See that the input field doesn't extend.
See the instructions in #2010.
---
=> fix: Disable multiline Input

CHANGELOG.md, app/configurator/components/layout-configurator.tsx, app/rdf/mappings.ts, e2e/dashboards.spec.ts, e2e/filter-position.spec.ts
Closes #2013
This PR fixes a week-based temporal dimensions parsing in dashboard shared filters.
1. Go to [this link](https://visualization-tool-git-fix-week-dates-global-filter-ixt1.vercel.app/en/create/new?cube=https://health.ld.admin.ch/fsvo/Moderhinke_Untersuchungsperiode_2024_2025/10&dataSource=Prod).
2. Add a second chart.
3. Proceed to layout options.
4. Enable `Date` shared filter.
5. ✅ See that the fields are filled in correctly.
6. ✅ See that you can interact with the date picker and the application doesn't break.
See instructions in #2013.
---
=> fix: Application crash when using shared weekly date filter

CHANGELOG.md, app/components/chart-panel.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-shared.tsx, app/test/__fixtures/config/prod/dashboard-tall.json, e2e/dashboard-date-filter.spec.ts, e2e/dashboard-tall-subgrid.spec.ts
Closes #2039
Closes #2042
This PR fixes chart area overflowing the available space in Chrome. While I was not able to narrow down the exact reason for the bug, we don't need a grid layout when in editing mode, as we always only look at one chart, so that should be safe to change anyways.
It also fixes tall layout dashboard in published mode (elements are correctly aligned between columns again).
#2039
1. Go to [this link](https://visualization-tool-git-fix-overflow-editing-mode-ixt1.vercel.app/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Month&dataSource=Prod) on Chrome.
2. Change chart type to pie, then table, and then area.
3. ✅ See that the chart area stays the same for all chart types.
#2042
1. Go to [this …
=> fix: Chart area overflowing when changing chart type

CHANGELOG.md, app/charts/combo/axis-height-linear-dual.tsx, app/charts/shared/axis-height-band.tsx, app/components/chart-shared.tsx
Closes #2045
This PR makes sure we keep correct colors in dual-axis charts' Y axis labels.
1. Go to [this link](https://visualization-tool-git-fix-dual-axis-colors-png-ixt1.vercel.app/en/v/wU3yCKqXSAJs?dataSource=Prod).
2. Download PNG image.
3. ✅ See that the Y axis labels have correct colors.
See #2045.
---
=> fix: Dual axis Y label colors in PNG download

CHANGELOG.md, app/charts/map/map-legend.tsx, app/charts/shared/containers.tsx, app/utils/use-screenshot.ts
Closes #2012
This PR:
- fixes map legend items overlap in PNG download,
- improves vertical spacing between map legend items.
1. Go to [this link](https://visualization-tool-git-fix-screenshot-overlaps-map-ixt1.vercel.app/en/v/B-kwpu3axtnI?dataSource=Prod).
2. Download a PNG image.
3. ✅ See that the map legend elements do not overlap.
See #2012.
---
=> fix: Map legend items overlap in PNG download

CHANGELOG.md, app/charts/bar/bars-grouped-state.tsx, app/charts/bar/bars-stacked-state.tsx, app/charts/bar/bars-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/axis-width-linear.tsx, app/charts/shared/brush/index.tsx, app/charts/shared/chart-dimensions.tsx, app/charts/shared/chart-state.ts
Closes [#2003](https://github.com/visualize-admin/visualization-tool/issues/2003)
This PR fixes a bug where the chart would crash when the interactive filter was selected on the y axis of a bar chart. The reason was that the computations necessary to make the brushes were not expecting a bar chart that has the axis flipped (when comparing to column charts). 
1. Go to a dataset
2. Select the Y axis
3. Toggle the interactive switch
4. Notice the chart works as intended
=> Fix interactive filter bar chart

CHANGELOG.md, app/components/chart-footnotes.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-shared.tsx
Closes #2031 
**What's new?**
This PR Now navigates users to the corresponding Chart when clicked on the "Created by visualize.admin.ch" section in the footer, like this users can benefit from quick chart creation & potentially starting out with a more established Chart.
1. Go to this Link
2. Create a new Visualisation 
3. Publish Visualisation 
4. Memorize last part of the URL (e.g `Xx3-xKHq9K2G`) -> this is necessary because we only support production charts
5. Click the "Created by visualize.admin.ch"
6. See how it navigates to the same Chart (See url) ✅
---
@bprusinowski please let me know if it makes sense here to make the URL dynamic or if I should keep it only for visualize.admin.ch, Vercel also has a URL called VERCEL_URL we could be using this for cases like these. Let me know …
=> Created by visualize link points to Chart

CHANGELOG.md, app/login/components/profile-content-tabs.tsx
Closes #1985
This PR removes the white bar in between header and navigation bar of the user profile page.
1. This feature can only be tested once merged.
1. Go to this [link](https://int.visualize.admin.ch/en)
2. Login 
3. See your profile with the white bar in between ❌
---
cc: @sosiology , @bprusinowski
=> style: changed to padding for backgroundColor

CHANGELOG.md, app/configurator/components/filters.tsx, app/configurator/config-form.tsx
Closes #1996 
**What changed?**
This PR ensures that selected filters have a color indication by correcting the color path that has changed during the implementation of custom color palettes. 
1. Go to this [link](https://visualization-tool-git-fix-boxes-without-color-ixt1.vercel.app/)
2. Select the following dataset `Market figures milk and dairy products - Monthly consumer prices`
3. Select `Segmentation` 
4. Select segmentation dimension `Product`
5. Click `Edit filters`
6. See how when selecting a value the box on the left changes color (Select all for easier confirmation) ✅
1. Go to this [link](https://int.visualize.admin.ch/en) 
2. Select the following dataset `Market figures milk and dairy products - Monthly consumer prices`
3. Select `Segmentation` 
4. Select segmentation …
=> feat: Added color change when selecting filters

CHANGELOG.md, app/configurator/components/chart-controls/color-palette.tsx
Closes #2033
This PR ensures that color shuffle and reset buttons work again and can shuffle colors with the custom color palette adaptation.
1. Go to this [Link](https://visualization-tool-git-fix-color-shuffling-ixt1.vercel.app/)
2. Select a dataset (e.g : Einmalvergütung für Photovoltaikanlagen)
3. Select `Segmentation`
4. Select Cantons as `dimension`
5. Click `Shuffle colors` , see how colors are shuffling ✅
6. Click `Reset color palette` , see how colors are being reseted ✅
2. Select a dataset (e.g : Einmalvergütung für Photovoltaikanlagen)
3. Select `Segmentation`
4. Select Cantons as `dimension`
5. Click `Shuffle colors` , see how colors aren't shuffling ❌
6. Click `Reset color palette` , see how colors …
=> fix: Fixed color shuffling by fixing field selection

CHANGELOG.md, app/charts/area/areas-state.tsx, app/charts/bar/bars-grouped-state.tsx, app/charts/bar/bars-stacked-state.tsx, app/charts/bar/bars-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/line/lines-state.tsx, app/charts/scatterplot/scatterplot-state.tsx, app/charts/shared/chart-dimensions.tsx, app/charts/shared/margins.ts
Closes #2040
This PR increases the margin between Y axis label and ticks for some charts and uses consistent margin for all of them.
1. Go to [this link](https://visualization-tool-git-feat-improve-y-axis-label-spacing-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Switch between line, area, column and bar charts.
3. ✅ See that the spacing between Y axis label and ticks is consistent and not so close as before in case of some chart types.
---
=> feat: Use consistent Y axis label margins between regular charts

CHANGELOG.md, e2e/varnish-cache-preload.ts
This PR increases the number of charts pre-loaded to the Varnish cache from 25 to 250, as the caching capabilities improved in the meantime.
---
cc @Rdataflow
=> chore: Increase the number of charts pre-loaded to Varnish cache

app/components/chart-panel.tsx, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/test/__fixtures/config/prod/dashboard-free-canvas.json, e2e/dashboard-free-canvas.spec.ts
Closes #2072
This PR makes sure we don't use `display: "contains"` for free canvas layout, so that the charts are not broken when in this mode.
1. Go to [this link](https://visualization-tool-git-fix-free-canvas-layout-ixt1.vercel.app/en/v/2SLRKv1zbrq3?dataSource=Prod).
2. ✅ See that the dashboard displays correctly.
---
=> fix: Dashboard free canvas layout

app/charts/table/table.tsx, app/components/add-button.tsx, app/components/chart-panel.tsx, app/components/chart-shared.tsx, e2e/dashboard-free-canvas.spec.ts
Closes #2078
Closes #2079
Closes #2081 
This PR:
- fixes editing of single chart after going back from layouting step,
- fixes wrong display that resulted in action buttons going out of the chart boundaries (missing `flex-direction: column`).
1. Go to [this link](https://visualization-tool-git-fix-free-canvas-in-editor-layout-ixt1.vercel.app/en/v/wneX9wuaNcfH?dataSource=Prod).
2. Copy and edit the dashboard.
3. ✅ See that the layout is not broken.
4. Proceed to layout options.
5. ✅ See that the layout is not broken.
---
=> fix: Free canvas layout

CHANGELOG.md, app/charts/line/lines.tsx, app/charts/shared/chart-helpers.tsx, e2e/edition.spec.ts
Closes #2082
This PR makes sure we correctly re-calculate `getX` when dimensions change, which fixes a problem with disappearing line chart in BLW cubes (or any cube with temporal entity-based X dimension).
1. Go to [this link](https://visualization-tool-git-fix-line-chart-locale-bug-ixt1.vercel.app/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Month&dataSource=Prod).
2. Change chart type to line.
3. Change the locale to DE.
4. ✅ See that the chart didn't disappear.
---
=> fix: Parsing temporal entities when changing locales

CHANGELOG.md, app/charts/shared/brush/index.tsx, app/test/__fixtures/config/prod/most-recent-time-range-interactive-filter.json, e2e/interactive-filters.spec.ts
This PR fixes initialization of published charts that use most recent date filter together with interactive filter, so that the full range is displayed, instead of being "stuck" in the start date.
1. Go to this link.
2. Open X axis field.
3. Enable most recent date filter.
4. Make the filter interactive.
5. Publish the chart.
6. ✅ See that's initialized correctly.
Follow the above steps on TEST and see that chart is broken in published mode (only a single year is selected in interactive filter).
---
cc @sosiology
=> fix: Most recent filter + interactive time range

CHANGELOG.md, app/configurator/configurator-state/reducer.tsx, e2e/chart-actions.spec.ts
Closes #2087
This PR fixes duplication of charts in layout mode.
Try to duplicate a chart in layout mode using a link from the PR and see that it works.
---
=> fix: Duplicating charts in layout mode

CHANGELOG.md, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #2094 
This PR fixes the missing button translations for `updating` and `creating` a custom color palette on the user profile in English.
1. Go to this [link](https://visualization-tool-git-fix-missing-button-label-ixt1.vercel.app/)
2. Click Sign in button 
3. Click on `My Color Palettes`
4. Add a new color palette
5. See how the button is now correctly translated in English _(make sure you are using EN translation)_ ✅
6. Save the color palette
7. Update the color palette, see how the button is now correctly translated in English ✅
2. Click the Sign in button and sign in 
3. Click on `My Color Palettes`
4. Add a new color palette
5. See how the button is not translated in English _(make sure you are using EN …
=> chore: fix translations

CHANGELOG.md, app/configurator/components/chart-controls/drawer-color-palette-content.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/color-palettes/color-palette-types.tsx, app/login/components/color-palettes/profile-color-palette-content.tsx, app/login/components/color-palettes/profile-color-palette-form.tsx
Closes #2095 
This PR fixes the missing error message on color palette title input when a title already exists and also adds a (required) hint + automatically disabling the `Add color button` when title is empty.
1. Go to this [link](https://visualization-tool-git-feat-highlight-missing-color-805a11-ixt1.vercel.app/)
2. Click Sign in button 
3. Click on `My Color Palettes`
4. Add a new color palette
5. See how palette title has a new (required) hint ✅
6. See how `Add color palette` button is disabled when there is no title specified ✅
7. Enter a title that already exists and see how you get the same error as in the editor ✅
2. Click Sign in button 
3. Click on `My Color Palettes`
4. Add a new color palette
5. See …
=> feat: Added error handling to profile for color palettes

CHANGELOG.md, app/components/text-block.tsx, app/configurator/configurator-state/reducer.tsx
Closes #2077
This PR enables automatic dashboard text block resizing in published charts.
1. Go to [this link](https://visualization-tool-git-feat-sync-text-block-heights-53f507-ixt1.vercel.app/en/v/CHFyazQhGXQ1?dataSource=Int-uncached) (chart state copied from #2077).
2. ✅ See that the text doesn't overlap.
---
=> feat: Resize dashboard text block also in published charts

CHANGELOG.md, app/configurator/components/chart-controls/color-palette.tsx, app/configurator/components/chart-controls/color-picker.tsx, app/configurator/components/chart-controls/color-ramp.tsx, app/configurator/components/color-picker.tsx, app/configurator/components/field.tsx, app/login/components/color-palettes/profile-color-palette-content.tsx, app/login/components/profile-content-tabs.tsx, app/palettes.ts, app/utils/use-user-palettes.ts, e2e/color-palettes.spec.ts
Closes #2100   
This PR changes selected custom color palettes to always display all colors even if type is `single` and inside the custom color picker the swatches should always dynamically set palette colors.
1. Go to this [link](https://visualization-tool-git-fix-y-axis-color-palette-ixt1.vercel.app/)
2. Create a Chart f.e (Einmalvergütung für Photovoltaikanlagen)
3. Click on `Y axis` 
4. Select a custom color palette, see how it displays all colors not just the used one ✅
5. Go back, and Select `Segmentations` (select `Kanton`, from the dropdown)
6. Select any color palette
7. Try to change a color with the custom color picker, See how the palettes colors are used for the swatches ✅
2. Create a Chart f.e …
=> fix: Show entire palette regardless the palette type

CHANGELOG.md, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/color-palettes/color-palette-types.tsx
Closes #2101  
This PR fixes makes contrast warning messages dynamic, in order to make more sense.
1. Go to this [link](https://visualization-tool-git-fix-dynamic-contrast-warnings-ixt1.vercel.app/)
2. Click Sign in button 
3. Click on `My Color Palettes`
4. Add a new color palette
5. Select Categorical color palette
6. Add Colors that are light
7. See how the warning hint appears, hover it and see how the text changed ✅
8. Select Diverging color palette
9. Add Colors that are light
10. See how the warning hint appears, hover it and see how the text changed ✅
2. Click Sign in button 
3. Click on `My Color Palettes`
4. Add a new color palette
5. Select Categorical color palette
6. Add Colors that are light
7. See …
=> chore: Add new translations

CHANGELOG.md, app/login/components/color-palettes/profile-color-palette-form.tsx
Closes #2109 
This PR fixes the missing makes sure duplicate title errors only arise when adding a palette not when updating.
1. Go to this [Link](https://visualization-tool-git-feat-highlight-missing-color-805a11-ixt1.vercel.app/)
2. Click Sign in button 
3. Click on `My Color Palettes`
4. Add a new color palette
5. See how palette title has a new (required) hint ✅
6. See how `Add color palette` button is disabled when there is no title specified ✅
7. Enter a title that already exists and see how you get the same error as in the editor ✅
2. Click Sign in button 
3. Click on `My Color Palettes`
4. Add a new color palette
5. See how palette title has no (required) hint ❌
6. See how `Add color palette` button is …
=> fix: Only allow title checks on add mode

CHANGELOG.md, app/configurator/components/filters.tsx
Closes #2111 
**What changed?**
This PR moves the `Edit filters` button from the filters section align to the left and increase spacing in that section.
1. Go to this link
2. Create a new Visualization
3. Add Segmentation & scroll down 
4. See how the button is left aligned with more spacing ✅
1. Go to this link
2. Create a new Visualization
3. Add Segmentation & scroll down 
4. See how the button is not left aligned with only little spacing ❌
---
=> fix: aligned button left and improved spacing

CHANGELOG.md, app/configurator/configurator-state/reducer.tsx
This PR fixes an infinite loop that was sometimes triggered by `useSyncTextBlockHeight` due to `ensureDashboardLayoutIsCorrect` that was creating a new `layout` object when it shouldn't.
1. Go to [this link](https://visualization-tool-git-fix-sync-text-height-ixt1.vercel.app/en/v/BvJSoR3239IX?dataSource=Prod).
2. Copy and edit the chart.
3. Add a H1 text in the text block.
4. ✅ Publish the chart and see that it works.
1. Go to [this link](https://int.visualize.admin.ch/v/sJNhBzYBM_za?dataSource=Prod).
3. Copy and edit the chart.
4. Add a H1 text in the text block.
5. ❌ Publish the chart and see that the application crashes.
---
=> fix: Infinite loop when resizing text blocks

CHANGELOG.md, app/charts/bar/chart-bar.tsx, app/charts/shared/limits.tsx, app/charts/shared/rendering-utils.ts, app/charts/table/chart-table.tsx, app/charts/table/table-state.tsx
Closes #1894
This PR adds support for showing target values and limits in bar charts.
1. Go to [this link](https://visualization-tool-git-feat-bar-table-limits-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/test_target/cube/target_1/1&dataSource=Test).
2. Switch to a bar chart.
3. ✅ Go to Horizontal Axis and see that you can add limits.
4. Add a few of them.
5. ✅ See that they appear on the chart.
---
=> feat: Add limit and target values to bar charts

CHANGELOG.md, app/configurator/components/chart-controls/color-palette.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #2123 
This PR adds a fallback for the color selector when color palettes are not available.
1. Go to this [link](https://visualization-tool-git-feat-color-palette-default-text-ixt1.vercel.app/) 
2. Create a visualization 
3. Use a custom color palette
4. Publish chart 
5. Log out 
6. Copy and edit chart 
7. See how where you picked a custom color palette it now says `Select a color palette` ✅
---
=> chore: Added translations

CHANGELOG.md, app/charts/line/lines.tsx
Closes #2129
This PR changes the logic to not base line chart dots on X axis labels, but rather on actual data points.
1. Go to [this link](https://visualization-tool-git-fix-line-dots-ixt1.vercel.app/en/v/zc_75U6iS3BN?dataSource=Prod).
2. ✅ See that dots are aligned with actual data points.
1. Go to [this link](https://int.visualize.admin.ch/en/v/THRVfaZcq4mU?dataSource=Prod).
2. ❌ See that dots are not aligned with actual data points.
---
=> fix: Base dots on data

CHANGELOG.md, app/charts/shared/legend-color.tsx
Closes https://github.com/visualize-admin/visualization-tool/issues/1894#issuecomment-2668845054
This PR adds showing of exact limit values in chart legend.
1. Go to [this link](https://visualization-tool-git-feat-limit-values-in-legend-ixt1.vercel.app/en/v/CNbXI-xzJokt?dataSource=Test).
2. See that limit values are visible in the legend.
---
=> feat: Add limit values to legend

CHANGELOG.md, app/configurator/components/chart-controls/drawer-color-palette-content.tsx, app/configurator/components/chart-options-selector.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/color-palettes/profile-color-palette-form.tsx
Closes #2070
This PR refactors show line dots component out of main encodings panel and adds translations for circle sizes.
1. Go to [this link](https://visualization-tool-git-fix-add-size-translations-ixt1.vercel.app/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Switch to a line chart.
3. Open Vertical Axis panel.
4. ✅ See that dot sizes are translated.
---
=> refactor: Extract component out and add translations

CHANGELOG.md, app/configurator/components/filters.tsx
This PR removes the tooltip on the legend titles toggle switch, based on the request by @KerstinFaye 
1. Go to this [link](https://visualization-tool-git-fix-remove-legend-titles-tooltip-ixt1.vercel.app/) 
2. Create Chart 
3. Add Segmenations
4. Scroll down to the Show titles toggle switch 
5. Hover over it 
6. See how there is no tooltip showing up ✅
1. Go to this [link](https://test.visualize.admin.ch) 
2. Create Chart 
3. Add Segmenations
4. Scroll down to the Show titles toggle switch 
5. Hover over it 
6. See how there is a tooltip showing up ❌
---
=> fix: removed tooltip on toggle switch

CHANGELOG.md, app/browser/dataset-preview.tsx, app/browser/select-dataset-step.tsx, app/components/header.tsx, app/components/layout.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/pages/browse/index.tsx
Closes #2059
This PR adds an improved view of Dataset Preview for the use of ODS.
1. Go to this [link](https://visualization-tool-git-feat-opendata-swiss-iframe-ixt1.vercel.app/) 
2. Create a Visualization w/ a Dataset
3. Go until the preview page 
4. add `&odsiframe=true` to the end of the `url` 
5. See how view is stripped of all mentioned elements under #1810
1. Go to this [link](https://test.visualize.admin.ch)
2. 2. Create a Visualization w/ a Dataset
3. Go until the preview page 
4. add `&odsiframe=true` to the end of the `url` 
5. See how view has all mentioned elements under #1810
---
---
_ps: @bprusinowski just tried to implement it the best of my understanding, so there might be a couple comments here_ 
---
cc: @KerstinFaye let me know about the translations …
=> Create optimal Iframe view for ODS

CHANGELOG.md, app/configurator/components/chart-controls/color-palette.tsx, app/configurator/components/chart-controls/color-ramp.tsx, app/configurator/components/chart-options-selector.tsx
Closes #2106
This PR makes sure that `symbolLayers` when using map charts support categorical color palettes aswell
1. Go to this [link](https://visualization-tool-git-fix-arealayer-symbollayer-bug-ixt1.vercel.app/) 
2. Create a new visualization with: `Einmalvergütung für Photovoltaikanlagen`
3. Change Chart to map type 
4. Add Symbol layer (Select Kanton)
5. Under color select Kanton 
6. See how there is a categorical palettes selection possible ✅
7. See how by default it's `Select a color palette` ✅
8. See how when you change to another dimension within color it says again `Select a color palette` ✅
1. Go to this [link](https://test.visualize.admin.ch) 
2. Create a new visualization with: `Einmalvergütung für Photovoltaikanlagen`
3. Change Chart to map type 
4. Add …
=> Fixed categorical palettes on symbolLayers

app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
This should finally fix the issue with the translations, please [test](https://visualization-tool-git-fix-color-palette-dynamic-tr-67b330-ixt1.vercel.app/) on google chrome since the issue only happened there, on safari it simply just reverted to English.
=> fix: fixed translations

CHANGELOG.md, app/charts/bar/bars-state-props.ts, app/charts/bar/bars-state.tsx, app/charts/bar/bars.tsx, app/charts/chart-config-ui-options.ts, app/config-types.ts, app/configurator/components/chart-options-selector.tsx
This PR adds custom color palettes bar chart types
1. Go to this [link](https://visualization-tool-git-fix-add-color-palettes-to-barchart-ixt1.vercel.app/)
2. Create a visualization 
3. Select bars
4. Select X Axis
5. See how there is a color selector ✅
1. Go to this [link](https://test.visualize.admin.ch)
2. Create a visualization 
3. Select bars
4. Select X Axis
5. See how there is no color selector ❌
---
=> feat: Added color palettes to bar charts

CHANGELOG.md, app/charts/shared/limits.tsx
Closes https://github.com/visualize-admin/visualization-tool/issues/1894#issuecomment-2682331086
This PR makes sure we don't render limits that have undefined X or Y values.
1. Go to [this link](https://visualization-tool-git-fix-filtering-of-limits-ixt1.vercel.app/en/v/sYiShrTs0WNn?dataSource=Test).
2. ✅ See that there are no limits on the left side of the chart.
---
=> fix: Correctly filter out undefined

app/charts/chart-config-ui-options.ts
Just noticed that I accidentally called the schema., `schemeCategory10` instead of just `category10` 😬
=> fix: schemeCategory10 -> category10

CHANGELOG.md, app/charts/shared/limits.tsx, app/docs/catalog/chart-preview-via-api.mdx, app/pages/_preview.tsx, app/pages/docs/index.tsx, app/pages/preview.tsx
Closes #2064
This PR makes it possible to set chart state in` /preview` chart preview via a `state` query parameter.
1. Go to [this link](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_Iframe).
2. Remove all the content from the left editor and paste the below.
```html
<!DOCTYPE html>
<html>
<body>
<h1>The iframe element</h1>
<iframe src="https://visualization-tool-git-feat-parametrisable-url-ixt1.vercel.app/preview?state={%22state%22:%22CONFIGURING_CHART%22,%22dataSet%22:%22https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/2%22,%22dataSource%22:{%22type%22:%22sparql%22,%22url%22:%22https://lindas-cached.cluster.ldbar.ch/query%22},%22meta%22:{%22title%22:{%22de%22:%22%22,%22fr%22:%22%22,%22it%22:%22%22,%22en%22:%22%22},%22description%22:{%22de%2 …
```
=> feat: Make it possible to preview chart via iframe with query parameter

CHANGELOG.md, app/configurator/components/chart-options-selector.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx, app/configurator/configurator-state/reducer.tsx
Closes #2149 
This PR fixes the color palette selection to persist and map correctly when changing dimensions
1. Go to this link 
2. Create a chart (e.g : Bodenbelastung durch Schwermetalle)
3. Add Segmentation select (Bemerkungen)
4. Select a color palette
5. Change Dimension to (Gemeinde)
6. See how colors persist ✅
1. Go to this [link](https://test.visualize.admin.ch) 
2. Create a chart (e.g : Bodenbelastung durch Schwermetalle)
3. Add Segmentation select (Bemerkungen)
4. Select a color palette
5. Change Dimension to (Gemeinde)
6. See how colors don't persist ❌
---
=> fix: fixed color on dimensions change

CHANGELOG.md, app/browser/dataset-preview.tsx
Closes #2159
This PR removes the title and description on dataset previews when odsiframe is active.
1. Go to this link
2. Create a Visualization w/ a Dataset
3. Go until the preview page 
4. add `&odsiframe=true` to the end of the `url` 
5. See how view is stripped of title and description as well 
---
---
@sosiology
=> fix: fixed odsiframe based on requests

CHANGELOG.md, app/charts/map/map-custom-layers-legend.tsx, app/components/hint.tsx
Closes #2164
This PR improves the styles of custom map legends loading indicator.
1. Go to [this link](https://visualization-tool-git-feat-optimize-custom-map-leg-2393c5-ixt1.vercel.app/en/v/dMuqmcsH31D8?dataSource=Prod).
2. ✅ See that the loading indicator doesn't take the full width, doesn't switch to "loading this dataset may require additional time" after 7.5s and that it's positioned further away from the footnotes.
---
=> feat: Add InlineLoading

CHANGELOG.md, app/configurator/components/chart-options-selector.tsx
Closes #2173
This PR makes sure we use correct field labels in the encoding options panel.
1. Go to this link.
2. Switch to a pie chart.
3. Open a `Measure` field.
4. See that the section title is correctly set to `Measure` instead of `Vertical Axis`.
---
=> fix: Field naming

CHANGELOG.md, app/charts/area/areas-state-props.ts, app/charts/area/areas-state.tsx, app/charts/area/chart-area.tsx, app/charts/bar/bars-state-props.ts, app/charts/bar/bars-state.tsx, app/charts/bar/chart-bar.tsx, app/charts/column/chart-column.tsx, app/charts/column/columns-state-props.ts, app/charts/column/columns-state.tsx, app/charts/line/chart-lines.tsx, app/charts/line/lines-state-props.ts, app/charts/line/lines-state.tsx, app/charts/shared/chart-state.ts, app/charts/shared/rendering-utils.ts, app/charts/shared/stacked-helpers.ts, app/docs/charts.stories.tsx, app/docs/lines.stories.tsx, app/docs/tooltip.stories.tsx
Closes #2169
This PR makes sure we always display appropriate limits, even when they go beyond the data range. It also correctly centers limits by offsetting half of line stroke width.
1. Go to [this link](https://visualization-tool-git-feat-show-limits-beyond-chart-range-ixt1.vercel.app/en/v/TD_3oSQPBtj2?dataSource=Test).
2. ✅ See that all limits are visible, even these far beyond the data range.
---
=> feat: Show limits beyond data range

CHANGELOG.md, app/configurator/components/chart-options-selector.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx
Closes #2177
This PR:
- fixes setting categorical symbol colors,
- makes opening the `Horizontal Axis` field no longer overwrite the colors in case chart has a segment,
- makes it impossible to set colors through multi-filter panel when shouldn't (in places like e.g. `Horizontal Axis`).
1. Go to [this link](https://visualization-tool-git-fix-color-x-segment-overwrite-ixt1.vercel.app/en/create/new?cube=https://health.ld.admin.ch/fsvo/Forschungsbericht_2021-2024_Themengebiete/2&dataSource=Prod).
2. Add a segmentation by `Subject areas`.
3. Open `Horizontal Axis`.
4. ✅ See that the colors were persisted.
5. ✅ See that the colors pickers are not available.
6. Go to [this link](https://visualization-tool-git-fix-color-x-segment-overwrite-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admi …
=> fix: Multi-filter colors setting

CHANGELOG.md, app/browser/select-dataset-step.tsx, app/charts/map/chart-map.tsx, app/charts/map/dashed-scatterplot-layer.ts, app/charts/map/map-legend.tsx, app/charts/map/map.tsx, app/charts/pie/pie.tsx, app/charts/shared/limits.tsx, app/charts/shared/render-value-labels.ts, app/config-types.ts, app/config-utils.ts, app/configurator/components/chart-options-selector.tsx, app/configurator/configurator-state/actions.tsx, app/configurator/configurator-state/reducer.tsx, app/docs/charts.stories.tsx, app/docs/lines.stories.tsx, app/docs/tooltip.stories.tsx
Closes #2170
Closes #2180
This PR:
1. Introduces support for rendering limits when "axis dimension" is not displayed directly in the chart, but is a single filter.
2. Introduces support for rendering limits in map charts.
**Rendering limits when "axis dimension" is a single filter**
1. Go to [this link](https://visualization-tool-git-feat-show-limits-in-maps-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/test_target/cube/target_1/1&dataSource=Test).
2. Open `Vertical Axis` field.
3. Add limit for thermal fuel (2012).
4. Switch `Horizontal Axis` to `Energy source`.
5. Set `Year` filter to `Year 2012`.
6. ✅ See that the limit is displayed (in contrast to TEST / INT, where it does not appear).
7. Go to [this …
=> feat: Render limits in maps and when axis dimension is a single filter

CHANGELOG.md, app/login/components/color-palettes/profile-color-palette-form.tsx
Closes #2098 
This PR makes sure the color type names are correctly translated, instead of always displaying German labels. This was fixed by moving the type labels mapping to a component, instead of being defined at the file-level.
1. Go to [this link](https://visualization-tool-git-fix-color-ui-copy-ixt1.vercel.app/en).
2. Log in.
3. Go to user profile.
4. ✅ Try to define a new color palette and see that the palette names are correctly translated.
5. ✅ Change language and repeat to see that the labels are correct.
---
=> fix: Translations of color names

CHANGELOG.md, app/components/footer.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #1795
This PR adds a link to Statistics page to the footer.
1. ✅ Go to [this link](https://visualization-tool-git-feat-add-stats-page-to-footer-ixt1.vercel.app/en) and see that there's a Statistics link in the footer that once clicked, opens Statistics page.
---
=> feat: Add Statistics page link to the footer

CHANGELOG.md, app/charts/shared/chart-data-filters.tsx, app/components/form.tsx, app/config-types.ts, app/configurator/components/chart-configurator.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #1881
This PR adds a way to display interactive filters panel open by default.
1. Go to [this link](https://visualization-tool-git-feat-improve-visibility-of-i-0d6e77-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. See that there's a "Show filter area open per default" checkbox in the left panel.
3. Make `Kanton` interactive.
4. ✅ Toggle "Show filter area open per default" checkbox and see that the filter area opened.
5. ✅ Publish the chart and see that it's also kept open here.
---
=> ✓ feat: Add a way to open interactive filters area per default

CHANGELOG.md, app/charts/index.ts, app/charts/shared/legend-color.tsx, app/charts/shared/limits.tsx, app/charts/shared/rendering-utils.ts, app/config-types.ts, app/config-utils.ts, app/configurator/components/chart-options-selector.tsx, app/configurator/configurator-state/reducer.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #2181
This PR adds support for setting circle and cross symbol types for area and line charts.
To make the implementation simpler, I decided to not introduce a new type (to keep track of e.g. `single` or `range` limits in chart config) and avoid a need to check the types everywhere to access `symbolType` or `lineType` properties.
I am not happy how the color legend code looks like now; but this could be cleaned when we migrate to new CI / CD, as the symbols and styles will change anyway then.
1. Go to [this link](https://visualization-tool-git-feat-add-limit-symbols-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/test_target/cube/target_1/1&dataSource=Test).
2. Go to `Vertical Axis` field and toggle all targets.
3. ✅ Switch to a line chart and see that you …
=> feat: Add limit symbols

.dockerignore, CHANGELOG.md, Dockerfile
Potentially supports #2064 
This PR includes a Node server configuration parameter for supporting long HTTP headers up to 64KB in length (default is 8K).
Currently, there is no possibility of testing the effectiveness of this parameter in our deployment environments, as it is dependent on other configuration changes (load balancer, WAF).
---
=> Support longer HTTP headers

Dockerfile
Potentially supports #2064 
Fix for previous PR (#2195) as the GC heap value was being overwritten with the option for long header support.
Currently, there is no possibility of testing the effectiveness of this parameter in our deployment environments, as it is dependent on other configuration changes (load balancer, WAF).
=> fix: Consolidate multiple Node options

CHANGELOG.md, app/charts/index.ts, app/charts/shared/chart-data-filters.tsx, app/configurator/components/chart-configurator.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #2192
Closes #2193
This PR sets the state of interactive filters to open by default. It also removes the function to collapse filters when this option is active.
1. Go to [this link](https://visualization-tool-git-feat-interactive-filters-tog-5be719-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Enable `Kanton` interactive filter.
3. ✅ See that it's shown open and that `Hide filters` toggle is missing.
@KerstinFaye @sosiology I know the client has already decided about removing `Hide filters` toggle, if I understood correctly, to save some space – I just wanted to point that removing it doesn't save any space, as it's rendered in the same row as `Details` panel button (and not having a …
=> feat: Interactive filters toggle changes

CHANGELOG.md, app/charts/bar/bars-stacked.tsx, app/charts/column/columns-stacked.tsx
Closes #2202
This PR fixes a rare scenario when showing value labels for segmented charts was not working – the only reproduction was possible with an INT cube, so I assume there was an issue with cube definitions. The fix to try to treat segment label as segment, in case it doesn't return a value when we try to retrie a segment value by label.
1. Go to [this link](https://visualization-tool-git-fix-segment-vs-segment-label-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/19&dataSource=Int).
2. Add segmentation by Kanton.
3. ✅ Toggle some value labels and see that they show on a chart.
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_p …
=> fix: Show value labels when segment label equals value

CHANGELOG.md, app/charts/chart-config-ui-options.ts, app/charts/shared/legend-color.tsx
Closes #2201
This PR makes sure we re-initialize `showValuesMapping` when segment is changed. This won't fix existing TEST / INT charts that were made before the fix, but will make sure new ones are saved correctly.
1. Go to [this link](https://visualization-tool-git-fix-value-mapping-copy-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd01041prod/4&dataSource=Prod).
2. Add segmentation by `Observation location`.
3. Change segmentation to `Parameter`.
4. Refresh the page.
5. ✅ See that you still see the chart.
1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd01041prod/4&dataSource=Prod) (TEST).
2. Add segmentation by `Observation location`.
3. Change segmentation to `Parameter`.
4. Refresh the page. …
=> fix: Correctly set showValuesMapping when segment changes

CHANGELOG.md, app/charts/combo/combo-line-column-state.tsx, app/charts/combo/combo-line-column.tsx, app/charts/combo/combo-line-dual-state.tsx, app/charts/combo/combo-line-dual.tsx, app/charts/combo/combo-line-single-state.tsx, app/charts/combo/combo-line-single.tsx, app/charts/combo/combo-state.ts, app/charts/shared/chart-data-filters.tsx, app/components/chart-footnotes.tsx, app/configurator/components/chart-configurator.tsx, app/configurator/components/dataset-control-section.tsx, e2e/filter-position.spec.ts, e2e/fixtures/hierarchy-test-13-municipality-population.json
Closes #1922
This PR:
- fixes the problem with changing one filter value that made two filters change when using merged cubes with dimensions with the same iris,
- fixes the problem with interactive filters displaying no values when enabling them in merged cubes context,
- fixes the problem with not separating dimensions per cubes in multi-line chart when using merged cubes with dimensions with the same iris (and also misaligned colors in the same cases),
- makes the legend items break words, which prevent the labels from overlapping.
1. Go to [this link](https://visualization-tool-git-fix-merged-cubes-filters-tandem-ixt1.vercel.app/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Month&dataSource=Prod).
2. Add a new dataset.
3. Select …
=> fix: Merging of cubes problems

CHANGELOG.md, app/browse/datatable.tsx, app/browser/dataset-preview.tsx, app/browser/select-dataset-step.tsx
Closes #2249
This PR improves the appearance of ODS dataset preview iframe by extending the table width to 100% even if we have few columns. It also optimizes horizontal padding to align more closely with surrounding content on target pages (didn't set it to 0 to avoid cut off shadows).
1. Go to [this link](https://visualization-tool-git-feat-improve-ods-iframe-ixt1.vercel.app/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22NOx%22%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd010702%2F14&dataSource=Int&odsiframe=true).
2. ✅ See that the table takes the full width of the page and that horizontal paddings are smaller than before.
---
=> style: Improve ODS dataset preview iframe's appearance

CHANGELOG.md, app/charts/area/areas-state-props.ts, app/charts/area/areas-state.tsx, app/charts/area/areas.tsx
Closes #2254
This PR adds support for showing future limits for area charts.
1. Go to [this link](https://visualization-tool-git-feat-future-limits-area-chart-ixt1.vercel.app/en/v/Z7eFo1DVEV6c?dataSource=Test).
2. ✅ See a non-broken area chart with future limits.
---
=> feat: Future limits support for area charts

CHANGELOG.md, app/rdf/queries.ts, app/rdf/query-cube-preview.ts, app/rdf/query-unit-labels.ts
Closes #2251
This PR adds support for fetching unit labels in more languages, falling back to non-localized strings if unit label is not localized.
1. Go to [this link](https://visualization-tool-git-feat-fetch-unit-labels-in-mo-7eb547-ixt1.vercel.app/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22future%22%2C%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftest_target%2Fcube%2Ftarget_future%2F1&dataSource=Int).
2. ✅ See that the `Mt` unit is displayed in the column.
3. Create a chart.
4. ✅ See that the `Mt` unit is displayed in the y axis label.
---
=> feat: Fetch unit labels in more languages

CHANGELOG.md, app/charts/shared/legend-color.tsx, app/charts/shared/rendering-utils.ts, app/config-types.ts, app/configurator/components/chart-options-selector.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/rdf/queries.ts
Closes #2218
This PR:
- introduces a triangle single-value limit symbol,
- allows styling of single-limit line (solid or dashed) when makes sense – either for single-value line limits or overarching limits not tied to any axis dimension value.
1. Go to [this link](https://visualization-tool-git-feat-new-limit-symbols-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/test_target/cube/target_future_ghg/1&dataSource=Test).
2. Switch to a line chart.
3. Open Vertical Axis.
4. ✅ Toggle a limit and see that you can select a triangle symbol that's also reflected in the legend.
5. Go to [this link](https://visualization-tool-git-feat-new-limit-symbols-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/test_target/cube/target_soil/1&dataSource=Test), …
=> feat: New limit styling options

CHANGELOG.md, app/charts/shared/chart-data-filters.tsx, app/components/markdown.tsx, app/components/mdx-editor/link-dialog.tsx
Closes #2125
Closes #2126
Closes #2265
This PR:
- allows entering www links in markdown-based components,
- aligns interactive filter select elements size,
- changes markdown link color to primary.
---
=> feat: Smaller improvements

CHANGELOG.md, app/utils/hash-utils.ts
Closes #2270
As some of the values can contain e.g. spaces (chart title or text block) or be empty arrays, they get inadvertently encoded when present in the URL. We need to decode the string to make sure we handle these cases correctly.
1. Go to [this link](https://visualization-tool-git-fix-hash-parsing-fixes-ixt1.vercel.app/en/v/Z__C5MpCwJwu?dataSource=Prod).
2. Copy and edit the visualization.
3. Copy preview link.
4. Paste preview link in a new tab and hit Enter.
5. ✅ See that the title is rendered as expected.
---
=> fix: Properly handle encoded values

app/utils/hash-utils.spec.ts, app/utils/hash-utils.ts
Closes #2270
This PR makes sure we correctly handle newlines in text when previewing the chart via hash params.
1. Go to [this link](https://visualization-tool-git-fix-hash-newlines-ixt1.vercel.app/en/create/new?copy=e31bt-AgZKb6).
2. Copy preview link.
3. ✅ Open the link in a new tab and see that new lines were persisted correctly.
---
=> fix: Hash preview text with newlines

CHANGELOG.md, app/charts/bar/rendering-utils.ts, app/charts/column/rendering-utils.ts, app/charts/shared/render-value-labels.ts, app/components/chart-shared.tsx
Closes #2275
This PR makes sure we do not overwrite segmented value label colors when downloading images.
1. Go to [this link](https://visualization-tool-git-fix-gray-value-labels-image-9b2f2b-ixt1.vercel.app/en/v/d8x-OZiOJhvj?dataSource=Prod).
2. Export PNG.
3. ✅ See that the value label colors are the same as in the website.
---
=> fix: Persist value label colors when downloading images

app/statistics/prisma.ts
Should close #2196 
This PR adds (very) basic validation that cube `iri`s conform to the form of a URL, i.e. beginning with `http://` or `https://`. For sure, more robust logic could be added, however, this would be at the expense of performance and fundamentally, the longer-term fix would be to not write malformed `iri`s to the DB in the first place.
_Note:_ The intended, fixed behaviour can only be tested on INT.
1. https://int.visualize.admin.ch/statistics
2. There should be no error reported and statistics should be displayed as expected
---
=> fix: Basic iri validation for statistics query

app/charts/map/wms-wmts-providers-autocomplete.tsx
Inadvertently kept the "open" attribute on the wmts autocomplete, preventing
the autocomplete popover to be closed.
This PR fixes this problem.
- Add a custom layer to a map
- See that the WMTS provider autocomplete is not open by default
=> fix: Do not keep open wmts autocomplete

CHANGELOG.md, app/next.config.js
Closes #2280 
This PR fixes image download by allowing local `data` in CSP.
1. Go to [this link](https://visualization-tool-git-fix-image-download-ixt1.vercel.app/en/v/9MAMEuKjiPDc?dataSource=Prod).
2. Try to download a chart.
3. ✅ See that it works.
---
=> fix: Image download

CHANGELOG.md, app/charts/map/map-custom-layers-legend.tsx, app/charts/map/map.tsx, app/charts/map/wms-utils.ts, app/charts/map/wms-wmts-endpoint-utils.ts, app/charts/map/wms-wmts-selector.tsx, app/charts/map/wms-wmts-utils.spec.ts, app/charts/map/wmts-playground.stories.tsx, app/charts/map/wmts-utils.ts
I do not know how I missed that lists were still used to find the remote layer from the config layer in the map. It was preventing nested layers to appear.
- **fix: Support html description for external layers**
- **feat: Add CRS and expose isCRS supported function for both WMS and WMTS tiles**
- **fix: Get attributions only from added layers**
- **fix: Correctly get deckgl layers from tree**
- **feat: Add mention of unsupported CRS**
- Correctly added layers
1. Open Photovoltaik
2. Add a custom layer with endpoint https://www.geoservice.apps.be.ch/geoservice3/services/a42geo/of_boundaries01_de_ms_wms/MapServer/WMSServer
3. Add layer from "Steininventare" : Stundensteine, historiziche grensteine
4. See that it works
- Add mention of unsupported CRS
Open the endpoint …
=> Display of layers

CHANGELOG.md, app/charts/combo/combo-state.ts, app/configurator/components/chart-configurator.tsx
Closes #
This PR introduces some enhancements to merging of cubes and combo charts.
1. Go to [this link](https://visualization-tool-git-feat-merging-of-cubes-improv-8b67c9-ixt1.vercel.app/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/BreadCerealsFlourBakedGoods/Consumption_Price_Month&dataSource=Int).
2. Add a **Market figures milk and dairy products - Monthly consumer prices** dataset.
3. ✅ See that it's possible to add non key dimensions for both datasets.
4. ✅ See that joined dimensions are shown first.
5. ✅ See that the Y axis label is not overlapping with Y axis ticks.
---
=> feat: Merging of cubes improvements

CHANGELOG.md, app/charts/area/chart-area.tsx, app/charts/bar/chart-bar.tsx, app/charts/chart-config-ui-options.ts, app/charts/column/chart-column.tsx, app/charts/line/chart-lines.tsx, app/charts/shared/axis-hide-overflow-rect.tsx, app/charts/shared/axis-width-band.tsx
Closes #1871
This PR:
- defaults custom scale domain minimum value to 0 in case no negative values are present,
- hides chart area that overflows X or Y axis when using custom scale domain,
- improves band axis' labels positioning.
1. Go to [this link](https://visualization-tool-git-fix-custom-scale-domain-issues-ixt1.vercel.app/en/create/new?cube=https://agriculture.ld.admin.ch/foag/cube/MilkDairyProducts/Consumption_Price_Month&dataSource=Prod&flag__custom-scale-domain=true).
2. ✅ See that the X axis tick labels are aligned correctly with the tick lines.
3. Open Vertical axis field.
4. Click on Adjust scale domain.
5. ✅ See that the min value was set to 0 and chart didn't shift to the bottom.
6. Set the min value to 5.
7. ✅ See that the chart doesn't overflow the X axis.
8. ✅ Repeat the …
=> fix: Custom scale domain issues

CHANGELOG.md, app/charts/column/overlay-columns.tsx, app/charts/combo/chart-combo-line-column.tsx, app/charts/combo/combo-line-column-state.tsx, app/charts/combo/combo-line-column.tsx, app/charts/shared/axis-width-band.tsx, app/charts/shared/chart-state.ts
Closes #2300
This PR makes the column-line chart work correctly with temporal entity X dimensions.
1. Go to [this link](https://visualization-tool-git-fix-merged-column-line-charts-ixt1.vercel.app/en/v/JQZnJZT2Nj84?dataSource=Int).
2. ✅ See that the column-line chart works correctly for merged BLW cubes (joined X temporal entity dimension).
---
=> fix: Temporal entity dimension column-line charts

CHANGELOG.md, app/charts/area/chart-area.tsx, app/charts/bar/chart-bar.tsx, app/charts/column/chart-column.tsx, app/charts/line/chart-lines.tsx, app/charts/shared/legend-color.tsx, app/config-utils.ts, app/docs/charts.stories.tsx, app/docs/lines.stories.tsx, app/docs/tooltip.stories.tsx
Closes #2301
This PR adds units to limit legend items if they are available.
1. Go to [this link](https://visualization-tool-git-feat-add-units-to-limit-lege-7d57f3-ixt1.vercel.app/en/v/Bkq9xccvieTR?dataSource=Int).
2. ✅ See that the legend limit contains a unit.
---
=> feat: Add units to limit legend items

CHANGELOG.md, app/configurator/components/custom-layers-selector.tsx
Closes #2298
This PR reverses the order of displaying the custom layers in the UI, so that the topmost layer is the topmost layer on the map.
1. Go to [this link](https://visualization-tool-git-feat-layers-order-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
2. Switch to a map chart.
3. Add a few custom layers.
4. ✅ See that new layers are added on top of the list.
5. ✅ See that the topmost layer in the list is also the topmost layer on the map.
---
=> feat: Reverse custom layers order

CHANGELOG.md, app/charts/bar/bars-grouped-state.tsx, app/charts/bar/bars-stacked-state.tsx, app/charts/bar/bars-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx, app/charts/combo/combo-line-column-state.tsx, app/charts/shared/axis-height-band.tsx, app/charts/shared/axis-width-band.tsx, app/charts/shared/chart-state.ts, app/rdf/query-search.ts
Fixes #2304
Fixes #2313
This PR fixes:
- an issue with NaN values in X axis and tooltip title for temporal entity dimensions,
- an issue with duplicated termset tags when search for cubes to merge.
1. Go to [this link](https://visualization-tool-git-fix-blw-cubes-issues-ixt1.vercel.app/browse?dataset=https%3A%2F%2Fagriculture.ld.admin.ch%2Ffoag%2Fcube%2FOilseeds%2FProduction_Quantity_Year&dataSource=Int).
2. ✅ See that X axis tick labels and tooltip title are formatted correctly (no NaNs).
3. ✅ Switch to a bar chart and see that it looks ok too.
4. Click on Hinzufügen.
5. Search for `Marktzahlen Ölsaaten - Jährliche Konsumentenpreise`.
6. ✅ See that the tags are not duplicated.
---
=> fix: BLW cube issues

CHANGELOG.md, app/package.json, yarn.lock
Closes #2307
This PR updates `swiss-federal-ci` to make sure we use the correct styles of some common components.
1. Go to [this link](https://visualization-tool-git-feat-update-swiss-federal-ci-ixt1.vercel.app/en).
2. See that the top bar, logo and header divider have updated styles that should match the [design](https://www.figma.com/design/bMl4bRDClW4oNXSf4DUrS2/BUND---Global-Library?node-id=2158-8480&m=dev).
---
=> chore: Update swiss-federal-ci

CHANGELOG.md, app/components/header.tsx
Closes #2310
This PR makes sure the text color is correctly displayed on Windows machines.
1. Go to [this link](https://visualization-tool-git-fix-invisible-windows-locale-c798a2-ixt1.vercel.app/en) on a Windows machine and use e.g. Edge browser.
2. ✅ Open the locale switcher menu and see that the text is visible.
---
=> fix: Locale switcher text color

CHANGELOG.md, app/components/chart-preview.tsx, app/components/chart-published.tsx, app/components/chart-table-preview.tsx, app/themes/components.tsx
Closes #2321
This PR improves the data preview table by:
- making the header sticky, as was the case before,
- using correct border styles,
- adding a bit of margin between the table and footnotes.
1. Go to [this link](https://visualization-tool-git-feat-improve-chart-table-preview-ixt1.vercel.app/en).
2. Scroll down, to the **Distribution of expenses and income by office** chart.
3. Open `Table view`.
4. ✅ Scroll the table and see that the header is sticky, the border colors are more prominent and include the last row's border, and there's a bit more gap between the table and the footnotes.
---
=> feat: Improve chart preview table

CHANGELOG.md, app/charts/bar/bars-state.tsx, app/charts/bar/show-values-utils.ts, app/charts/column/columns-state.tsx, app/charts/column/show-values-utils.ts, app/charts/shared/show-values-utils.ts
Closes #2328
This PR makes sure there are no overlaps when total value labels and error whiskers are enabled at the same time.
1. Go to [this link](https://visualization-tool-git-fix-show-all-values-error-wh-c2b469-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/nfi/nfi_T-changes/cube/2024-1&dataSource=Prod).
2. Open Vertical Axis field.
3. Enable `Always show total values` option.
4. ✅ See that the value labels do not overlap with the error whiskers.
5. ✅ Switch to a bar chart and see that the overlap is also not here.
---
=> fix: Total value labels and error whiskers overlap

CHANGELOG.md, app/rdf/limits.ts
Closes #2332
Closes #2333
This PR:
- makes sure we do not display not supposed range limits in the UI, preventing some bugs that come out of this,
- fixes fetching of related limit values (position can be undefined, use dimension iri, not id) to prevent "tandem toggle" issue.
1. Go to [this link](https://visualization-tool-git-fix-do-not-display-not-suppo-4da0b7-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/test_target/cube/target_soil/1&dataSource=Int).
2. Open `Vertical Axis` field.
3. ✅ See that only limit for current filter (`Cadmium`) is displayed.
4. Change the filter to `Copper`.
5. ✅ Go back to the `Vertical Axis` field and see that only the limit for `Cooper` is displayed.
6. Go to [this link](https://visualization-tool-git-fix-do-not-display-not-suppo-4d …
=> fix: Do not display range limits + fix fetching of related limit values

CHANGELOG.md, app/charts/pie/chart-pie.tsx, app/charts/pie/pie-state.tsx, app/charts/shared/axis-height-linear.tsx, app/charts/shared/axis-height-title.tsx
Closes #2223
This PR adds "Y" axis title to pie charts.
1. Go to [this link](https://visualization-tool-git-feat-add-axis-title-to-pie-charts-ixt1.vercel.app/en/v/8kQrrwRMsl-u?dataSource=Prod).
2. ✅ See that the pie chart has an "Y" axis title.
---
=> feat: Add axis title to pie charts

CHANGELOG.md, app/rdf/limits.ts
Closes #2337
This PR makes sure we can display limits with `Literal` related values (regular dates).
1. Go to [this link](https://visualization-tool-git-feat-support-literal-related-f348d6-ixt1.vercel.app/en/v/6byHMR3sTBFl?dataSource=Int).
2. ✅ See that the limits are displayed (temporal entity based related limit values).
3. Go to [this link](https://visualization-tool-git-feat-support-literal-related-f348d6-ixt1.vercel.app/en/v/eu-rXJBdhixR?dataSource=Int).
4. ✅ See that the limits are displayed (non temporal entity based related limit values).
---
=> feat: Support limits with Literal related values

CHANGELOG.md, app/configurator/components/chart-options-selector/conversion-units-field.tsx
Closes #2347
This PR improves the conversion unit input element UX by allowing clearing the input value and only updating the application state when the multiplier value is valid. The input also resets back to a correct, previous value in case user enters a wrong value and the input loses focus.
1. Go to [this link](https://visualization-tool-git-feat-conversion-units-ui-imp-cede5c-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod&flag__convert-units=true).
2. Open Vertical Axis.
3. Enable conversion units.
4. ✅ See that the multiplier input is much more user friendly – e.g. it's possible to remove multiplier.
---
=> feat: Improve conversion unit input UX

CHANGELOG.md, app/charts/shared/render-value-labels.ts
Closes #2361
This PR makes sure the segmented value label colors persist when downloading PNG image of a chart.
1. Go to [this link](https://visualization-tool-git-fix-segment-value-labels-png-ixt1.vercel.app/en/v/UBM1nX43UAd-?dataSource=Prod).
2. Export PNG image.
3. ✅ See that the value label colors are correct.
---
=> fix: Segmented value label colors in PNG export

CHANGELOG.md, app/charts/bar/bars-grouped-state.tsx, app/charts/bar/bars-stacked-state.tsx, app/charts/bar/bars-state.tsx, app/charts/column/columns-grouped-state.tsx, app/charts/column/columns-stacked-state.tsx, app/charts/column/columns-state.tsx
Closes #2362
This PR makes sure we correctly format X and Y band axis ticks.
1. Go to [this link](https://visualization-tool-git-fix-formatting-ixt1.vercel.app/en/v/bHWNuHLuWIbf?dataSource=Prod).
2. ✅ See that the X axis ticks are formatted correctly.
---
=> fix: Tick formatting

CHANGELOG.md, app/flags/types.ts, app/graphql/client.tsx
Closes #2376
This PR removes a way to set custom GQL endpoint. I am not aware of any current use case that requires it, and keeping it is a real security issue.
---
=> chore: Remove GQL endpoint flag

CHANGELOG.md, app/configurator/components/chart-controls/color-palette.tsx
Closes #2367
This PR fixes duplicated color squares that were starting to appear when switching between custom and default color palettes.
1. Go to [this link](https://visualization-tool-git-fix-duplicated-color-squares-ixt1.vercel.app/en?dataSource=Prod).
2. Sign in.
3. Go to [this link](https://visualization-tool-git-fix-duplicated-color-squares-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/10&dataSource=Prod).
4. Open `Vertical Axis`.
5. ✅ Switch between custom and default color palettes and see that the color squares are not being duplicated.
---
=> fix: Duplicated color squares

CHANGELOG.md, app/configurator/components/chart-options-selector/conversion-units-field.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #2371
This PR improves the UX of interacting with unit multiplier input by providing clear error messages when input is invalid.
1. Go to [this link](https://visualization-tool-git-feat-errors-in-conversion-mu-2df098-ixt1.vercel.app/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22photo%22%7D&dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen%2F10&dataSource=Prod&flag__custom-scale-domain=true&flag__convert-units=true).
2. Start a visualization.
3. Open Vertical Axis panel.
4. Enable custom scale domain and unit conversion.
5. Try to enter an invalid value in custom scale domain input and see that an error appears.
6. ✅ Try to enter an invalid value in unit conversion multiplier input and see that it behaves in …
=> feat: Improve error handling in unit multiplier input

CHANGELOG.md, app/configurator/components/field.tsx
Closes #2390
This PR fixes the display of most recent date toggle in the single filters panel.
1. Go to [this link](https://visualization-tool-git-fix-use-most-recent-toggle-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/nfi/nfi_T-changes/cube/2024-1&dataSource=Prod).
2. Switch to a map chart.
3. ✅ Scroll down the left panel to the filters section and see that "Use most recent" toggle is correctly rendered.
---
=> fix: Most recent date toggle

CHANGELOG.md, app/browser/select-dataset-step.tsx, app/configurator/components/layout.tsx
Closes #898
This PR improves the dataset browser's appearance on mobile. It's still not perfect, but should at least be usable now.
1. Go to [this link](https://visualization-tool-git-fix-dataset-browser-on-mobile-ixt1.vercel.app/en/browse?dataSource=Prod) on mobile.
2. Open any dataset.
3. ✅ See that both views are not overflowing horizontally.
---
=> fix: Dataset browser on mobile

app/docs/homepage.docs.mdx, app/docs/homepage.stories.tsx, app/static-pages/de/index.mdx, app/static-pages/en/index.mdx, app/static-pages/fr/index.mdx, app/static-pages/it/index.mdx, app/templates/email/index.ts
Closes #2369
This PR removes IXT from newsletter subscriptions (bcc emails).
1. Go to this link.
2. Click on `Subscribe` button at the bottom of the page (newsletter).
3. ✅ See that the mail would only be sent to visualize@bafu.admin.ch.
---
=> feat: Remove IXT from newsletter mail bcc

CHANGELOG.md, app/components/chart-published.tsx, app/components/chart-shared.tsx, app/pages/preview.tsx, app/pages/preview_post.tsx
Closes #2397
This PR makes sure we can't use database-related actions in preview charts (that do not exist in a database).
1. Go to [this link](https://visualization-tool-git-fix-hide-database-related-ac-2daa83-ixt1.vercel.app/en/preview#version=4.6.0||state=CONFIGURING_CHART||dataSource__SEP__type=sparql||dataSource__SEP__url=https://lindas-cached.cluster.ldbar.ch/query||layout__SEP__type=tab||layout__SEP__meta__SEP__title__SEP__de=||layout__SEP__meta__SEP__title__SEP__en=||layout__SEP__meta__SEP__title__SEP__fr=||layout__SEP__meta__SEP__title__SEP__it=||layout__SEP__meta__SEP__description__SEP__de=||layout__SEP__meta__SEP__description__SEP__en=||layout__SEP__meta__SEP__description__SEP__fr=||layout__SEP__meta__SEP__description__SEP__it=||layout__SEP__meta__SEP__label__SEP__de=||layout__S …
=> fix: Hide database-related actions in chart previews

CHANGELOG.md, app/components/chart-selection-tabs.tsx
Closes #1776
This PR makes sure we always show scroll arrows when needed to avoid empty spaces.
1. Go to [this link](https://visualization-tool-git-feat-always-show-scroll-butt-ad5f82-ixt1.vercel.app/en/v/WUo-ZwN8m6WW?dataSource=Prod).
2. ✅ See that the left arrow is visible without having to scroll.
---
=> fix: Always show chart tab scroll buttons when needed

CHANGELOG.md, app/components/row-actions.tsx, app/configurator/components/chart-controls/color-picker.tsx, app/db/config.ts, app/domain/user-configs.ts, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po, app/login/components/color-palettes/color-palette-types.tsx, app/login/components/color-palettes/profile-color-palette-content.tsx, app/login/components/profile-content-tabs.tsx, app/login/components/profile-tables.tsx, app/login/utils.ts, app/pages/api/config/view.ts, app/utils/chart-config/api.ts
Closes #1796
This PR:
- adds a new, `Views` column to user profile tables that displays the number of times a given chart was displayed,
- aligns some login styles with the design.
1. Go to [this link](https://visualization-tool-git-feat-improve-profile-page-ixt1.vercel.app/en).
2. Log in as test user.
3. Open your profile.
4. ✅ See that there's a Views column in the tables.
5. Open the published chart and go back to the table.
6. ✅ See that the view count has increased.
---
=> feat: Add view stats to personal user profile

app/charts/shared/annotation-utils.ts, app/components/multi-select/option.tsx, app/components/multi-select/tags.tsx, app/components/select-tree.tsx, app/configurator/components/filters.tsx
Closes #2437
Closes #2438
Closes #2441
This PR:
- aligns interactive multi filter toggle to the left,
- fixes label and X icon overlaps and adds ellipses to `MultiFilter` component,
- fixes charts that bounced on every mouse move.
=> feat: Multi-filters UX improvements

.github/workflows/preload-varnish-cache.yml, CHANGELOG.md, e2e/varnish-cache-preload.ts
Closes #2449
This PR addresses the failing workflow for preloading the Varnish cache.
Potentially, this workflow could be tested locally, see [here](https://github.com/visualize-admin/visualization-tool?tab=readme-ov-file#4-developing-github-actions). However, it can also be directly tested through the Actions menu in this repo by triggering it manually.
<!-- ## Steps to reproduce
N/A
---
=> fix: Preload Varnish Cache

CHANGELOG.md, app/charts/shared/chart-data-filters/index.tsx, app/charts/shared/legend-color.tsx, app/charts/table/table-content.tsx, app/charts/table/table.tsx, app/components/multi-select/tags.tsx, app/components/select-tree.tsx, app/configurator/components/field-date-picker.tsx, app/configurator/components/field.tsx, app/configurator/components/filters.tsx, app/configurator/configurator-state/reducer.spec.tsx, app/configurator/configurator-state/reducer.tsx, app/locales/de/messages.po, app/locales/en/messages.po, app/locales/fr/messages.po, app/locales/it/messages.po
Closes #2443
Closes #2444
This PR polishes up the multi-filters implementation by:
- Changing "No filter" labels to "Select filter"
- Preventing from switching from range filter to single filter when hiding a table column
- Persisting sorting on data changes in table charts
Changes can be tested via https://visualization-tool-git-feat-multi-filters-adjustments-ixt1.vercel.app/
---
=> feat: Multi filter adjustments
